;; Copyright 2026 Aaron Alpar
;;
;; Licensed under the Apache License, Version 2.0 (the "License");
;; you may not use this file except in compliance with the License.
;; You may obtain a copy of the License at
;;
;;     http://www.apache.org/licenses/LICENSE-2.0
;;
;; Unless required by applicable law or agreed to in writing, software
;; distributed under the License is distributed on an "AS IS" BASIS,
;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;; See the License for the specific language governing permissions and
;; limitations under the License.

;;; wile-axis-b-params.scm — Phase 5.B per-slot ParamTypes analyzer.
;;;
;;; Reads plans/axis-b-manifest.scm (generated by audit_manifest_test.go in
;;; Phase 5.A), then for each primitive's Go function analyzes each declared
;;; parameter slot by scanning the SSA instruction stream for three patterns:
;;;
;;;   1. Direct RequireArg[*T]        — instr-level ssa-call to generic helper
;;;   2. Direct mc.Arg(i) + type-assert — invoke Arg, consuming ssa-type-assert
;;;   3. Delegator                    — primitive body is just a helper dispatch
;;;
;;; Each slot is classified into one of the §3.3 buckets:
;;;   Single-strict / Single-coercing / Declared-too-narrow /
;;;   Declared-too-wide / Union / Unguarded / Variadic-rest
;;;
;;; Outputs:
;;;   - plans/paramtypes-raw.scm                    (per-primitive S-expr records)
;;;   - plans/2026-04-20-paramtypes-inventory.md    (bucketed markdown)
;;;   - stdout summary                              (bucket counts)
;;;
;;; Invocation (from wile repo root):
;;;   wile-goast -f audit/wile-axis-b-params.scm
;;;
;;; Env overrides:
;;;   WILE_PARAMTYPES_MANIFEST  — manifest path (default: plans/axis-b-manifest.scm)
;;;   WILE_PARAMTYPES_RAW       — raw output (default: plans/paramtypes-raw.scm)
;;;   WILE_PARAMTYPES_INVENTORY — inventory  (default: plans/2026-04-20-paramtypes-inventory.md)
;;;   WILE_PARAMTYPES_NAMES     — comma-separated allowlist (default: all)
;;;
;;; See plans/2026-04-20-paramtypes-audit-design.md §3 for the analyzer design.
;;;
;;; v1 known limitations (enumerated here to prevent repeat triage):
;;;   - Post-gate filters are not traced. Primitives that call
;;;     RequireArg[*Number] then filter out *Complex programmatically
;;;     (e.g., abs, make-polar) report scanned=number even though the
;;;     effective accepted domain is real. Flagged as Declared-too-narrow
;;;     but is a false positive — the narrow declaration is correct.
;;;   - Dispatch-style type-asserts (predicates like real? with comma-ok
;;;     + both-branches-continue) are not distinguished from gate asserts.
;;;     Currently bucketed as Union; human review should treat declared=any
;;;     + dispatch union as correct.
;;;   - Only direct helper calls are classified. Two-hop delegators
;;;     (primitive → helper-A → helper-B) fall through to Unguarded unless
;;;     helper-A is in the extractor table.

(import (wile goast)
        (wile goast ssa)
        (wile goast utils)
        (srfi 1))

;; ---------------------------------------------------------------------------
;; Config / paths
;; ---------------------------------------------------------------------------

(define (env-or name default)
  (let ((v (get-environment-variable name)))
    (if (and v (not (string=? v "")))
        v
        default)))

(define default-manifest-path  "plans/axis-b-manifest.scm")
(define default-raw-output     "plans/paramtypes-raw.scm")
(define default-inventory-path "plans/2026-04-20-paramtypes-inventory.md")

(define (manifest-path)   (env-or "WILE_PARAMTYPES_MANIFEST"  default-manifest-path))
(define (raw-output-path) (env-or "WILE_PARAMTYPES_RAW"       default-raw-output))
(define (inventory-path)  (env-or "WILE_PARAMTYPES_INVENTORY" default-inventory-path))

;; ---------------------------------------------------------------------------
;; String utilities (defined early — EvalMultiple forward-references fail)
;; ---------------------------------------------------------------------------

(define (string-index s ch)
  (let ((n (string-length s)))
    (let loop ((i 0))
      (cond
        ((= i n) #f)
        ((char=? (string-ref s i) ch) i)
        (else (loop (+ i 1)))))))

(define (string-prefix? prefix s)
  (let ((pn (string-length prefix))
        (sn (string-length s)))
    (and (<= pn sn)
         (string=? prefix (substring s 0 pn)))))

(define (split-comma s)
  (let ((n (string-length s)))
    (if (= n 0) '()
        (let loop ((i 0) (start 0) (acc '()))
          (cond
            ((= i n) (reverse (cons (substring s start n) acc)))
            ((char=? (string-ref s i) #\,)
             (loop (+ i 1) (+ i 1) (cons (substring s start i) acc)))
            (else (loop (+ i 1) start acc)))))))

;; strip-type-annotation: "0:int" → "0", "t3" → "t3", "\"foo\":string" → "\"foo\""
(define (strip-type-annotation s)
  (let ((idx (string-index s #\:)))
    (if idx (substring s 0 idx) s)))

;; string-member? — list membership by string=?
(define (string-member? s lst)
  (cond
    ((null? lst) #f)
    ((string=? s (car lst)) #t)
    (else (string-member? s (cdr lst)))))

(define (union-strings xs)
  (let loop ((xs xs) (acc '()))
    (cond
      ((null? xs) (reverse acc))
      ((string-member? (car xs) acc) (loop (cdr xs) acc))
      (else (loop (cdr xs) (cons (car xs) acc))))))

;; ---------------------------------------------------------------------------
;; Manifest reader
;; ---------------------------------------------------------------------------

;; Manifest tuple shape (5 slots):
;;   (name return-type (param-types...) go-function go-source)
;; Generated by audit_manifest_test.go — see plans/2026-04-20-paramtypes-audit-design.md §3.1.

(define (read-manifest path)
  (let ((port (open-input-file path)))
    (let ((result (read port)))
      (close-input-port port)
      result)))

(define (entry-name e)        (list-ref e 0))
(define (entry-return-type e) (list-ref e 1))
(define (entry-param-types e) (list-ref e 2))
(define (entry-go-function e) (list-ref e 3))
(define (entry-go-source e)   (list-ref e 4))

;; Param-type strings use "..." prefix for variadic rest element
;; (per registry.go §7.1 convention).
(define (variadic-rest? type-str)
  (string-prefix? "..." type-str))

(define (strip-variadic type-str)
  (if (variadic-rest? type-str)
      (substring type-str 3 (string-length type-str))
      type-str))

;; ---------------------------------------------------------------------------
;; Filter to wile primitives + optional name allowlist
;; ---------------------------------------------------------------------------

(define wile-package-prefix "github.com/aalpar/wile/")

(define (wile-entry? entry)
  (let ((go-fn (entry-go-function entry)))
    (or (string=? go-fn "")
        (string-prefix? wile-package-prefix go-fn))))

(define (filter-entries entries)
  (let* ((wile-only (filter wile-entry? entries))
         (filter-str (env-or "WILE_PARAMTYPES_NAMES" "")))
    (cond
      ((string=? filter-str "") wile-only)
      (else
       (let ((allowed (split-comma filter-str)))
         (filter (lambda (e) (member (entry-name e) allowed))
                 wile-only))))))

;; ---------------------------------------------------------------------------
;; Function index
;; ---------------------------------------------------------------------------

;; Functions with generic instantiation render as "Pkg.Func[T1, T2]" in SSA but
;; the manifest stores the underlying Prim fn name. The index uses the full
;; SSA name; resolution matches exactly.
(define (build-func-index ssa-funcs)
  (map (lambda (f) (cons (nf f 'name) f)) ssa-funcs))

(define (resolve-function go-fn func-index)
  (let ((hit (assoc go-fn func-index)))
    (if hit (cdr hit) #f)))

;; ---------------------------------------------------------------------------
;; Pattern matchers — each returns an extracted fact or #f
;; ---------------------------------------------------------------------------

;; parse-generic-type-arg extracts T from "Pkg.Fn[T]" → "T".
;; Returns #f if no [ present. For multi-type-param functions returns the
;; full "[T1, T2]" content; caller splits on ", " if needed.
(define (parse-generic-type-arg func-name)
  (let* ((open-idx (string-index func-name #\[))
         (close-idx (string-index func-name #\])))
    (if (and open-idx close-idx (> close-idx open-idx))
        (substring func-name (+ open-idx 1) close-idx)
        #f)))

;; func-base-name strips the generic type-arg suffix: "Fn[T]" → "Fn".
(define (func-base-name func-name)
  (let ((open-idx (string-index func-name #\[)))
    (if open-idx
        (substring func-name 0 open-idx)
        func-name)))

;; args-list returns the 'args field of an ssa-call, or '() if absent/missing.
(define (args-list instr)
  (or (nf instr 'args) '()))

;; match-arg-invoke: is this a (ssa-call (mode . invoke) (method . "Arg"))?
;; Returns (slot . ssa-name) where slot is an integer, ssa-name is the result name.
;; The receiver is any value of type CallContext. v1 doesn't require recv="mc"
;; because some primitives rebind via a type-assert (e.g., PrimApply:
;;   mc := cc.(*machine.MachineContext); mc.Arg(0)). Accept any receiver since
;; wile primitives always have exactly one CallContext in scope.
(define (match-arg-invoke instr)
  (and (tag? instr 'ssa-call)
       (eq? (nf instr 'mode) 'invoke)
       (let ((method (nf instr 'method)))
         (and method
              (string=? method "Arg")
              (let ((args (args-list instr)))
                (and (pair? args)
                     (let* ((slot-str (strip-type-annotation (car args)))
                            (slot (string->number slot-str)))
                       (and slot
                            (cons slot (nf instr 'name))))))))))

;; match-requirearg: (ssa-call (func . "RequireArg[*T]") (args "mc" "N:int" sentinel name))
;; Returns (slot . type-string) where type-string is the T (quoted with * prefix).
(define (match-requirearg instr)
  (and (tag? instr 'ssa-call)
       (eq? (nf instr 'mode) 'call)
       (let ((func (nf instr 'func)))
         (and func
              (let ((base (func-base-name func)))
                (and (or (string=? base "RequireArg")
                         (string-prefix? "RequireArg" base)
                         (string-prefix? "github.com/aalpar/wile/registry/helpers.RequireArg" base))
                     (let ((type-arg (parse-generic-type-arg func))
                           (args (args-list instr)))
                       (and type-arg
                            (>= (length args) 2)
                            (let* ((slot-str (strip-type-annotation (list-ref args 1)))
                                   (slot (string->number slot-str)))
                              (and slot (cons slot type-arg)))))))))))

;; match-type-assert: (ssa-type-assert (x . "tN") (asserted-type . "..."))
;; Returns (x-name . asserted-type) or #f.
(define (match-type-assert instr)
  (and (tag? instr 'ssa-type-assert)
       (let ((x (nf instr 'x))
             (at (nf instr 'asserted-type)))
         (and x at (cons x at)))))

;; match-helper-call: (ssa-call (func . F) (args "mc" ...)) where F is in extractor table
;; Returns the helper short-name (func-base-name) or #f.
(define (match-helper-call instr)
  (and (tag? instr 'ssa-call)
       (eq? (nf instr 'mode) 'call)
       (let ((func (nf instr 'func))
             (args (args-list instr)))
         (and func
              (pair? args)
              (string=? (car args) "mc")
              (func-base-name func)))))

;; ---------------------------------------------------------------------------
;; Extractor table (curated)
;; ---------------------------------------------------------------------------
;;
;; Maps a helper's base name (without generic type-args, without package prefix)
;; to a slot-classification: a list of (slot-index . type-string) pairs.
;;
;; Variadic helpers use slot-index 'rest to denote "and the rest".
;; The special slot-index 'all means "applies to every param slot" (e.g.,
;; NumericFoldVariadic treats every supplied arg as a Number).
;;
;; Format:
;;   (helper-name . ((slot . type) ...))
;;
;; Sources:
;;   - helpers/args.go     (RequireArg, OptionalArg)
;;   - helpers/integer.go  (ExtractInteger, ParseSubrange)
;;   - helpers/value_conv.go (ExtractReal, ToFloat64, ToComplex128)
;;   - prim_* delegator patterns observed in the codebase
;;
;; Add entries as new delegator patterns surface in the kill-criterion check.

(define extractor-table
  '(;; RequireArg is handled by match-requirearg (extracts type from [T]);
    ;; listed here only for documentation completeness.

    ;; Direct-value extractors (called on mc.Arg(i) results)
    ("ExtractInteger"          . ((0 . "integer")))
    ("ExtractReal"             . ((0 . "real")))
    ("ToFloat64"               . ((0 . "real")))
    ("ToComplex128"            . ((0 . "complex")))
    ("ParseSubrange"           . ((0 . "exact-integer") (1 . "exact-integer")))

    ;; Numeric-fold / numeric-compare delegators (accept full CallContext,
    ;; iterate args internally). All slots share the same accepted type.
    ("NumericFoldVariadic"     . ((all . "number")))
    ("NumericFoldWithFirst"    . ((all . "number")))
    ("NumericChainCompare"     . ((all . "number")))
    ("NumericChainCompareReal" . ((all . "real")))
    ("NumericExtremum"         . ((all . "real")))
    ("IntegerFold"             . ((all . "integer")))
    ("GcdInt"                  . ((all . "integer")))

    ;; Sequence / list / string / char delegators
    ("AssocLookup"             . ((0 . "any") (1 . "list")))
    ("MemberLookup"            . ((0 . "any") (1 . "list")))
    ("ListToVector"            . ((0 . "list")))
    ("SequenceRef"             . ((0 . "seq") (1 . "exact-integer")))
    ("SequenceSet"             . ((0 . "seq") (1 . "exact-integer") (2 . "any")))
    ("SequenceLength"          . ((0 . "seq")))
    ("StringCompareVariadic"   . ((all . "string")))
    ("CharCompareVariadic"     . ((all . "character")))

    ;; Math-internal division delegators (package-local to extensions/math)
    ("realDivision"            . ((0 . "real") (1 . "real")))
    ))

(define (extractor-lookup helper-name)
  (let ((hit (assoc helper-name extractor-table)))
    (if hit (cdr hit) #f)))

;; ---------------------------------------------------------------------------
;; Go → wile type name mapping for direct-from-SSA types
;; ---------------------------------------------------------------------------
;;
;; asserted-type strings and RequireArg type-args reference fully-qualified Go
;; paths. Reuse the mapping from Phase 3.B (wile-axis-b.scm) but keep a local
;; copy — the scripts are intended to stay independent.

(define go-type->wile-type-table
  '(("github.com/aalpar/wile/values.Integer"             . "integer")
    ("github.com/aalpar/wile/values.BigInteger"          . "integer")
    ("github.com/aalpar/wile/values.Float"               . "flonum")
    ("github.com/aalpar/wile/values.BigFloat"            . "flonum")
    ("github.com/aalpar/wile/values.Rational"            . "rational")
    ("github.com/aalpar/wile/values.Complex"             . "complex")
    ("github.com/aalpar/wile/values.BigComplex"          . "complex")
    ("github.com/aalpar/wile/values.Number"              . "number")
    ("github.com/aalpar/wile/values.RealNumber"          . "real")
    ("github.com/aalpar/wile/values.ComplexNumber"       . "complex")
    ("github.com/aalpar/wile/values.Boolean"             . "boolean")
    ("github.com/aalpar/wile/values.Character"           . "character")
    ("github.com/aalpar/wile/values.String"              . "string")
    ("github.com/aalpar/wile/values.Symbol"              . "symbol")
    ("github.com/aalpar/wile/values.Byte"                . "byte")
    ("github.com/aalpar/wile/values.Pair"                . "pair")
    ("github.com/aalpar/wile/values.Tuple"               . "pair")
    ("github.com/aalpar/wile/values.Vector"              . "vector")
    ("github.com/aalpar/wile/values.ByteVector"          . "bytevector")
    ("github.com/aalpar/wile/values.Hashtable"           . "hashtable")
    ("github.com/aalpar/wile/values.CharacterInputPort"  . "textual-input-port")
    ("github.com/aalpar/wile/values.CharacterOutputPort" . "textual-output-port")
    ("github.com/aalpar/wile/values.BinaryInputPort"     . "binary-input-port")
    ("github.com/aalpar/wile/values.BinaryOutputPort"    . "binary-output-port")
    ("github.com/aalpar/wile/values.StringInputPort"     . "textual-input-port")
    ("github.com/aalpar/wile/values.StringOutputPort"    . "textual-output-port")
    ("github.com/aalpar/wile/values.ByteVectorInputPort" . "binary-input-port")
    ("github.com/aalpar/wile/values.ByteVectorOutputPort" . "binary-output-port")
    ("github.com/aalpar/wile/values.MachineClosure"      . "procedure")
    ("github.com/aalpar/wile/values.CaseLambdaClosure"   . "procedure")
    ;; Procedure-class interfaces + machine-level closure types. In Wile,
    ;; anything Callable is exposed as `procedure` at the Scheme level.
    ("github.com/aalpar/wile/values.Callable"            . "procedure")
    ("github.com/aalpar/wile/machine.MachineClosure"     . "procedure")
    ("github.com/aalpar/wile/machine.CaseLambdaClosure"  . "procedure")
    ("github.com/aalpar/wile/machine.ForeignClosure"     . "procedure")
    ("github.com/aalpar/wile/machine.Parameter"          . "procedure")
    ;; Port interfaces — map to the generic port family, relying on
    ;; narrower? to relate textual/binary variants when appropriate.
    ("github.com/aalpar/wile/values.InputPort"           . "input-port")
    ("github.com/aalpar/wile/values.OutputPort"          . "output-port")
    ("github.com/aalpar/wile/values.Port"                . "port")
    ("github.com/aalpar/wile/values.ByteVectorExtractor" . "binary-output-port")
    ("github.com/aalpar/wile/values.Value"               . "any")
    ("github.com/aalpar/wile/values.Record"              . "record")
    ("github.com/aalpar/wile/values.RecordType"          . "record-type")
    ("github.com/aalpar/wile/values.Promise"             . "promise")
    ("github.com/aalpar/wile/values.Box"                 . "box")
    ("github.com/aalpar/wile/values.OpaqueValue"         . "opaque")))

;; Go types in SSA may appear with or without leading '*'. Strip it for lookup.
(define (strip-star s)
  (if (and (> (string-length s) 0)
           (char=? (string-ref s 0) #\*))
      (substring s 1 (string-length s))
      s))

(define (go-type->wile-type go-type)
  (let ((key (strip-star go-type)))
    (let ((hit (assoc key go-type->wile-type-table)))
      (if hit (cdr hit) go-type))))

;; ---------------------------------------------------------------------------
;; Function-level scan: collect all per-slot facts across all blocks
;; ---------------------------------------------------------------------------

;; scan-function returns an alist:
;;   arg-invokes:  ((slot . ssa-name) ...)  — every mc.Arg(i) call's result name
;;   require-args: ((slot . go-type) ...)  — every RequireArg[*T] call
;;   type-asserts: ((x-name . go-type) ...) — every type-assert on a value
;;   helper-calls: (helper-short-name ...)  — delegator candidate calls
(define (scan-function ssa-func)
  (let loop ((blocks (nf ssa-func 'blocks))
             (arg-invokes '()) (require-args '())
             (type-asserts '()) (helper-calls '()))
    (cond
      ((or (not blocks) (null? blocks))
       (list (cons 'arg-invokes (reverse arg-invokes))
             (cons 'require-args (reverse require-args))
             (cons 'type-asserts (reverse type-asserts))
             (cons 'helper-calls (reverse helper-calls))))
      (else
       (let inner ((instrs (nf (car blocks) 'instrs))
                   (ai arg-invokes) (ra require-args)
                   (ta type-asserts) (hc helper-calls))
         (cond
           ((or (not instrs) (null? instrs))
            (loop (cdr blocks) ai ra ta hc))
           (else
            (let ((instr (car instrs)))
              (let ((m-ai (match-arg-invoke instr))
                    (m-ra (match-requirearg instr))
                    (m-ta (match-type-assert instr))
                    (m-hc (match-helper-call instr)))
              (inner (cdr instrs)
                     (if m-ai (cons m-ai ai) ai)
                     (if m-ra (cons m-ra ra) ra)
                     (if m-ta (cons m-ta ta) ta)
                     (if m-hc (cons m-hc hc) hc)))))))))))

;; ---------------------------------------------------------------------------
;; Per-slot gate derivation
;; ---------------------------------------------------------------------------

;; derive-slot-gate: given scan results and a slot index, return
;;   ((source . <tag>) (types . (wile-type ...)))
;; where <tag> ∈ {requirearg extractor typeassert delegator unguarded}.
;; Multi-source matches are possible (typeassert + delegator); we keep all in 'types.

(define (derive-slot-gate scan slot-index)
  (let* ((arg-invokes   (cdr (assq 'arg-invokes scan)))
         (require-args  (cdr (assq 'require-args scan)))
         (type-asserts  (cdr (assq 'type-asserts scan)))
         (helper-calls  (cdr (assq 'helper-calls scan))))

    ;; 1) Strict gate via RequireArg[*T]
    (let ((ra-hit (assv slot-index require-args)))
      (if ra-hit
          (list (cons 'source 'requirearg)
                (cons 'types (list (go-type->wile-type (cdr ra-hit)))))
          ;; 2) Direct mc.Arg(i) → find ssa-name, then collect consuming asserts
          (let ((ai-hit (assv slot-index arg-invokes)))
            (cond
              (ai-hit
               (let* ((ssa-name (cdr ai-hit))
                      (asserts (filter (lambda (p) (string=? (car p) ssa-name))
                                       type-asserts))
                      (types (map (lambda (p) (go-type->wile-type (cdr p)))
                                  asserts)))
                 (if (null? types)
                     (list (cons 'source 'unguarded-direct)
                           (cons 'types '()))
                     (list (cons 'source 'typeassert)
                           (cons 'types (union-strings types))))))
              ;; 3) Delegator: search extractor table for the first helper-call
              ;;    entry that maps this slot (or 'all)
              (else
               (let outer ((hs helper-calls))
                 (cond
                   ((null? hs)
                    (list (cons 'source 'unguarded)
                          (cons 'types '())))
                   (else
                    (let* ((h (car hs))
                           (entries (extractor-lookup h)))
                      (if entries
                          (let ((all-entry (assq 'all entries))
                                (slot-entry (assv slot-index entries)))
                            (cond
                              (all-entry
                               (list (cons 'source 'delegator)
                                     (cons 'helper h)
                                     (cons 'types (list (cdr all-entry)))))
                              (slot-entry
                               (list (cons 'source 'delegator)
                                     (cons 'helper h)
                                     (cons 'types (list (cdr slot-entry)))))
                              (else (outer (cdr hs)))))
                          (outer (cdr hs))))))))))))))

;; ---------------------------------------------------------------------------
;; Bucket classification (§3.3)
;; ---------------------------------------------------------------------------

;; Buckets:
;;   Single-strict       — RequireArg gate, declared matches scanned
;;   Single-coercing     — extractor/delegator gate, declared matches accepted domain
;;   Declared-too-narrow — declared strictly narrower than scanned (unsound under §2 enforcement)
;;   Declared-too-wide   — declared wider than scanned (imprecise but sound)
;;   Union               — multiple scanned types, no single ValueType covers union
;;   Unguarded           — no gate detected
;;   Variadic-rest       — rest slot; analysis done per-element (aggregated)

;; Rough type-narrower-than test: real < number, integer < real < number,
;; pair < list, {textual,binary}-{input,output}-port < {input,output}-port <
;; port, etc. Tightening this is its own subtask — the initial pass uses
;; equality and a small precedence table. Relationships outside the table
;; are conservatively classified as Declared-too-wide (not Union) because
;; the analyzer cannot confirm alignment and treating "don't know" as
;; "type-system gap" would inflate the Union bucket with noise.

(define narrow-than-table
  ;; (narrower . wider) pairs; transitively closed below.
  '(("integer" . "rational")
    ("rational" . "real")
    ("real" . "number")
    ("complex" . "number")
    ("pair" . "list")
    ("textual-input-port" . "input-port")
    ("textual-output-port" . "output-port")
    ("binary-input-port" . "input-port")
    ("binary-output-port" . "output-port")
    ("input-port" . "port")
    ("output-port" . "port")))

;; narrower? returns #t if a is strictly narrower than b. Computes transitive
;; closure lazily per call (table is small — no caching needed).
(define (narrower? a b)
  (cond
    ((string=? a b) #f)
    (else
     (let loop ((frontier (list a)) (visited '()))
       (cond
         ((null? frontier) #f)
         ((string-member? (car frontier) visited) (loop (cdr frontier) visited))
         (else
          (let ((parents (map cdr
                              (filter (lambda (p) (string=? (car p) (car frontier)))
                                      narrow-than-table))))
            (cond
              ((string-member? b parents) #t)
              (else (loop (append (cdr frontier) parents)
                          (cons (car frontier) visited)))))))))))

;; comparable? — are a and b in the same hierarchy?
(define (comparable? a b)
  (or (string=? a b)
      (narrower? a b)
      (narrower? b a)))

;; covers? — does declared subsume scanned? True if declared="any", declared
;; equals scanned, or declared is a strict ancestor of scanned.
(define (covers? declared scanned)
  (or (string=? declared "any")
      (string=? declared scanned)
      (narrower? scanned declared)))

;; covers-all? — does declared cover every scanned type in the union?
;; Used to distinguish "declared-any-over-a-union" (Declared-too-wide) from
;; "real type-system gap" (Union).
(define (covers-all? declared scanned-types)
  (let loop ((ts scanned-types))
    (cond
      ((null? ts) #t)
      ((covers? declared (car ts)) (loop (cdr ts)))
      (else #f))))

;; classify-slot returns a bucket symbol.
;;   declared: single type-name string (or "any")
;;   gate:     result of derive-slot-gate — alist
(define (classify-slot declared gate is-variadic-rest?)
  (cond
    (is-variadic-rest? 'Variadic-rest)
    (else
     (let ((source (cdr (assq 'source gate)))
           (types (cdr (assq 'types gate))))
       (cond
         ;; unguarded-direct (mc.Arg(i) extracted but no consuming type-assert)
         ;; with declared=any is an HONEST declaration — the primitive
         ;; legitimately accepts any value (e.g., cons, eq?, box). Classify as
         ;; Single-coercing so it doesn't inflate the Unguarded bucket.
         ((and (eq? source 'unguarded-direct) (string=? declared "any"))
          'Single-coercing)
         ((eq? source 'unguarded) 'Unguarded)
         ((eq? source 'unguarded-direct) 'Unguarded)
         ((= (length types) 0) 'Unguarded)
         ((= (length types) 1)
          (let ((scanned (car types)))
            (cond
              ;; declared = scanned: clean
              ((string=? declared scanned)
               (if (eq? source 'requirearg) 'Single-strict 'Single-coercing))
              ;; declared = "any": too wide regardless of scanned
              ((string=? declared "any") 'Declared-too-wide)
              ;; declared strictly narrower than scanned: unsound
              ((narrower? declared scanned) 'Declared-too-narrow)
              ;; declared strictly wider than scanned: imprecise
              ((narrower? scanned declared) 'Declared-too-wide)
              ;; no relation: conservatively declared-too-wide (analyzer uncertain)
              (else 'Declared-too-wide))))
         ;; Multi-type: if declared covers every scanned member, the union is
         ;; representable by the existing declared type (predicate dispatch,
         ;; TypeAny-with-variant-branches). That's imprecise but sound —
         ;; bucket as Declared-too-wide. Only when declared fails to cover
         ;; the full union is it a genuine type-system gap → Union.
         ((covers-all? declared types) 'Declared-too-wide)
         (else 'Union))))))

;; ---------------------------------------------------------------------------
;; Per-entry analysis
;; ---------------------------------------------------------------------------

;; analyze-entry: produce an (entry ...) record.
(define (analyze-entry entry func-index)
  (let* ((name (entry-name entry))
         (go-fn (entry-go-function entry))
         (go-source (entry-go-source entry))
         (param-types (entry-param-types entry))
         (n-slots (length param-types))
         (fn (resolve-function go-fn func-index)))
    (cond
      ((or (not fn) (string=? go-fn "") (= n-slots 0))
       (list (cons 'name name)
             (cons 'go-function go-fn)
             (cons 'go-source go-source)
             (cons 'param-count n-slots)
             (cons 'status (if (= n-slots 0) 'no-params 'unresolved))
             (cons 'slots '())))
      (else
       (let ((scan (scan-function fn)))
         (let loop ((i 0) (acc '()))
           (cond
             ((= i n-slots)
              (list (cons 'name name)
                    (cons 'go-function go-fn)
                    (cons 'go-source go-source)
                    (cons 'param-count n-slots)
                    (cons 'status 'resolved)
                    (cons 'slots (reverse acc))))
             (else
              (let* ((declared-raw (list-ref param-types i))
                     (is-rest? (and (variadic-rest? declared-raw)
                                    (= i (- n-slots 1))))
                     (declared (strip-variadic declared-raw))
                     (gate (derive-slot-gate scan i))
                     (bucket (classify-slot declared gate is-rest?)))
                (loop (+ i 1)
                      (cons (list (cons 'index i)
                                  (cons 'declared declared)
                                  (cons 'variadic-rest is-rest?)
                                  (cons 'gate gate)
                                  (cons 'bucket bucket))
                            acc)))))))))))

;; ---------------------------------------------------------------------------
;; Output — raw S-expression
;; ---------------------------------------------------------------------------

(define (write-scheme-string port s)
  (display "\"" port)
  (let ((n (string-length s)))
    (let loop ((i 0))
      (cond
        ((= i n) #f)
        (else
         (let ((c (string-ref s i)))
           (cond
             ((char=? c #\") (display "\\\"" port))
             ((char=? c #\\) (display "\\\\" port))
             (else (display c port)))
           (loop (+ i 1)))))))
  (display "\"" port))

(define (write-string-list port xs)
  (display "(" port)
  (let loop ((xs xs) (first? #t))
    (cond
      ((null? xs) (display ")" port))
      (else
       (when (not first?) (display " " port))
       (write-scheme-string port (car xs))
       (loop (cdr xs) #f)))))

(define (emit-raw-slot port slot)
  (display "    (slot " port)
  (display (cdr (assq 'index slot)) port) (display "\n" port)
  (display "      (declared " port)
  (write-scheme-string port (cdr (assq 'declared slot)))
  (display ")\n" port)
  (display "      (variadic-rest " port)
  (display (cdr (assq 'variadic-rest slot)) port) (display ")\n" port)
  (display "      (gate-source " port)
  (display (cdr (assq 'source (cdr (assq 'gate slot)))) port)
  (display ")\n" port)
  (display "      (gate-types " port)
  (write-string-list port (cdr (assq 'types (cdr (assq 'gate slot)))))
  (display ")\n" port)
  (display "      (bucket " port)
  (display (cdr (assq 'bucket slot)) port) (display "))\n" port))

(define (emit-raw-entry port e)
  (display "(primitive\n" port)
  (display "  (name " port)
  (write-scheme-string port (cdr (assq 'name e)))
  (display ")\n" port)
  (display "  (go-function " port)
  (write-scheme-string port (cdr (assq 'go-function e)))
  (display ")\n" port)
  (display "  (go-source " port)
  (write-scheme-string port (cdr (assq 'go-source e)))
  (display ")\n" port)
  (display "  (param-count " port)
  (display (cdr (assq 'param-count e)) port) (display ")\n" port)
  (display "  (status " port)
  (display (cdr (assq 'status e)) port) (display ")\n" port)
  (display "  (slots\n" port)
  (for-each (lambda (s) (emit-raw-slot port s))
            (cdr (assq 'slots e)))
  (display "  ))\n" port))

(define (write-raw-output entries path)
  (let ((port (open-output-file path)))
    (display ";; ParamTypes audit raw — generated by wile-axis-b-params.scm\n" port)
    (display ";; Phase 5.B per-slot analysis. See plans/2026-04-20-paramtypes-audit-design.md.\n" port)
    (display ";; Do not edit by hand — re-run: wile-goast -f audit/wile-axis-b-params.scm\n\n" port)
    (for-each (lambda (e) (emit-raw-entry port e)) entries)
    (close-output-port port)))

;; ---------------------------------------------------------------------------
;; Output — markdown inventory
;; ---------------------------------------------------------------------------

(define bucket-order
  '(Single-strict Single-coercing Declared-too-narrow Declared-too-wide
    Union Variadic-rest Unguarded))

(define bucket-descriptions
  '((Single-strict       . "Single strict gate (RequireArg[*T]), declared matches scanned. Clean.")
    (Single-coercing     . "Single coercing extractor/delegator, declared matches accepted domain. Clean.")
    (Declared-too-narrow . "Declared ValueType is strictly narrower than scanned accepted domain. **Potentially unsound under Phase-2 enforcement** — but note: v1 analyzer does not trace post-gate filters, so entries using `RequireArg[Wider] + in-body filter` (e.g., `abs`, `make-polar` using `RequireArg[Number]` + `isRealNumber` reject) are false positives — the declared type matches the *effective* post-filter domain. Manual review required per entry before any annotation change.")
    (Declared-too-wide   . "Declared is wider than scanned (e.g., TypeAny where impl strictly requires TypeString). Imprecise but sound. Lower-priority tightening.")
    (Union               . "Scanned accepts multiple types; no single ValueType covers the union. Feeds TypeUnion / TypeMaybe extension evidence.")
    (Variadic-rest       . "Rest slot; analysis applies per-element. Aggregate stats computed separately.")
    (Unguarded           . "No type check detected. Declared is typically TypeAny or missing. High count signals missing extractor-table entries — see kill criterion (>30% → expand table).")))

;; Group slots across all entries into bucket → slot-records
(define (all-slots entries)
  (apply append
         (map (lambda (e)
                (let ((name (cdr (assq 'name e)))
                      (src  (cdr (assq 'go-source e))))
                  (map (lambda (s)
                         (list (cons 'primitive name)
                               (cons 'go-source src)
                               (cons 'slot s)))
                       (cdr (assq 'slots e)))))
              entries)))

(define (group-slots-by-bucket slot-recs)
  (let loop ((rs slot-recs) (groups '()))
    (cond
      ((null? rs) groups)
      (else
       (let* ((r (car rs))
              (b (cdr (assq 'bucket (cdr (assq 'slot r)))))
              (hit (assq b groups)))
         (loop (cdr rs)
               (if hit
                   (begin (set-cdr! hit (cons r (cdr hit))) groups)
                   (cons (cons b (list r)) groups))))))))

(define (bucket-slots groups b)
  (let ((hit (assq b groups)))
    (if hit (reverse (cdr hit)) '())))

;; pct-string formats n/total as "X%", or "<1%" for small non-zero ratios
;; (prevents signal loss on buckets like 3/476 which truncate to 0%).
(define (pct-string n total)
  (cond
    ((or (= total 0) (= n 0)) "0%")
    (else
     (let ((pct (quotient (* n 100) total)))
       (cond
         ((= pct 0) "<1%")
         (else (string-append (number->string pct) "%")))))))

(define (display-list-joined port xs sep)
  (let loop ((xs xs) (first? #t))
    (cond
      ((null? xs) #f)
      (else
       (when (not first?) (display sep port))
       (display (car xs) port)
       (loop (cdr xs) #f)))))

(define (emit-markdown-inventory entries path)
  (let* ((port (open-output-file path))
         (slot-recs (all-slots entries))
         (groups (group-slots-by-bucket slot-recs))
         (n-entries (length entries))
         (n-slots (length slot-recs)))
    (display "# Phase 5.B — ParamTypes Per-Slot Inventory\n\n" port)
    (display "Generated by `wile-goast -f audit/wile-axis-b-params.scm`.\n" port)
    (display "See `plans/2026-04-20-paramtypes-audit-design.md` §3 for analyzer design.\n\n" port)
    (display (string-append "Primitives analyzed: " (number->string n-entries) "  \n") port)
    (display (string-append "Total parameter slots: " (number->string n-slots) "\n\n") port)
    (display "| Bucket | Count | % |\n|---|---|---|\n" port)
    (for-each
      (lambda (b)
        (let* ((slots (bucket-slots groups b))
               (n (length slots)))
          (display "| " port) (display b port)
          (display " | " port) (display n port)
          (display " | " port) (display (pct-string n n-slots) port)
          (display " |\n" port)))
      bucket-order)
    (newline port)
    (for-each
      (lambda (b)
        (let* ((slots (bucket-slots groups b))
               (n (length slots)))
          (when (> n 0)
            (display "## " port) (display b port)
            (display " (" port) (display n port) (display ")\n\n" port)
            (let ((desc (assq b bucket-descriptions)))
              (when desc
                (display (cdr desc) port)
                (display "\n\n" port)))
            (display "| Primitive | Slot | Declared | Scanned | Source | go-source |\n" port)
            (display "|---|---|---|---|---|---|\n" port)
            (for-each
              (lambda (r)
                (let* ((prim (cdr (assq 'primitive r)))
                       (src  (cdr (assq 'go-source r)))
                       (slot (cdr (assq 'slot r)))
                       (i    (cdr (assq 'index slot)))
                       (decl (cdr (assq 'declared slot)))
                       (gate (cdr (assq 'gate slot)))
                       (types (cdr (assq 'types gate)))
                       (source (cdr (assq 'source gate))))
                  (display "| `" port) (display prim port) (display "` | " port)
                  (display i port) (display " | " port)
                  (display decl port) (display " | " port)
                  (if (null? types) (display "—" port)
                      (display-list-joined port types ", "))
                  (display " | " port) (display source port)
                  (display " | `" port) (display src port) (display "` |\n" port)))
              slots)
            (newline port))))
      bucket-order)
    (close-output-port port)))

;; ---------------------------------------------------------------------------
;; Stdout summary
;; ---------------------------------------------------------------------------

(define (emit-summary entries)
  (let* ((slot-recs (all-slots entries))
         (groups (group-slots-by-bucket slot-recs))
         (n-entries (length entries))
         (n-slots (length slot-recs)))
    (display "\nParamTypes summary: ") (display n-entries)
    (display " primitives, ") (display n-slots) (display " slots\n")
    (for-each
      (lambda (b)
        (let ((n (length (bucket-slots groups b))))
          (when (> n 0)
            (display "  ") (display b) (display ": ") (display n) (newline))))
      bucket-order)
    ;; Kill-criterion check
    (let ((unguarded (length (bucket-slots groups 'Unguarded))))
      (when (> n-slots 0)
        (let ((pct (quotient (* unguarded 100) n-slots)))
          (display "\nUnguarded: ") (display (pct-string unguarded n-slots)) (display " ")
          (cond
            ((> pct 30)
             (display "— EXCEEDS KILL CRITERION (30%) — expand extractor table\n"))
            (else (display "— below kill criterion\n"))))))))

;; ---------------------------------------------------------------------------
;; Main
;; ---------------------------------------------------------------------------

(define (main)
  (let ((entries (filter-entries (read-manifest (manifest-path)))))
    (display "wile-axis-b-params: loaded ") (display (length entries))
    (display " manifest entries\n")
    (parameterize ((current-go-target "github.com/aalpar/wile/..."))
      (display "wile-axis-b-params: building SSA (takes ~1 minute)\n")
      (let* ((funcs (go-ssa-build))
             (idx (build-func-index funcs)))
        (display "wile-axis-b-params: indexed ") (display (length funcs))
        (display " SSA functions\n")
        (let ((results (map (lambda (e) (analyze-entry e idx)) entries)))
          (display "wile-axis-b-params: analyzed ") (display (length results))
          (display " primitives\n")
          (let ((rpath (raw-output-path)))
            (write-raw-output results rpath)
            (display "wile-axis-b-params: wrote raw to ") (display rpath) (newline))
          (let ((ipath (inventory-path)))
            (emit-markdown-inventory results ipath)
            (display "wile-axis-b-params: wrote inventory to ") (display ipath) (newline))
          (emit-summary results))))))

(main)
