version: "2"

run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocritic
    - revive
    - nilerr
    - whitespace

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - wile

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - appendAssign
      - commentedOutCode
      - hugeParam
      - rangeValCopy
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    - path: cmd/
      linters:
        - unparam
