;;; Generated by tools/sage/verify_algebra.sage --snapshot
;;; Oracle: SageMath SageMath version 10.8, Release Date: 2025-12-18
;;; Date: 2026-04-12
;;; Seed: 42
;;; DO NOT EDIT — regenerate with:
;;;   sage tools/sage/verify_algebra.sage --snapshot

(import (scheme base)
        (chibi test)
        (wile algebra)
        (wile algebra symbolic)
        (wile algebra rewrite)
)

(test-begin "sage-rewriting-lattice")

(define proto
  (sexp-term-protocol
    (lambda (a b)
      (cond
        ((and (symbol? a) (symbol? b))
         (string<? (symbol->string a) (symbol->string b)))
        ((symbol? a) #t)
        ((symbol? b) #f)
        (else #f)))))

(define norm
  (make-recursive-normalizer
    (lattice->theory (powerset-lattice '(1 2 3)) 'join 'meet)
    proto))

;; (join a (join (meet c (join c a)) (meet (join c c) b))) normalizes to (join a c)
(let-values (((result trace) (norm '(join a (join (meet c (join c a)) (meet (join c c) b))))))
  (test '(join a c) result))

;; a normalizes to a
(let-values (((result trace) (norm 'a)))
  (test 'a result))

;; (join (meet c (join b (join b b))) (meet (join (join c b) (meet b c)) (meet (meet c a) (join a b)))) normalizes to (join (meet b c) (meet (join b c) (meet a (meet c (join a b)))))
(let-values (((result trace) (norm '(join (meet c (join b (join b b))) (meet (join (join c b) (meet b c)) (meet (meet c a) (join a b)))))))
  (test '(join (meet b c) (meet (join b c) (meet a (meet c (join a b))))) result))

;; b normalizes to b
(let-values (((result trace) (norm 'b)))
  (test 'b result))

;; (meet (join (join (meet c a) (join c b)) a) c) normalizes to (meet c (join a (join (meet a c) (join b c))))
(let-values (((result trace) (norm '(meet (join (join (meet c a) (join c b)) a) c))))
  (test '(meet c (join a (join (meet a c) (join b c)))) result))

;; (meet (join (join a a) (meet c c)) (join c c)) normalizes to c
(let-values (((result trace) (norm '(meet (join (join a a) (meet c c)) (join c c)))))
  (test 'c result))

;; b normalizes to b
(let-values (((result trace) (norm 'b)))
  (test 'b result))

;; (join (meet (join (join b b) c) c) (meet (meet (join a a) (join b c)) (meet b (meet a b)))) normalizes to (join c (meet a (meet (join b c) (meet b (meet a b)))))
(let-values (((result trace) (norm '(join (meet (join (join b b) c) c) (meet (meet (join a a) (join b c)) (meet b (meet a b)))))))
  (test '(join c (meet a (meet (join b c) (meet b (meet a b))))) result))

;; (meet c (meet (meet (join a b) (meet b c)) (meet c a))) normalizes to (meet c (meet (join a b) (meet b (meet c (meet a c)))))
(let-values (((result trace) (norm '(meet c (meet (meet (join a b) (meet b c)) (meet c a))))))
  (test '(meet c (meet (join a b) (meet b (meet c (meet a c))))) result))

;; (meet (meet (join (join b a) (join b b)) (join (join c c) (meet c c))) b) normalizes to (meet b (meet c (join b (join a b))))
(let-values (((result trace) (norm '(meet (meet (join (join b a) (join b b)) (join (join c c) (meet c c))) b))))
  (test '(meet b (meet c (join b (join a b)))) result))

;; a normalizes to a
(let-values (((result trace) (norm 'a)))
  (test 'a result))

;; b normalizes to b
(let-values (((result trace) (norm 'b)))
  (test 'b result))

;; c normalizes to c
(let-values (((result trace) (norm 'c)))
  (test 'c result))

;; b normalizes to b
(let-values (((result trace) (norm 'b)))
  (test 'b result))

;; (join (join (join c (meet c a)) (join a (join b a))) c) normalizes to (join c (join c (join a (join a b))))
(let-values (((result trace) (norm '(join (join (join c (meet c a)) (join a (join b a))) c))))
  (test '(join c (join c (join a (join a b)))) result))

;; (join b (join (meet (meet b a) (meet c c)) (join a a))) normalizes to (join b (join a (meet c (meet a b))))
(let-values (((result trace) (norm '(join b (join (meet (meet b a) (meet c c)) (join a a))))))
  (test '(join b (join a (meet c (meet a b)))) result))

;; (join (meet (join (join a c) (meet c c)) (meet (join c b) (join b b))) (meet a c)) normalizes to (join (meet b (join c (join a c))) (meet a c))
(let-values (((result trace) (norm '(join (meet (join (join a c) (meet c c)) (meet (join c b) (join b b))) (meet a c)))))
  (test '(join (meet b (join c (join a c))) (meet a c)) result))

;; a normalizes to a
(let-values (((result trace) (norm 'a)))
  (test 'a result))

;; (meet b b) normalizes to b
(let-values (((result trace) (norm '(meet b b))))
  (test 'b result))

;; (meet (join (meet c a) (join b b)) (join a (meet c (join b c)))) normalizes to (meet (join b (meet a c)) (join a c))
(let-values (((result trace) (norm '(meet (join (meet c a) (join b b)) (join a (meet c (join b c)))))))
  (test '(meet (join b (meet a c)) (join a c)) result))

;; b normalizes to b
(let-values (((result trace) (norm 'b)))
  (test 'b result))

;; b normalizes to b
(let-values (((result trace) (norm 'b)))
  (test 'b result))

;; (join (join a (join (join a c) (meet b b))) (join (join (meet a b) (join a a)) (meet (meet a b) (join b c)))) normalizes to (join a (join a (join b (join a c))))
(let-values (((result trace) (norm '(join (join a (join (join a c) (meet b b))) (join (join (meet a b) (join a a)) (meet (meet a b) (join b c)))))))
  (test '(join a (join a (join b (join a c)))) result))

;; c normalizes to c
(let-values (((result trace) (norm 'c)))
  (test 'c result))

;; (meet (join (meet a b) (join (meet a b) b)) (join (join b (join a a)) (meet (join c a) (join b b)))) normalizes to b
(let-values (((result trace) (norm '(meet (join (meet a b) (join (meet a b) b)) (join (join b (join a a)) (meet (join c a) (join b b)))))))
  (test 'b result))

;; (join (meet (join (meet c c) (meet c c)) (meet c c)) (meet (join c a) (meet (join a a) a))) normalizes to (join a c)
(let-values (((result trace) (norm '(join (meet (join (meet c c) (meet c c)) (meet c c)) (meet (join c a) (meet (join a a) a))))))
  (test '(join a c) result))

;; a normalizes to a
(let-values (((result trace) (norm 'a)))
  (test 'a result))

;; (meet (join (join (meet a b) (meet b a)) (join (meet c c) c)) c) normalizes to c
(let-values (((result trace) (norm '(meet (join (join (meet a b) (meet b a)) (join (meet c c) c)) c))))
  (test 'c result))

;; (meet (join (join (meet a b) (join a c)) (meet (join b c) (join b c))) c) normalizes to (meet c (join (meet a b) (join a (join c (join b c)))))
(let-values (((result trace) (norm '(meet (join (join (meet a b) (join a c)) (meet (join b c) (join b c))) c))))
  (test '(meet c (join (meet a b) (join a (join c (join b c))))) result))

;; (meet (join (join b (join c c)) (join (meet c b) (join b a))) (meet (join (meet c b) (join a a)) (join c (meet c b)))) normalizes to (meet (join b (join c (join (meet b c) (join a b)))) (meet c (join a (meet b c))))
(let-values (((result trace) (norm '(meet (join (join b (join c c)) (join (meet c b) (join b a))) (meet (join (meet c b) (join a a)) (join c (meet c b)))))))
  (test '(meet (join b (join c (join (meet b c) (join a b)))) (meet c (join a (meet b c)))) result))

;; (meet a b) normalizes to (meet a b)
(let-values (((result trace) (norm '(meet a b))))
  (test '(meet a b) result))

;; (join a (meet (join a (join c c)) b)) normalizes to (join a (meet b (join a c)))
(let-values (((result trace) (norm '(join a (meet (join a (join c c)) b)))))
  (test '(join a (meet b (join a c))) result))

;; (join (meet b (join (meet c b) (join c b))) b) normalizes to b
(let-values (((result trace) (norm '(join (meet b (join (meet c b) (join c b))) b))))
  (test 'b result))

;; b normalizes to b
(let-values (((result trace) (norm 'b)))
  (test 'b result))

;; (meet (join (meet (meet b c) a) (join (meet c c) (meet a a))) (join (meet c (meet a a)) b)) normalizes to (meet (join (meet a (meet b c)) (join a c)) (join b (meet a c)))
(let-values (((result trace) (norm '(meet (join (meet (meet b c) a) (join (meet c c) (meet a a))) (join (meet c (meet a a)) b)))))
  (test '(meet (join (meet a (meet b c)) (join a c)) (join b (meet a c))) result))

;; a normalizes to a
(let-values (((result trace) (norm 'a)))
  (test 'a result))

;; (meet (join b c) (meet a (join (join b a) b))) normalizes to (meet (join b c) (meet a (join b (join a b))))
(let-values (((result trace) (norm '(meet (join b c) (meet a (join (join b a) b))))))
  (test '(meet (join b c) (meet a (join b (join a b)))) result))

;; c normalizes to c
(let-values (((result trace) (norm 'c)))
  (test 'c result))

;; (meet b (meet (join a (meet b b)) (join (meet a a) (meet c a)))) normalizes to (meet a b)
(let-values (((result trace) (norm '(meet b (meet (join a (meet b b)) (join (meet a a) (meet c a)))))))
  (test '(meet a b) result))

;; (join (meet (join (meet a b) (join a b)) (meet (join a a) a)) (meet (join a b) c)) normalizes to (join (meet a (join (meet a b) (join a b))) (meet c (join a b)))
(let-values (((result trace) (norm '(join (meet (join (meet a b) (join a b)) (meet (join a a) a)) (meet (join a b) c)))))
  (test '(join (meet a (join (meet a b) (join a b))) (meet c (join a b))) result))

;; (meet (meet b (join (join a c) c)) (meet a (meet (join b c) (meet b c)))) normalizes to (meet b (meet (join c (join a c)) (meet a (meet (join b c) (meet b c)))))
(let-values (((result trace) (norm '(meet (meet b (join (join a c) c)) (meet a (meet (join b c) (meet b c)))))))
  (test '(meet b (meet (join c (join a c)) (meet a (meet (join b c) (meet b c))))) result))

;; (join (join (meet b (join a b)) (meet (join c a) c)) (join b (meet b (meet a c)))) normalizes to (join b (join b c))
(let-values (((result trace) (norm '(join (join (meet b (join a b)) (meet (join c a) c)) (join b (meet b (meet a c)))))))
  (test '(join b (join b c)) result))

;; c normalizes to c
(let-values (((result trace) (norm 'c)))
  (test 'c result))

;; a normalizes to a
(let-values (((result trace) (norm 'a)))
  (test 'a result))

;; (join c c) normalizes to c
(let-values (((result trace) (norm '(join c c))))
  (test 'c result))

;; (meet (join (meet c (meet c a)) (join (join b a) (join c c))) (meet (meet (meet c b) (join c a)) b)) normalizes to (meet (join (meet c (meet a c)) (join c (join a b))) (meet b (meet b c)))
(let-values (((result trace) (norm '(meet (join (meet c (meet c a)) (join (join b a) (join c c))) (meet (meet (meet c b) (join c a)) b)))))
  (test '(meet (join (meet c (meet a c)) (join c (join a b))) (meet b (meet b c))) result))

;; (meet (join (meet a c) (meet (join a c) (meet a c))) c) normalizes to (meet c (meet a c))
(let-values (((result trace) (norm '(meet (join (meet a c) (meet (join a c) (meet a c))) c))))
  (test '(meet c (meet a c)) result))

;; (meet (meet (join (meet c b) (join a b)) (join (join c c) (join b c))) c) normalizes to (meet c (meet (join (meet b c) (join a b)) (join c (join b c))))
(let-values (((result trace) (norm '(meet (meet (join (meet c b) (join a b)) (join (join c c) (join b c))) c))))
  (test '(meet c (meet (join (meet b c) (join a b)) (join c (join b c)))) result))

;; (meet b (meet (meet (meet c b) (join c a)) c)) normalizes to (meet b (meet c (meet b c)))
(let-values (((result trace) (norm '(meet b (meet (meet (meet c b) (join c a)) c)))))
  (test '(meet b (meet c (meet b c))) result))

;; c normalizes to c
(let-values (((result trace) (norm 'c)))
  (test 'c result))

;; (meet a (meet (meet b (meet a c)) a)) normalizes to (meet a (meet a (meet b (meet a c))))
(let-values (((result trace) (norm '(meet a (meet (meet b (meet a c)) a)))))
  (test '(meet a (meet a (meet b (meet a c)))) result))

;; (meet (join (join (join b b) a) (meet b (meet a b))) (join (join (join b c) (meet a a)) (join (meet b b) c))) normalizes to (meet (join a b) (join a (join b c)))
(let-values (((result trace) (norm '(meet (join (join (join b b) a) (meet b (meet a b))) (join (join (join b c) (meet a a)) (join (meet b b) c))))))
  (test '(meet (join a b) (join a (join b c))) result))

;; (meet (meet b (meet (join a a) (join c c))) (join (join (meet a a) c) (join a b))) normalizes to (meet b (meet a (meet c (join a (join c (join a b))))))
(let-values (((result trace) (norm '(meet (meet b (meet (join a a) (join c c))) (join (join (meet a a) c) (join a b))))))
  (test '(meet b (meet a (meet c (join a (join c (join a b)))))) result))

;; b normalizes to b
(let-values (((result trace) (norm 'b)))
  (test 'b result))

;; b normalizes to b
(let-values (((result trace) (norm 'b)))
  (test 'b result))

;; (meet (join c c) (meet (join b (meet a a)) (meet (join c c) (meet a a)))) normalizes to (meet c (meet (join a b) (meet a c)))
(let-values (((result trace) (norm '(meet (join c c) (meet (join b (meet a a)) (meet (join c c) (meet a a)))))))
  (test '(meet c (meet (join a b) (meet a c))) result))

;; (join (join (meet (join b a) a) c) (meet (join (meet b a) (meet b c)) (meet (join b c) (meet c c)))) normalizes to (join c (join a (meet c (join (meet a b) (meet b c)))))
(let-values (((result trace) (norm '(join (join (meet (join b a) a) c) (meet (join (meet b a) (meet b c)) (meet (join b c) (meet c c)))))))
  (test '(join c (join a (meet c (join (meet a b) (meet b c))))) result))

;; c normalizes to c
(let-values (((result trace) (norm 'c)))
  (test 'c result))

;; (meet (meet (meet a (join a c)) (meet a (join a b))) (join (join a a) (meet a (meet a c)))) normalizes to a
(let-values (((result trace) (norm '(meet (meet (meet a (join a c)) (meet a (join a b))) (join (join a a) (meet a (meet a c)))))))
  (test 'a result))

;; c normalizes to c
(let-values (((result trace) (norm 'c)))
  (test 'c result))

;; (join (meet (meet (meet a b) (join b b)) (meet (meet c b) a)) c) normalizes to (join c (meet b (meet a (meet b (meet a (meet b c))))))
(let-values (((result trace) (norm '(join (meet (meet (meet a b) (join b b)) (meet (meet c b) a)) c))))
  (test '(join c (meet b (meet a (meet b (meet a (meet b c)))))) result))

;; (join (meet a (join (join c a) a)) c) normalizes to (join a c)
(let-values (((result trace) (norm '(join (meet a (join (join c a) a)) c))))
  (test '(join a c) result))

;; c normalizes to c
(let-values (((result trace) (norm 'c)))
  (test 'c result))

;; b normalizes to b
(let-values (((result trace) (norm 'b)))
  (test 'b result))

;; (join (join (join (meet a a) (meet b a)) (meet (join c b) a)) (meet (meet (meet c c) a) (join (join c c) (meet c c)))) normalizes to (join a (meet c (meet a c)))
(let-values (((result trace) (norm '(join (join (join (meet a a) (meet b a)) (meet (join c b) a)) (meet (meet (meet c c) a) (join (join c c) (meet c c)))))))
  (test '(join a (meet c (meet a c))) result))

;; a normalizes to a
(let-values (((result trace) (norm 'a)))
  (test 'a result))

;; (join (join (join c b) (join (join a b) a)) (join (join (meet b c) (join c b)) c)) normalizes to (join b (join c (join a (join a (join b (join c (join (meet b c) (join b c))))))))
(let-values (((result trace) (norm '(join (join (join c b) (join (join a b) a)) (join (join (meet b c) (join c b)) c)))))
  (test '(join b (join c (join a (join a (join b (join c (join (meet b c) (join b c)))))))) result))

;; a normalizes to a
(let-values (((result trace) (norm 'a)))
  (test 'a result))

;; (meet (join (join (meet b b) c) (meet b a)) (meet (meet (join a b) (meet a a)) (meet a (meet c b)))) normalizes to (meet (join b (join c (meet a b))) (meet a (meet (join a b) (meet a (meet b c)))))
(let-values (((result trace) (norm '(meet (join (join (meet b b) c) (meet b a)) (meet (meet (join a b) (meet a a)) (meet a (meet c b)))))))
  (test '(meet (join b (join c (meet a b))) (meet a (meet (join a b) (meet a (meet b c))))) result))

;; (join (meet c (join a (join a b))) (join (join a c) (meet (meet b c) c))) normalizes to (join (meet c (join a (join a b))) (join a c))
(let-values (((result trace) (norm '(join (meet c (join a (join a b))) (join (join a c) (meet (meet b c) c))))))
  (test '(join (meet c (join a (join a b))) (join a c)) result))

;; (meet (meet c (join (join a a) b)) b) normalizes to (meet b (meet c (join a b)))
(let-values (((result trace) (norm '(meet (meet c (join (join a a) b)) b))))
  (test '(meet b (meet c (join a b))) result))

;; (meet a (join (join a (join c c)) (join a (join a c)))) normalizes to a
(let-values (((result trace) (norm '(meet a (join (join a (join c c)) (join a (join a c)))))))
  (test 'a result))

;; (join (meet c (join (join a b) a)) (join a (meet (join a a) (join a a)))) normalizes to (join a (meet c (join a (join a b))))
(let-values (((result trace) (norm '(join (meet c (join (join a b) a)) (join a (meet (join a a) (join a a)))))))
  (test '(join a (meet c (join a (join a b)))) result))

;; (join a c) normalizes to (join a c)
(let-values (((result trace) (norm '(join a c))))
  (test '(join a c) result))

;; (meet b (meet (join (join a b) (meet b b)) a)) normalizes to (meet b (meet a (join b (join a b))))
(let-values (((result trace) (norm '(meet b (meet (join (join a b) (meet b b)) a)))))
  (test '(meet b (meet a (join b (join a b)))) result))

;; (meet (meet (join b a) c) (join (join (meet a a) (meet a a)) (join (meet b c) (join c c)))) normalizes to (meet c (meet (join a b) (join a c)))
(let-values (((result trace) (norm '(meet (meet (join b a) c) (join (join (meet a a) (meet a a)) (join (meet b c) (join c c)))))))
  (test '(meet c (meet (join a b) (join a c))) result))

;; (join (meet c (join (join b a) a)) (meet (meet (join a a) a) (join b (meet a b)))) normalizes to (join (meet c (join a (join a b))) (meet a b))
(let-values (((result trace) (norm '(join (meet c (join (join b a) a)) (meet (meet (join a a) a) (join b (meet a b)))))))
  (test '(join (meet c (join a (join a b))) (meet a b)) result))

;; (meet b a) normalizes to (meet a b)
(let-values (((result trace) (norm '(meet b a))))
  (test '(meet a b) result))

;; (join (join (join (join a b) (join b b)) a) (join c (join a b))) normalizes to (join a (join b (join a (join b (join c (join a b))))))
(let-values (((result trace) (norm '(join (join (join (join a b) (join b b)) a) (join c (join a b))))))
  (test '(join a (join b (join a (join b (join c (join a b)))))) result))

;; (meet (meet (meet (meet b c) (meet b b)) (join (meet b a) b)) (join c a)) normalizes to (meet b (meet b (meet b c)))
(let-values (((result trace) (norm '(meet (meet (meet (meet b c) (meet b b)) (join (meet b a) b)) (join c a)))))
  (test '(meet b (meet b (meet b c))) result))

;; (join a (meet (join (meet a b) c) a)) normalizes to a
(let-values (((result trace) (norm '(join a (meet (join (meet a b) c) a)))))
  (test 'a result))

;; (meet (join (join (join b a) a) (join b (meet a a))) (meet (meet (join b a) a) c)) normalizes to (meet (join a (join a b)) (meet a c))
(let-values (((result trace) (norm '(meet (join (join (join b a) a) (join b (meet a a))) (meet (meet (join b a) a) c)))))
  (test '(meet (join a (join a b)) (meet a c)) result))

;; (meet (meet (meet (meet a a) a) (join (join b b) (meet b a))) c) normalizes to (meet c (meet a b))
(let-values (((result trace) (norm '(meet (meet (meet (meet a a) a) (join (join b b) (meet b a))) c))))
  (test '(meet c (meet a b)) result))

;; a normalizes to a
(let-values (((result trace) (norm 'a)))
  (test 'a result))

;; (meet a (meet (join (meet c c) a) (join (meet c b) b))) normalizes to (meet a (meet b (join a c)))
(let-values (((result trace) (norm '(meet a (meet (join (meet c c) a) (join (meet c b) b))))))
  (test '(meet a (meet b (join a c))) result))

;; c normalizes to c
(let-values (((result trace) (norm 'c)))
  (test 'c result))

;; (join (join (meet (meet a c) (join b a)) c) (join (meet (meet b c) (meet c a)) (join (meet c a) (meet c c)))) normalizes to (join c (join (meet a (meet c (join a b))) (join c (meet b (meet c (meet a c))))))
(let-values (((result trace) (norm '(join (join (meet (meet a c) (join b a)) c) (join (meet (meet b c) (meet c a)) (join (meet c a) (meet c c)))))))
  (test '(join c (join (meet a (meet c (join a b))) (join c (meet b (meet c (meet a c)))))) result))

;; (join (meet (join b (meet b c)) a) (meet (join (meet c c) (meet a a)) (meet b (join a a)))) normalizes to (meet a b)
(let-values (((result trace) (norm '(join (meet (join b (meet b c)) a) (meet (join (meet c c) (meet a a)) (meet b (join a a)))))))
  (test '(meet a b) result))

;; (meet (join b a) (join (meet c (join a b)) (meet (join a b) (meet c c)))) normalizes to (meet (join a b) (meet c (join a b)))
(let-values (((result trace) (norm '(meet (join b a) (join (meet c (join a b)) (meet (join a b) (meet c c)))))))
  (test '(meet (join a b) (meet c (join a b))) result))

;; a normalizes to a
(let-values (((result trace) (norm 'a)))
  (test 'a result))

;; (meet (meet (join (meet b c) (join c b)) (meet (join c a) a)) a) normalizes to (meet a (meet a (join (meet b c) (join b c))))
(let-values (((result trace) (norm '(meet (meet (join (meet b c) (join c b)) (meet (join c a) a)) a))))
  (test '(meet a (meet a (join (meet b c) (join b c)))) result))

;; (meet (join (join (meet c a) b) c) (join (meet (meet a c) (join b c)) (meet (join b a) (join c a)))) normalizes to (meet (join c (join b (meet a c))) (join (meet a c) (meet (join a b) (join a c))))
(let-values (((result trace) (norm '(meet (join (join (meet c a) b) c) (join (meet (meet a c) (join b c)) (meet (join b a) (join c a)))))))
  (test '(meet (join c (join b (meet a c))) (join (meet a c) (meet (join a b) (join a c)))) result))

;; a normalizes to a
(let-values (((result trace) (norm 'a)))
  (test 'a result))

;; (meet b c) normalizes to (meet b c)
(let-values (((result trace) (norm '(meet b c))))
  (test '(meet b c) result))

;; (join (join (meet (meet c c) (meet a b)) (meet (meet c b) (join c b))) (meet b (join a b))) normalizes to (join b (join (meet c (meet a b)) (meet b c)))
(let-values (((result trace) (norm '(join (join (meet (meet c c) (meet a b)) (meet (meet c b) (join c b))) (meet b (join a b))))))
  (test '(join b (join (meet c (meet a b)) (meet b c))) result))

;; a normalizes to a
(let-values (((result trace) (norm 'a)))
  (test 'a result))

;; b normalizes to b
(let-values (((result trace) (norm 'b)))
  (test 'b result))

;; (join (meet c c) (join b (join (meet a b) (join c b)))) normalizes to (join c (join b (join (meet a b) (join b c))))
(let-values (((result trace) (norm '(join (meet c c) (join b (join (meet a b) (join c b)))))))
  (test '(join c (join b (join (meet a b) (join b c)))) result))

;; (join (join a a) (join (join (join c b) a) (meet (meet a a) b))) normalizes to (join a (join a (join b (join c (meet a b)))))
(let-values (((result trace) (norm '(join (join a a) (join (join (join c b) a) (meet (meet a a) b))))))
  (test '(join a (join a (join b (join c (meet a b))))) result))

;; (join (join (meet (meet b b) a) (meet (join a c) a)) (meet (join (meet c a) (join c b)) (join (join b b) (join a b)))) normalizes to (join (meet a b) (join a (meet (join (meet a c) (join b c)) (join b (join a b)))))
(let-values (((result trace) (norm '(join (join (meet (meet b b) a) (meet (join a c) a)) (meet (join (meet c a) (join c b)) (join (join b b) (join a b)))))))
  (test '(join (meet a b) (join a (meet (join (meet a c) (join b c)) (join b (join a b))))) result))


(test-end)
(test-exit)
