;;; sage-rewriting-boolean-algebra-test.scm — Generated by Sage oracle
;;; Oracle: SageMath version 10.8, Release Date: 2025-12-18
;;; Date: 2026-04-12
;;; Seed: 42
;;; DO NOT EDIT — regenerate with:
;;;   sage tools/sage/verify_algebra.sage --snapshot

(import (scheme base)
        (chibi test)
        (wile algebra)
        (wile algebra symbolic)
        (wile algebra rewrite))

(test-begin "sage-rewriting-boolean-algebra")

(define proto
  (sexp-term-protocol
    (lambda (a b)
      (cond
        ((and (symbol? a) (symbol? b))
         (string<? (symbol->string a) (symbol->string b)))
        ((symbol? a) #t)
        ((symbol? b) #f)
        (else #f)))))

(define norm
  (make-recursive-normalizer
    (boolean->theory (powerset-boolean '(x y z)) 'or 'and 'not)
    proto))

;; r normalizes to r
(let-values (((result trace) (norm 'r)))
  (test 'r result))

;; (not p) normalizes to (not p)
(let-values (((result trace) (norm '(not p))))
  (test '(not p) result))

;; p normalizes to p
(let-values (((result trace) (norm 'p)))
  (test 'p result))

;; (and (or q (or (not q) (not q))) (not p)) normalizes to (and (or q (not q)) (not p))
(let-values (((result trace) (norm '(and (or q (or (not q) (not q))) (not p)))))
  (test '(and (or q (not q)) (not p)) result))

;; (or r (or (not (and q q)) p)) normalizes to (or r (or p (not q)))
(let-values (((result trace) (norm '(or r (or (not (and q q)) p)))))
  (test '(or r (or p (not q))) result))

;; (and (and (not (and q q)) q) (not (not (not r)))) normalizes to (and q (and (not q) (not r)))
(let-values (((result trace) (norm '(and (and (not (and q q)) q) (not (not (not r)))))))
  (test '(and q (and (not q) (not r))) result))

;; (not (and (and (and q p) (and r r)) r)) normalizes to (not (and r (and r (and p q))))
(let-values (((result trace) (norm '(not (and (and (and q p) (and r r)) r)))))
  (test '(not (and r (and r (and p q)))) result))

;; (not r) normalizes to (not r)
(let-values (((result trace) (norm '(not r))))
  (test '(not r) result))

;; r normalizes to r
(let-values (((result trace) (norm 'r)))
  (test 'r result))

;; (and (or r (and r (and r r))) r) normalizes to r
(let-values (((result trace) (norm '(and (or r (and r (and r r))) r))))
  (test 'r result))

;; (not (or (not (and r r)) (or r p))) normalizes to (not (or (not r) (or p r)))
(let-values (((result trace) (norm '(not (or (not (and r r)) (or r p))))))
  (test '(not (or (not r) (or p r))) result))

;; (and (and (or (not p) p) (and (and p p) (or p r))) q) normalizes to (and p q)
(let-values (((result trace) (norm '(and (and (or (not p) p) (and (and p p) (or p r))) q))))
  (test '(and p q) result))

;; (or (and q (not (or p q))) (not p)) normalizes to (or (and q (not (or p q))) (not p))
(let-values (((result trace) (norm '(or (and q (not (or p q))) (not p)))))
  (test '(or (and q (not (or p q))) (not p)) result))

;; (and (or p (not p)) (or (and (or q p) (not r)) (or (not q) (and r r)))) normalizes to (and (or p (not p)) (or (and (or p q) (not r)) (or r (not q))))
(let-values (((result trace) (norm '(and (or p (not p)) (or (and (or q p) (not r)) (or (not q) (and r r)))))))
  (test '(and (or p (not p)) (or (and (or p q) (not r)) (or r (not q)))) result))

;; (or (not (or (or r q) q)) r) normalizes to (or r (not (or q (or q r))))
(let-values (((result trace) (norm '(or (not (or (or r q) q)) r))))
  (test '(or r (not (or q (or q r)))) result))

;; (or q (and (and p (or r r)) r)) normalizes to (or q (and r (and p r)))
(let-values (((result trace) (norm '(or q (and (and p (or r r)) r)))))
  (test '(or q (and r (and p r))) result))

;; (not (not r)) normalizes to r
(let-values (((result trace) (norm '(not (not r)))))
  (test 'r result))

;; (not (and (or (and p q) (or p p)) (not (not p)))) normalizes to (not p)
(let-values (((result trace) (norm '(not (and (or (and p q) (or p p)) (not (not p)))))))
  (test '(not p) result))

;; p normalizes to p
(let-values (((result trace) (norm 'p)))
  (test 'p result))

;; (not (not (or (or q r) (or r q)))) normalizes to (or q r)
(let-values (((result trace) (norm '(not (not (or (or q r) (or r q)))))))
  (test '(or q r) result))

;; (and (or r q) (and (or p p) (and (not p) (or q q)))) normalizes to (and (or q r) (and p (and q (not p))))
(let-values (((result trace) (norm '(and (or r q) (and (or p p) (and (not p) (or q q)))))))
  (test '(and (or q r) (and p (and q (not p)))) result))

;; (and (not q) r) normalizes to (and r (not q))
(let-values (((result trace) (norm '(and (not q) r))))
  (test '(and r (not q)) result))

;; (and (and (or p (or q r)) (not (or r p))) (or q p)) normalizes to (and (or p (or q r)) (and (not (or p r)) (or p q)))
(let-values (((result trace) (norm '(and (and (or p (or q r)) (not (or r p))) (or q p)))))
  (test '(and (or p (or q r)) (and (not (or p r)) (or p q))) result))

;; (not (or (or (and r p) (or q r)) r)) normalizes to (not (or r (or (and p r) (or q r))))
(let-values (((result trace) (norm '(not (or (or (and r p) (or q r)) r)))))
  (test '(not (or r (or (and p r) (or q r)))) result))

;; (and (or (and (not q) (or r q)) (not (or q q))) (not (or p (not p)))) normalizes to (and (not q) (not (or p (not p))))
(let-values (((result trace) (norm '(and (or (and (not q) (or r q)) (not (or q q))) (not (or p (not p)))))))
  (test '(and (not q) (not (or p (not p)))) result))

;; (not q) normalizes to (not q)
(let-values (((result trace) (norm '(not q))))
  (test '(not q) result))

;; (or p (not (or p r))) normalizes to (or p (not (or p r)))
(let-values (((result trace) (norm '(or p (not (or p r))))))
  (test '(or p (not (or p r))) result))

;; (or r (or (and (or p q) q) (not (not q)))) normalizes to (or q r)
(let-values (((result trace) (norm '(or r (or (and (or p q) q) (not (not q)))))))
  (test '(or q r) result))

;; (not (and (and (not p) (and r r)) (and (not p) (not q)))) normalizes to (not (and r (and (not p) (and (not p) (not q)))))
(let-values (((result trace) (norm '(not (and (and (not p) (and r r)) (and (not p) (not q)))))))
  (test '(not (and r (and (not p) (and (not p) (not q))))) result))

;; (not r) normalizes to (not r)
(let-values (((result trace) (norm '(not r))))
  (test '(not r) result))

;; (not (not q)) normalizes to q
(let-values (((result trace) (norm '(not (not q)))))
  (test 'q result))

;; (or p r) normalizes to (or p r)
(let-values (((result trace) (norm '(or p r))))
  (test '(or p r) result))

;; (or (not r) (not q)) normalizes to (or (not r) (not q))
(let-values (((result trace) (norm '(or (not r) (not q)))))
  (test '(or (not r) (not q)) result))

;; (not (not q)) normalizes to q
(let-values (((result trace) (norm '(not (not q)))))
  (test 'q result))

;; (and (or (or (and p q) (not p)) (not (and r r))) (or (and (and q q) r) r)) normalizes to (and r (or (and p q) (or (not p) (not r))))
(let-values (((result trace) (norm '(and (or (or (and p q) (not p)) (not (and r r))) (or (and (and q q) r) r)))))
  (test '(and r (or (and p q) (or (not p) (not r)))) result))

;; (or p r) normalizes to (or p r)
(let-values (((result trace) (norm '(or p r))))
  (test '(or p r) result))

;; (not (not (or (and q p) (and r r)))) normalizes to (or r (and p q))
(let-values (((result trace) (norm '(not (not (or (and q p) (and r r)))))))
  (test '(or r (and p q)) result))

;; p normalizes to p
(let-values (((result trace) (norm 'p)))
  (test 'p result))

;; (or (or (or r (not q)) q) (or r (and (not q) (and r p)))) normalizes to (or q (or r (or (not q) (or r (and (not q) (and p r))))))
(let-values (((result trace) (norm '(or (or (or r (not q)) q) (or r (and (not q) (and r p)))))))
  (test '(or q (or r (or (not q) (or r (and (not q) (and p r)))))) result))

;; p normalizes to p
(let-values (((result trace) (norm 'p)))
  (test 'p result))

;; p normalizes to p
(let-values (((result trace) (norm 'p)))
  (test 'p result))

;; (or p (not (not (not r)))) normalizes to (or p (not r))
(let-values (((result trace) (norm '(or p (not (not (not r)))))))
  (test '(or p (not r)) result))

;; (or (not r) r) normalizes to (or r (not r))
(let-values (((result trace) (norm '(or (not r) r))))
  (test '(or r (not r)) result))

;; p normalizes to p
(let-values (((result trace) (norm 'p)))
  (test 'p result))

;; (or (not (not (not p))) (not (not (not r)))) normalizes to (or (not p) (not r))
(let-values (((result trace) (norm '(or (not (not (not p))) (not (not (not r)))))))
  (test '(or (not p) (not r)) result))

;; (and r p) normalizes to (and p r)
(let-values (((result trace) (norm '(and r p))))
  (test '(and p r) result))

;; (and q (or (and (and q p) (not p)) (not (or q q)))) normalizes to (and q (or (and p (and q (not p))) (not q)))
(let-values (((result trace) (norm '(and q (or (and (and q p) (not p)) (not (or q q)))))))
  (test '(and q (or (and p (and q (not p))) (not q))) result))

;; p normalizes to p
(let-values (((result trace) (norm 'p)))
  (test 'p result))

;; (or (and (not q) (and (or q q) (or r q))) (or (and p (not r)) (not p))) normalizes to (or (and q (not q)) (or (and p (not r)) (not p)))
(let-values (((result trace) (norm '(or (and (not q) (and (or q q) (or r q))) (or (and p (not r)) (not p))))))
  (test '(or (and q (not q)) (or (and p (not r)) (not p))) result))

;; (or (or r (and (and r r) q)) q) normalizes to (or q r)
(let-values (((result trace) (norm '(or (or r (and (and r r) q)) q))))
  (test '(or q r) result))

;; (not r) normalizes to (not r)
(let-values (((result trace) (norm '(not r))))
  (test '(not r) result))

;; r normalizes to r
(let-values (((result trace) (norm 'r)))
  (test 'r result))

;; (and (not (and q (not p))) (not (not p))) normalizes to (and p (not (and q (not p))))
(let-values (((result trace) (norm '(and (not (and q (not p))) (not (not p))))))
  (test '(and p (not (and q (not p)))) result))

;; (and (and (and r (or p q)) (or (not r) (and q q))) (or (or (not r) r) r)) normalizes to (and r (and (or p q) (and (or q (not r)) (or r (or r (not r))))))
(let-values (((result trace) (norm '(and (and (and r (or p q)) (or (not r) (and q q))) (or (or (not r) r) r)))))
  (test '(and r (and (or p q) (and (or q (not r)) (or r (or r (not r)))))) result))

;; (and p q) normalizes to (and p q)
(let-values (((result trace) (norm '(and p q))))
  (test '(and p q) result))

;; (or q (or (not p) r)) normalizes to (or q (or r (not p)))
(let-values (((result trace) (norm '(or q (or (not p) r)))))
  (test '(or q (or r (not p))) result))

;; (or (or (not (or p q)) (or (and r q) (not p))) (and (not (or q q)) (or (and r r) q))) normalizes to (or (not (or p q)) (or (and q r) (or (not p) (and (not q) (or q r)))))
(let-values (((result trace) (norm '(or (or (not (or p q)) (or (and r q) (not p))) (and (not (or q q)) (or (and r r) q))))))
  (test '(or (not (or p q)) (or (and q r) (or (not p) (and (not q) (or q r))))) result))

;; (not (not p)) normalizes to p
(let-values (((result trace) (norm '(not (not p)))))
  (test 'p result))

;; (and (not (or (and p q) r)) (and r (not r))) normalizes to (and (not (or r (and p q))) (and r (not r)))
(let-values (((result trace) (norm '(and (not (or (and p q) r)) (and r (not r))))))
  (test '(and (not (or r (and p q))) (and r (not r))) result))

;; (or q (or (and (and p r) (or p r)) (not (not p)))) normalizes to (or p q)
(let-values (((result trace) (norm '(or q (or (and (and p r) (or p r)) (not (not p)))))))
  (test '(or p q) result))

;; p normalizes to p
(let-values (((result trace) (norm 'p)))
  (test 'p result))

;; (not p) normalizes to (not p)
(let-values (((result trace) (norm '(not p))))
  (test '(not p) result))

;; r normalizes to r
(let-values (((result trace) (norm 'r)))
  (test 'r result))

;; q normalizes to q
(let-values (((result trace) (norm 'q)))
  (test 'q result))

;; (or (and (or (or q r) (not q)) (not (or p p))) (and (and (not q) q) (not r))) normalizes to (or (and (or q (or r (not q))) (not p)) (and q (and (not q) (not r))))
(let-values (((result trace) (norm '(or (and (or (or q r) (not q)) (not (or p p))) (and (and (not q) q) (not r))))))
  (test '(or (and (or q (or r (not q))) (not p)) (and q (and (not q) (not r)))) result))

;; (or (and (and (not p) q) (and q q)) (and (and (and q r) r) (and (or r p) (not p)))) normalizes to (or (and q (and q (not p))) (and r (and q (and r (and (or p r) (not p))))))
(let-values (((result trace) (norm '(or (and (and (not p) q) (and q q)) (and (and (and q r) r) (and (or r p) (not p)))))))
  (test '(or (and q (and q (not p))) (and r (and q (and r (and (or p r) (not p)))))) result))

;; (not (or (or (or q p) (and q r)) p)) normalizes to (not (or p (or p q)))
(let-values (((result trace) (norm '(not (or (or (or q p) (and q r)) p)))))
  (test '(not (or p (or p q))) result))

;; (and (or (and (or q p) (and q p)) (or (or p r) q)) (or q r)) normalizes to (and (or (and (or p q) (and p q)) (or q (or p r))) (or q r))
(let-values (((result trace) (norm '(and (or (and (or q p) (and q p)) (or (or p r) q)) (or q r)))))
  (test '(and (or (and (or p q) (and p q)) (or q (or p r))) (or q r)) result))

;; (or r q) normalizes to (or q r)
(let-values (((result trace) (norm '(or r q))))
  (test '(or q r) result))

;; (or (and (or r (not q)) r) (not (or (and p r) (and q r)))) normalizes to (or r (not (or (and p r) (and q r))))
(let-values (((result trace) (norm '(or (and (or r (not q)) r) (not (or (and p r) (and q r)))))))
  (test '(or r (not (or (and p r) (and q r)))) result))

;; (and p r) normalizes to (and p r)
(let-values (((result trace) (norm '(and p r))))
  (test '(and p r) result))

;; (and p q) normalizes to (and p q)
(let-values (((result trace) (norm '(and p q))))
  (test '(and p q) result))

;; (and r (or (and (and r r) p) (or (or q q) (or r q)))) normalizes to (and r (or (and p r) (or q (or q r))))
(let-values (((result trace) (norm '(and r (or (and (and r r) p) (or (or q q) (or r q)))))))
  (test '(and r (or (and p r) (or q (or q r)))) result))

;; (not (or (or (and r p) q) (and (not p) q))) normalizes to (not (or q (or (and p r) (and q (not p)))))
(let-values (((result trace) (norm '(not (or (or (and r p) q) (and (not p) q))))))
  (test '(not (or q (or (and p r) (and q (not p))))) result))

;; q normalizes to q
(let-values (((result trace) (norm 'q)))
  (test 'q result))

;; (or r (and (and (not q) (and r p)) (not (not r)))) normalizes to r
(let-values (((result trace) (norm '(or r (and (and (not q) (and r p)) (not (not r)))))))
  (test 'r result))

;; (or (and (and p r) p) (or q (not (and p r)))) normalizes to (or (and p (and p r)) (or q (not (and p r))))
(let-values (((result trace) (norm '(or (and (and p r) p) (or q (not (and p r)))))))
  (test '(or (and p (and p r)) (or q (not (and p r)))) result))

;; (and (and q (not q)) (and (or r (not r)) (not q))) normalizes to (and q (and (not q) (and (or r (not r)) (not q))))
(let-values (((result trace) (norm '(and (and q (not q)) (and (or r (not r)) (not q))))))
  (test '(and q (and (not q) (and (or r (not r)) (not q)))) result))

;; q normalizes to q
(let-values (((result trace) (norm 'q)))
  (test 'q result))

;; (not (or r (or (or p q) p))) normalizes to (not (or r (or p (or p q))))
(let-values (((result trace) (norm '(not (or r (or (or p q) p))))))
  (test '(not (or r (or p (or p q)))) result))

;; (or p (and r (or r (or q r)))) normalizes to (or p r)
(let-values (((result trace) (norm '(or p (and r (or r (or q r)))))))
  (test '(or p r) result))

;; p normalizes to p
(let-values (((result trace) (norm 'p)))
  (test 'p result))

;; q normalizes to q
(let-values (((result trace) (norm 'q)))
  (test 'q result))

;; (and (and (not (not p)) p) p) normalizes to p
(let-values (((result trace) (norm '(and (and (not (not p)) p) p))))
  (test 'p result))

;; q normalizes to q
(let-values (((result trace) (norm 'q)))
  (test 'q result))

;; (or (not (and (not r) r)) (not (or p (or r p)))) normalizes to (or (not (and r (not r))) (not (or p (or p r))))
(let-values (((result trace) (norm '(or (not (and (not r) r)) (not (or p (or r p)))))))
  (test '(or (not (and r (not r))) (not (or p (or p r)))) result))

;; q normalizes to q
(let-values (((result trace) (norm 'q)))
  (test 'q result))

;; (and p q) normalizes to (and p q)
(let-values (((result trace) (norm '(and p q))))
  (test '(and p q) result))

;; (and (not (or (and q r) (and r q))) (not (or (and r p) (not q)))) normalizes to (and (not (and q r)) (not (or (and p r) (not q))))
(let-values (((result trace) (norm '(and (not (or (and q r) (and r q))) (not (or (and r p) (not q)))))))
  (test '(and (not (and q r)) (not (or (and p r) (not q)))) result))

;; (and (not (not (or q q))) (and (or (or q q) r) (or (not p) q))) normalizes to (and q (and (or q r) (or q (not p))))
(let-values (((result trace) (norm '(and (not (not (or q q))) (and (or (or q q) r) (or (not p) q))))))
  (test '(and q (and (or q r) (or q (not p)))) result))

;; (and (not (not r)) q) normalizes to (and q r)
(let-values (((result trace) (norm '(and (not (not r)) q))))
  (test '(and q r) result))

;; (not (and (not (not q)) (not (or q r)))) normalizes to (not (and q (not (or q r))))
(let-values (((result trace) (norm '(not (and (not (not q)) (not (or q r)))))))
  (test '(not (and q (not (or q r)))) result))

;; (not (or (not (or r r)) p)) normalizes to (not (or p (not r)))
(let-values (((result trace) (norm '(not (or (not (or r r)) p)))))
  (test '(not (or p (not r))) result))

;; p normalizes to p
(let-values (((result trace) (norm 'p)))
  (test 'p result))

;; r normalizes to r
(let-values (((result trace) (norm 'r)))
  (test 'r result))

;; (and r p) normalizes to (and p r)
(let-values (((result trace) (norm '(and r p))))
  (test '(and p r) result))

;; (not r) normalizes to (not r)
(let-values (((result trace) (norm '(not r))))
  (test '(not r) result))

;; (and (or (not (and r p)) (and (not r) p)) (not q)) normalizes to (and (or (not (and p r)) (and p (not r))) (not q))
(let-values (((result trace) (norm '(and (or (not (and r p)) (and (not r) p)) (not q)))))
  (test '(and (or (not (and p r)) (and p (not r))) (not q)) result))

;; q normalizes to q
(let-values (((result trace) (norm 'q)))
  (test 'q result))

;; r normalizes to r
(let-values (((result trace) (norm 'r)))
  (test 'r result))


(test-end)
(test-exit)
