;;; sage-structures-graph-test.scm — Generated by Sage oracle
;;; Oracle: SageMath version 10.8, Release Date: 2025-12-18
;;; Oracle source: Sage-builtin
;;; Date: 2026-06-07
;;; Seed: 42
;;; DO NOT EDIT — regenerate with:
;;;   make sage-snapshot

(import (scheme base)
        (chibi test)
        (wile algebra))

(test-begin "sage-structures-graph")

(test 3 (graph-spanning-tree-count (complete-graph 3)))
(test 16 (graph-spanning-tree-count (complete-graph 4)))
(test 4 (graph-spanning-tree-count (cycle-graph 4)))
(test 5 (graph-spanning-tree-count (cycle-graph 5)))
(test 1 (graph-spanning-tree-count (path-graph 4)))
(test 12 (graph-spanning-tree-count (complete-bipartite-graph 2 3)))
(test 2000 (graph-spanning-tree-count (petersen-graph)))
(test '(0 2 -3 1) (graph-chromatic-polynomial (complete-graph 3)))
(test '(0 -6 11 -6 1) (graph-chromatic-polynomial (complete-graph 4)))
(test '(0 -3 6 -4 1) (graph-chromatic-polynomial (cycle-graph 4)))
(test '(0 4 -10 10 -5 1) (graph-chromatic-polynomial (cycle-graph 5)))
(test '(0 -1 3 -3 1) (graph-chromatic-polynomial (path-graph 4)))
(test '(0 7 -17 15 -6 1) (graph-chromatic-polynomial (complete-bipartite-graph 2 3)))

(test-end)
(test-exit)
