;;; sage-rewriting-rational-field-test.scm — Generated by Sage oracle
;;; Oracle: SageMath version 10.8, Release Date: 2025-12-18
;;; Oracle source: Sage-builtin
;;; Date: 2026-06-07
;;; Seed: 42
;;; DO NOT EDIT — regenerate with:
;;;   make sage-snapshot

(import (scheme base)
        (chibi test)
        (wile algebra)
        (wile algebra symbolic)
        (wile algebra rewrite))

(test-begin "sage-rewriting-rational-field")

;; Evaluate a normalized term to its rational value.
(define (term-value t)
  (cond
    ((number? t) t)
    ((not (pair? t)) (error "term-value: unexpected atom" t))
    ((eq? (car t) '+)
     (+ (term-value (cadr t)) (term-value (caddr t))))
    ((eq? (car t) '*)
     (* (term-value (cadr t)) (term-value (caddr t))))
    ((eq? (car t) 'neg)
     (- (term-value (cadr t))))
    ((eq? (car t) 'recip)
     (/ 1 (term-value (cadr t))))
    (else (error "term-value: unknown operator" (car t)))))

(define proto
  (sexp-term-protocol
    (lambda (a b)
      (cond
        ((and (number? a) (number? b)) (< a b))
        ((number? a) #t)
        ((number? b) #f)
        (else #f)))))

(define norm
  (make-recursive-normalizer
    (field->theory (rational-field) '+ '* 'neg 'recip)
    proto))

;; Original: (recip 2) = 1/2
(let-values (((result trace) (norm '(recip 2))))
  (test "1/2" (number->string (term-value result))))

;; Original: (+ (neg (recip (+ 2 -1/2))) (* -1 (recip (neg 1/3)))) = 7/3
(let-values (((result trace) (norm '(+ (neg (recip (+ 2 -1/2))) (* -1 (recip (neg 1/3)))))))
  (test "7/3" (number->string (term-value result))))

;; Original: (neg (* (* (neg 1/2) (* -2 -1)) (neg -1/2))) = 1/2
(let-values (((result trace) (norm '(neg (* (* (neg 1/2) (* -2 -1)) (neg -1/2))))))
  (test "1/2" (number->string (term-value result))))

;; Original: (neg (+ (+ -1/2 (recip 3)) (+ (recip 1) (* -2 1/2)))) = 1/6
(let-values (((result trace) (norm '(neg (+ (+ -1/2 (recip 3)) (+ (recip 1) (* -2 1/2)))))))
  (test "1/6" (number->string (term-value result))))

;; Original: -1 = -1
(let-values (((result trace) (norm '-1)))
  (test "-1" (number->string (term-value result))))

;; Original: -1/2 = -1/2
(let-values (((result trace) (norm '-1/2)))
  (test "-1/2" (number->string (term-value result))))

;; Original: 1/2 = 1/2
(let-values (((result trace) (norm '1/2)))
  (test "1/2" (number->string (term-value result))))

;; Original: (+ -2 (neg (+ (+ -2 -2) 3))) = -1
(let-values (((result trace) (norm '(+ -2 (neg (+ (+ -2 -2) 3))))))
  (test "-1" (number->string (term-value result))))

;; Original: -1/2 = -1/2
(let-values (((result trace) (norm '-1/2)))
  (test "-1/2" (number->string (term-value result))))

;; Original: (* (neg (+ 3 1)) (recip (* 3 (+ -1 -1/2)))) = 8/9
(let-values (((result trace) (norm '(* (neg (+ 3 1)) (recip (* 3 (+ -1 -1/2)))))))
  (test "8/9" (number->string (term-value result))))

;; Original: 3 = 3
(let-values (((result trace) (norm '3)))
  (test "3" (number->string (term-value result))))

;; Original: (+ (+ (* (+ 2 -1/2) (+ -1/2 1)) (+ (+ -2 3) -2)) 1/2) = 1/4
(let-values (((result trace) (norm '(+ (+ (* (+ 2 -1/2) (+ -1/2 1)) (+ (+ -2 3) -2)) 1/2))))
  (test "1/4" (number->string (term-value result))))

;; Original: (neg (+ -2 1)) = 1
(let-values (((result trace) (norm '(neg (+ -2 1)))))
  (test "1" (number->string (term-value result))))

;; Original: (+ (+ -1/2 1/2) (+ (+ (+ -2 2) (+ 3 1)) (neg (+ 2 -1)))) = 3
(let-values (((result trace) (norm '(+ (+ -1/2 1/2) (+ (+ (+ -2 2) (+ 3 1)) (neg (+ 2 -1)))))))
  (test "3" (number->string (term-value result))))

;; Original: -1 = -1
(let-values (((result trace) (norm '-1)))
  (test "-1" (number->string (term-value result))))

;; Original: 1/3 = 1/3
(let-values (((result trace) (norm '1/3)))
  (test "1/3" (number->string (term-value result))))

;; Original: (neg (recip (+ (* -1/2 1/3) (neg 1/3)))) = 2
(let-values (((result trace) (norm '(neg (recip (+ (* -1/2 1/3) (neg 1/3)))))))
  (test "2" (number->string (term-value result))))

;; Original: (recip -1) = -1
(let-values (((result trace) (norm '(recip -1))))
  (test "-1" (number->string (term-value result))))

;; Original: -1 = -1
(let-values (((result trace) (norm '-1)))
  (test "-1" (number->string (term-value result))))

;; Original: 1/3 = 1/3
(let-values (((result trace) (norm '1/3)))
  (test "1/3" (number->string (term-value result))))

;; Original: (+ (recip 3) 2) = 7/3
(let-values (((result trace) (norm '(+ (recip 3) 2))))
  (test "7/3" (number->string (term-value result))))

;; Original: 3 = 3
(let-values (((result trace) (norm '3)))
  (test "3" (number->string (term-value result))))

;; Original: (+ (+ (* (recip -1/2) (* -1/2 -1)) (neg (neg 2))) (* (recip (+ 1 2)) (neg (+ 1/3 3)))) = -1/9
(let-values (((result trace) (norm '(+ (+ (* (recip -1/2) (* -1/2 -1)) (neg (neg 2))) (* (recip (+ 1 2)) (neg (+ 1/3 3)))))))
  (test "-1/9" (number->string (term-value result))))

;; Original: (neg (neg (* (+ 1/2 -1) (neg -1/2)))) = -1/4
(let-values (((result trace) (norm '(neg (neg (* (+ 1/2 -1) (neg -1/2)))))))
  (test "-1/4" (number->string (term-value result))))

;; Original: (recip 1/2) = 2
(let-values (((result trace) (norm '(recip 1/2))))
  (test "2" (number->string (term-value result))))

;; Original: (neg (* (+ (recip -1/2) 1/2) (+ 1 (+ -1 3)))) = 9/2
(let-values (((result trace) (norm '(neg (* (+ (recip -1/2) 1/2) (+ 1 (+ -1 3)))))))
  (test "9/2" (number->string (term-value result))))

;; Original: (neg -2) = 2
(let-values (((result trace) (norm '(neg -2))))
  (test "2" (number->string (term-value result))))

;; Original: -1/2 = -1/2
(let-values (((result trace) (norm '-1/2)))
  (test "-1/2" (number->string (term-value result))))

;; Original: (recip (neg 1/3)) = -3
(let-values (((result trace) (norm '(recip (neg 1/3)))))
  (test "-3" (number->string (term-value result))))

;; Original: (+ (+ (recip (+ 3 -1)) (* -1/2 -1)) 2) = 3
(let-values (((result trace) (norm '(+ (+ (recip (+ 3 -1)) (* -1/2 -1)) 2))))
  (test "3" (number->string (term-value result))))

;; Original: 2 = 2
(let-values (((result trace) (norm '2)))
  (test "2" (number->string (term-value result))))

;; Original: (* 2 3) = 6
(let-values (((result trace) (norm '(* 2 3))))
  (test "6" (number->string (term-value result))))

;; Original: (* (neg (neg 3)) 3) = 9
(let-values (((result trace) (norm '(* (neg (neg 3)) 3))))
  (test "9" (number->string (term-value result))))

;; Original: (+ -1 (* (+ (neg -2) (recip 2)) 2)) = 4
(let-values (((result trace) (norm '(+ -1 (* (+ (neg -2) (recip 2)) 2)))))
  (test "4" (number->string (term-value result))))

;; Original: (+ (recip 1/2) (+ (recip (+ 2 1)) (+ (+ 3 1/2) -1))) = 29/6
(let-values (((result trace) (norm '(+ (recip 1/2) (+ (recip (+ 2 1)) (+ (+ 3 1/2) -1))))))
  (test "29/6" (number->string (term-value result))))

;; Original: (* (+ (neg -1/2) (neg (* 1 2))) -2) = 3
(let-values (((result trace) (norm '(* (+ (neg -1/2) (neg (* 1 2))) -2))))
  (test "3" (number->string (term-value result))))

;; Original: -2 = -2
(let-values (((result trace) (norm '-2)))
  (test "-2" (number->string (term-value result))))

;; Original: (recip (+ (* (+ 2 -1) 1/3) -2)) = -3/5
(let-values (((result trace) (norm '(recip (+ (* (+ 2 -1) 1/3) -2)))))
  (test "-3/5" (number->string (term-value result))))

;; Original: (recip (+ (neg (neg 1/3)) (neg (+ 3 2)))) = -3/14
(let-values (((result trace) (norm '(recip (+ (neg (neg 1/3)) (neg (+ 3 2)))))))
  (test "-3/14" (number->string (term-value result))))

;; Original: (+ (recip (+ (neg 2) (recip 1))) (+ (recip (* 1/3 3)) (+ 1/2 -1/2))) = 0
(let-values (((result trace) (norm '(+ (recip (+ (neg 2) (recip 1))) (+ (recip (* 1/3 3)) (+ 1/2 -1/2))))))
  (test "0" (number->string (term-value result))))

;; Original: -2 = -2
(let-values (((result trace) (norm '-2)))
  (test "-2" (number->string (term-value result))))

;; Original: (+ 1 -2) = -1
(let-values (((result trace) (norm '(+ 1 -2))))
  (test "-1" (number->string (term-value result))))

;; Original: (neg -1/2) = 1/2
(let-values (((result trace) (norm '(neg -1/2))))
  (test "1/2" (number->string (term-value result))))

;; Original: (* (recip 3) (recip (* (+ 3 2) 2))) = 1/30
(let-values (((result trace) (norm '(* (recip 3) (recip (* (+ 3 2) 2))))))
  (test "1/30" (number->string (term-value result))))

;; Original: (* 1 (neg 2)) = -2
(let-values (((result trace) (norm '(* 1 (neg 2)))))
  (test "-2" (number->string (term-value result))))

;; Original: (neg (recip (neg (neg 1/3)))) = -3
(let-values (((result trace) (norm '(neg (recip (neg (neg 1/3)))))))
  (test "-3" (number->string (term-value result))))

;; Original: 1 = 1
(let-values (((result trace) (norm '1)))
  (test "1" (number->string (term-value result))))

;; Original: (recip (recip 3)) = 3
(let-values (((result trace) (norm '(recip (recip 3)))))
  (test "3" (number->string (term-value result))))

;; Original: 1/3 = 1/3
(let-values (((result trace) (norm '1/3)))
  (test "1/3" (number->string (term-value result))))

;; Original: -2 = -2
(let-values (((result trace) (norm '-2)))
  (test "-2" (number->string (term-value result))))

;; Original: 2 = 2
(let-values (((result trace) (norm '2)))
  (test "2" (number->string (term-value result))))

;; Original: (neg (neg (* (neg 2) (* 1 3)))) = -6
(let-values (((result trace) (norm '(neg (neg (* (neg 2) (* 1 3)))))))
  (test "-6" (number->string (term-value result))))

;; Original: 2 = 2
(let-values (((result trace) (norm '2)))
  (test "2" (number->string (term-value result))))

;; Original: (recip -1) = -1
(let-values (((result trace) (norm '(recip -1))))
  (test "-1" (number->string (term-value result))))

;; Original: (+ (* (* -1 (* -1 1/2)) (* (recip -2) (+ -1/2 -2))) (neg (* -2 (+ 3 1/2)))) = 61/8
(let-values (((result trace) (norm '(+ (* (* -1 (* -1 1/2)) (* (recip -2) (+ -1/2 -2))) (neg (* -2 (+ 3 1/2)))))))
  (test "61/8" (number->string (term-value result))))

;; Original: 2 = 2
(let-values (((result trace) (norm '2)))
  (test "2" (number->string (term-value result))))

;; Original: -1 = -1
(let-values (((result trace) (norm '-1)))
  (test "-1" (number->string (term-value result))))

;; Original: (+ -2 (* (* (recip -1) (+ 1 1)) 1/2)) = -3
(let-values (((result trace) (norm '(+ -2 (* (* (recip -1) (+ 1 1)) 1/2)))))
  (test "-3" (number->string (term-value result))))

;; Original: (recip 1/2) = 2
(let-values (((result trace) (norm '(recip 1/2))))
  (test "2" (number->string (term-value result))))

;; Original: (neg (+ (neg (neg 1)) (* 3 (neg -2)))) = -7
(let-values (((result trace) (norm '(neg (+ (neg (neg 1)) (* 3 (neg -2)))))))
  (test "-7" (number->string (term-value result))))

;; Original: -2 = -2
(let-values (((result trace) (norm '-2)))
  (test "-2" (number->string (term-value result))))

;; Original: -1/2 = -1/2
(let-values (((result trace) (norm '-1/2)))
  (test "-1/2" (number->string (term-value result))))

;; Original: (recip (+ -1/2 3)) = 2/5
(let-values (((result trace) (norm '(recip (+ -1/2 3)))))
  (test "2/5" (number->string (term-value result))))

;; Original: (recip -1) = -1
(let-values (((result trace) (norm '(recip -1))))
  (test "-1" (number->string (term-value result))))

;; Original: (neg -1) = 1
(let-values (((result trace) (norm '(neg -1))))
  (test "1" (number->string (term-value result))))

;; Original: (recip (recip (recip (neg 2)))) = -1/2
(let-values (((result trace) (norm '(recip (recip (recip (neg 2)))))))
  (test "-1/2" (number->string (term-value result))))

;; Original: (recip 1) = 1
(let-values (((result trace) (norm '(recip 1))))
  (test "1" (number->string (term-value result))))

;; Original: (* (neg (+ (+ 1 2) -1)) (recip (recip 1/3))) = -2/3
(let-values (((result trace) (norm '(* (neg (+ (+ 1 2) -1)) (recip (recip 1/3))))))
  (test "-2/3" (number->string (term-value result))))

;; Original: (* (* 1/3 1/2) (+ (recip (neg 1/2)) (recip 3))) = -5/18
(let-values (((result trace) (norm '(* (* 1/3 1/2) (+ (recip (neg 1/2)) (recip 3))))))
  (test "-5/18" (number->string (term-value result))))

;; Original: (neg 1) = -1
(let-values (((result trace) (norm '(neg 1))))
  (test "-1" (number->string (term-value result))))

;; Original: -2 = -2
(let-values (((result trace) (norm '-2)))
  (test "-2" (number->string (term-value result))))

;; Original: (neg (* (* (+ -2 2) 1/2) (recip (* 2 1/3)))) = 0
(let-values (((result trace) (norm '(neg (* (* (+ -2 2) 1/2) (recip (* 2 1/3)))))))
  (test "0" (number->string (term-value result))))

;; Original: (neg -2) = 2
(let-values (((result trace) (norm '(neg -2))))
  (test "2" (number->string (term-value result))))

;; Original: (recip (+ (neg (* 1 -1)) 3)) = 1/4
(let-values (((result trace) (norm '(recip (+ (neg (* 1 -1)) 3)))))
  (test "1/4" (number->string (term-value result))))

;; Original: (+ (neg -1/2) (* (* (neg -1) (recip 2)) (neg (* -2 1/3)))) = 5/6
(let-values (((result trace) (norm '(+ (neg -1/2) (* (* (neg -1) (recip 2)) (neg (* -2 1/3)))))))
  (test "5/6" (number->string (term-value result))))

;; Original: (neg (neg (recip (recip 3)))) = 3
(let-values (((result trace) (norm '(neg (neg (recip (recip 3)))))))
  (test "3" (number->string (term-value result))))

;; Original: (neg (* 3 (+ -1/2 (neg 1)))) = 9/2
(let-values (((result trace) (norm '(neg (* 3 (+ -1/2 (neg 1)))))))
  (test "9/2" (number->string (term-value result))))

;; Original: (* (recip (neg (* 1 -1/2))) (recip (recip -2))) = -4
(let-values (((result trace) (norm '(* (recip (neg (* 1 -1/2))) (recip (recip -2))))))
  (test "-4" (number->string (term-value result))))

;; Original: (+ (* 3 (+ -1 (neg 1))) -2) = -8
(let-values (((result trace) (norm '(+ (* 3 (+ -1 (neg 1))) -2))))
  (test "-8" (number->string (term-value result))))

;; Original: 1/3 = 1/3
(let-values (((result trace) (norm '1/3)))
  (test "1/3" (number->string (term-value result))))

;; Original: (+ 1/2 (recip (* (neg 1) (* -2 2)))) = 3/4
(let-values (((result trace) (norm '(+ 1/2 (recip (* (neg 1) (* -2 2)))))))
  (test "3/4" (number->string (term-value result))))

;; Original: 1/3 = 1/3
(let-values (((result trace) (norm '1/3)))
  (test "1/3" (number->string (term-value result))))

;; Original: (* (* (* (neg 1/2) -1/2) (recip -2)) (* (recip -1) 2)) = 1/4
(let-values (((result trace) (norm '(* (* (* (neg 1/2) -1/2) (recip -2)) (* (recip -1) 2)))))
  (test "1/4" (number->string (term-value result))))

;; Original: (* 1 (neg (neg 3))) = 3
(let-values (((result trace) (norm '(* 1 (neg (neg 3))))))
  (test "3" (number->string (term-value result))))

;; Original: (* -2 (recip (recip 2))) = -4
(let-values (((result trace) (norm '(* -2 (recip (recip 2))))))
  (test "-4" (number->string (term-value result))))

;; Original: (recip (+ (recip 1/2) (neg (neg -1/2)))) = 2/3
(let-values (((result trace) (norm '(recip (+ (recip 1/2) (neg (neg -1/2)))))))
  (test "2/3" (number->string (term-value result))))

;; Original: (* 1/2 (neg (+ -2 1/2))) = 3/4
(let-values (((result trace) (norm '(* 1/2 (neg (+ -2 1/2))))))
  (test "3/4" (number->string (term-value result))))

;; Original: (+ (* (+ 1/2 -1) (+ (+ -2 1) -1)) 1) = 2
(let-values (((result trace) (norm '(+ (* (+ 1/2 -1) (+ (+ -2 1) -1)) 1))))
  (test "2" (number->string (term-value result))))

;; Original: -1 = -1
(let-values (((result trace) (norm '-1)))
  (test "-1" (number->string (term-value result))))

;; Original: (recip (neg -2)) = 1/2
(let-values (((result trace) (norm '(recip (neg -2)))))
  (test "1/2" (number->string (term-value result))))

;; Original: (* (+ -2 (recip (+ -2 1))) (+ -1/2 (neg (recip -1)))) = -3/2
(let-values (((result trace) (norm '(* (+ -2 (recip (+ -2 1))) (+ -1/2 (neg (recip -1)))))))
  (test "-3/2" (number->string (term-value result))))

;; Original: (recip (+ 1 1/3)) = 3/4
(let-values (((result trace) (norm '(recip (+ 1 1/3)))))
  (test "3/4" (number->string (term-value result))))

;; Original: (+ (* (+ (+ 1/2 -1/2) (recip -1)) 1/3) (recip (* (* -1/2 -1) (+ 1/2 1)))) = 1
(let-values (((result trace) (norm '(+ (* (+ (+ 1/2 -1/2) (recip -1)) 1/3) (recip (* (* -1/2 -1) (+ 1/2 1)))))))
  (test "1" (number->string (term-value result))))

;; Original: (* (neg (+ (recip 1/2) (* 1/2 -2))) (* (* -1/2 (* -1 1/3)) (recip (+ -1 1/2)))) = 1/3
(let-values (((result trace) (norm '(* (neg (+ (recip 1/2) (* 1/2 -2))) (* (* -1/2 (* -1 1/3)) (recip (+ -1 1/2)))))))
  (test "1/3" (number->string (term-value result))))

;; Original: (neg (recip (* -2 1/2))) = 1
(let-values (((result trace) (norm '(neg (recip (* -2 1/2))))))
  (test "1" (number->string (term-value result))))

;; Original: 1/3 = 1/3
(let-values (((result trace) (norm '1/3)))
  (test "1/3" (number->string (term-value result))))

;; Original: -1/2 = -1/2
(let-values (((result trace) (norm '-1/2)))
  (test "-1/2" (number->string (term-value result))))

;; Original: (* -1 (+ 2 (neg (recip -1)))) = -3
(let-values (((result trace) (norm '(* -1 (+ 2 (neg (recip -1)))))))
  (test "-3" (number->string (term-value result))))

;; Original: (+ (recip (+ (recip 2) (+ 1/3 -2))) (* (recip (+ -1 3)) 2)) = 1/7
(let-values (((result trace) (norm '(+ (recip (+ (recip 2) (+ 1/3 -2))) (* (recip (+ -1 3)) 2)))))
  (test "1/7" (number->string (term-value result))))

;; Original: (recip (recip 1)) = 1
(let-values (((result trace) (norm '(recip (recip 1)))))
  (test "1" (number->string (term-value result))))


(test-end)
(test-exit)
