;;; sage-structures-boolean-semiring-test.scm — Generated by Sage oracle
;;; Oracle: SageMath version 10.8, Release Date: 2025-12-18
;;; Date: 2026-04-12
;;; Seed: 42
;;; DO NOT EDIT — regenerate with:
;;;   sage tools/sage/verify_algebra.sage --snapshot

(import (scheme base)
        (chibi test)
        (wile algebra))

(test-begin "sage-structures-boolean-semiring")

(let ((S (boolean-semiring)))
  (test #f (semiring-plus S #f #f))
  (test #f (semiring-times S #f #f))
  (test #t (semiring-plus S #f #t))
  (test #f (semiring-times S #f #t))
  (test #t (semiring-plus S #t #f))
  (test #f (semiring-times S #t #f))
  (test #t (semiring-plus S #t #t))
  (test #t (semiring-times S #t #t))
)

(test-end)
(test-exit)
