;;; sage-rewriting-boolean-algebra-test.scm — Generated by Sage oracle
;;; Oracle: SageMath version 10.8, Release Date: 2025-12-18
;;; Oracle source: Sage-builtin
;;; Date: 2026-06-09
;;; Seed: 42
;;; DO NOT EDIT — regenerate with:
;;;   make sage-snapshot

(import (scheme base)
        (chibi test)
        (wile algebra)
        (wile algebra symbolic)
        (wile algebra rewrite))

(test-begin "sage-rewriting-boolean-algebra")

;; r normalizes to r
(let-values (((result trace) (symbolic-boolean-normalize 'r)))
  (test 'r result))

;; (not p) normalizes to (not p)
(let-values (((result trace) (symbolic-boolean-normalize '(not p))))
  (test '(not p) result))

;; p normalizes to p
(let-values (((result trace) (symbolic-boolean-normalize 'p)))
  (test 'p result))

;; (and (or q (or (not q) (not q))) (not p)) normalizes to (not p)
(let-values (((result trace) (symbolic-boolean-normalize '(and (or q (or (not q) (not q))) (not p)))))
  (test '(not p) result))

;; (or r (or (not (and q q)) p)) normalizes to (or (not q) (or p r))
(let-values (((result trace) (symbolic-boolean-normalize '(or r (or (not (and q q)) p)))))
  (test '(or (not q) (or p r)) result))

;; (and (and (not (and q q)) q) (not (not (not r)))) normalizes to #f
(let-values (((result trace) (symbolic-boolean-normalize '(and (and (not (and q q)) q) (not (not (not r)))))))
  (test '#f result))

;; (not (and (and (and q p) (and r r)) r)) normalizes to (or (not p) (or (not q) (not r)))
(let-values (((result trace) (symbolic-boolean-normalize '(not (and (and (and q p) (and r r)) r)))))
  (test '(or (not p) (or (not q) (not r))) result))

;; (not r) normalizes to (not r)
(let-values (((result trace) (symbolic-boolean-normalize '(not r))))
  (test '(not r) result))

;; r normalizes to r
(let-values (((result trace) (symbolic-boolean-normalize 'r)))
  (test 'r result))

;; (and (or r (and r (and r r))) r) normalizes to r
(let-values (((result trace) (symbolic-boolean-normalize '(and (or r (and r (and r r))) r))))
  (test 'r result))

;; (not (or (not (and r r)) (or r p))) normalizes to #f
(let-values (((result trace) (symbolic-boolean-normalize '(not (or (not (and r r)) (or r p))))))
  (test '#f result))

;; (and (and (or (not p) p) (and (and p p) (or p r))) q) normalizes to (and (or p r) (and p q))
(let-values (((result trace) (symbolic-boolean-normalize '(and (and (or (not p) p) (and (and p p) (or p r))) q))))
  (test '(and (or p r) (and p q)) result))

;; (or (and q (not (or p q))) (not p)) normalizes to (not p)
(let-values (((result trace) (symbolic-boolean-normalize '(or (and q (not (or p q))) (not p)))))
  (test '(not p) result))

;; (and (or p (not p)) (or (and (or q p) (not r)) (or (not q) (and r r)))) normalizes to (or (and (not r) (or p q)) (or (not q) r))
(let-values (((result trace) (symbolic-boolean-normalize '(and (or p (not p)) (or (and (or q p) (not r)) (or (not q) (and r r)))))))
  (test '(or (and (not r) (or p q)) (or (not q) r)) result))

;; (or (not (or (or r q) q)) r) normalizes to (or (and (not q) (not r)) r)
(let-values (((result trace) (symbolic-boolean-normalize '(or (not (or (or r q) q)) r))))
  (test '(or (and (not q) (not r)) r) result))

;; (or q (and (and p (or r r)) r)) normalizes to (or (and p r) q)
(let-values (((result trace) (symbolic-boolean-normalize '(or q (and (and p (or r r)) r)))))
  (test '(or (and p r) q) result))

;; (not (not r)) normalizes to r
(let-values (((result trace) (symbolic-boolean-normalize '(not (not r)))))
  (test 'r result))

;; (not (and (or (and p q) (or p p)) (not (not p)))) normalizes to (not p)
(let-values (((result trace) (symbolic-boolean-normalize '(not (and (or (and p q) (or p p)) (not (not p)))))))
  (test '(not p) result))

;; p normalizes to p
(let-values (((result trace) (symbolic-boolean-normalize 'p)))
  (test 'p result))

;; (not (not (or (or q r) (or r q)))) normalizes to (or q r)
(let-values (((result trace) (symbolic-boolean-normalize '(not (not (or (or q r) (or r q)))))))
  (test '(or q r) result))

;; (and (or r q) (and (or p p) (and (not p) (or q q)))) normalizes to #f
(let-values (((result trace) (symbolic-boolean-normalize '(and (or r q) (and (or p p) (and (not p) (or q q)))))))
  (test '#f result))

;; (and (not q) r) normalizes to (and (not q) r)
(let-values (((result trace) (symbolic-boolean-normalize '(and (not q) r))))
  (test '(and (not q) r) result))

;; (and (and (or p (or q r)) (not (or r p))) (or q p)) normalizes to (and (not p) (and (not r) (and (or p (or q r)) (or p q))))
(let-values (((result trace) (symbolic-boolean-normalize '(and (and (or p (or q r)) (not (or r p))) (or q p)))))
  (test '(and (not p) (and (not r) (and (or p (or q r)) (or p q)))) result))

;; (not (or (or (and r p) (or q r)) r)) normalizes to (and (not q) (not r))
(let-values (((result trace) (symbolic-boolean-normalize '(not (or (or (and r p) (or q r)) r)))))
  (test '(and (not q) (not r)) result))

;; (and (or (and (not q) (or r q)) (not (or q q))) (not (or p (not p)))) normalizes to #f
(let-values (((result trace) (symbolic-boolean-normalize '(and (or (and (not q) (or r q)) (not (or q q))) (not (or p (not p)))))))
  (test '#f result))

;; (not q) normalizes to (not q)
(let-values (((result trace) (symbolic-boolean-normalize '(not q))))
  (test '(not q) result))

;; (or p (not (or p r))) normalizes to (or (and (not p) (not r)) p)
(let-values (((result trace) (symbolic-boolean-normalize '(or p (not (or p r))))))
  (test '(or (and (not p) (not r)) p) result))

;; (or r (or (and (or p q) q) (not (not q)))) normalizes to (or q r)
(let-values (((result trace) (symbolic-boolean-normalize '(or r (or (and (or p q) q) (not (not q)))))))
  (test '(or q r) result))

;; (not (and (and (not p) (and r r)) (and (not p) (not q)))) normalizes to (or (not r) (or p q))
(let-values (((result trace) (symbolic-boolean-normalize '(not (and (and (not p) (and r r)) (and (not p) (not q)))))))
  (test '(or (not r) (or p q)) result))

;; (not r) normalizes to (not r)
(let-values (((result trace) (symbolic-boolean-normalize '(not r))))
  (test '(not r) result))

;; (not (not q)) normalizes to q
(let-values (((result trace) (symbolic-boolean-normalize '(not (not q)))))
  (test 'q result))

;; (or p r) normalizes to (or p r)
(let-values (((result trace) (symbolic-boolean-normalize '(or p r))))
  (test '(or p r) result))

;; (or (not r) (not q)) normalizes to (or (not q) (not r))
(let-values (((result trace) (symbolic-boolean-normalize '(or (not r) (not q)))))
  (test '(or (not q) (not r)) result))

;; (not (not q)) normalizes to q
(let-values (((result trace) (symbolic-boolean-normalize '(not (not q)))))
  (test 'q result))

;; (and (or (or (and p q) (not p)) (not (and r r))) (or (and (and q q) r) r)) normalizes to (and (or (and p q) (or (not p) (not r))) r)
(let-values (((result trace) (symbolic-boolean-normalize '(and (or (or (and p q) (not p)) (not (and r r))) (or (and (and q q) r) r)))))
  (test '(and (or (and p q) (or (not p) (not r))) r) result))

;; (or p r) normalizes to (or p r)
(let-values (((result trace) (symbolic-boolean-normalize '(or p r))))
  (test '(or p r) result))

;; (not (not (or (and q p) (and r r)))) normalizes to (or (and p q) r)
(let-values (((result trace) (symbolic-boolean-normalize '(not (not (or (and q p) (and r r)))))))
  (test '(or (and p q) r) result))

;; p normalizes to p
(let-values (((result trace) (symbolic-boolean-normalize 'p)))
  (test 'p result))

;; (or (or (or r (not q)) q) (or r (and (not q) (and r p)))) normalizes to #t
(let-values (((result trace) (symbolic-boolean-normalize '(or (or (or r (not q)) q) (or r (and (not q) (and r p)))))))
  (test '#t result))

;; p normalizes to p
(let-values (((result trace) (symbolic-boolean-normalize 'p)))
  (test 'p result))

;; p normalizes to p
(let-values (((result trace) (symbolic-boolean-normalize 'p)))
  (test 'p result))

;; (or p (not (not (not r)))) normalizes to (or (not r) p)
(let-values (((result trace) (symbolic-boolean-normalize '(or p (not (not (not r)))))))
  (test '(or (not r) p) result))

;; (or (not r) r) normalizes to #t
(let-values (((result trace) (symbolic-boolean-normalize '(or (not r) r))))
  (test '#t result))

;; p normalizes to p
(let-values (((result trace) (symbolic-boolean-normalize 'p)))
  (test 'p result))

;; (or (not (not (not p))) (not (not (not r)))) normalizes to (or (not p) (not r))
(let-values (((result trace) (symbolic-boolean-normalize '(or (not (not (not p))) (not (not (not r)))))))
  (test '(or (not p) (not r)) result))

;; (and r p) normalizes to (and p r)
(let-values (((result trace) (symbolic-boolean-normalize '(and r p))))
  (test '(and p r) result))

;; (and q (or (and (and q p) (not p)) (not (or q q)))) normalizes to #f
(let-values (((result trace) (symbolic-boolean-normalize '(and q (or (and (and q p) (not p)) (not (or q q)))))))
  (test '#f result))

;; p normalizes to p
(let-values (((result trace) (symbolic-boolean-normalize 'p)))
  (test 'p result))

;; (or (and (not q) (and (or q q) (or r q))) (or (and p (not r)) (not p))) normalizes to (or (and (not r) p) (not p))
(let-values (((result trace) (symbolic-boolean-normalize '(or (and (not q) (and (or q q) (or r q))) (or (and p (not r)) (not p))))))
  (test '(or (and (not r) p) (not p)) result))

;; (or (or r (and (and r r) q)) q) normalizes to (or (and q r) (or q r))
(let-values (((result trace) (symbolic-boolean-normalize '(or (or r (and (and r r) q)) q))))
  (test '(or (and q r) (or q r)) result))

;; (not r) normalizes to (not r)
(let-values (((result trace) (symbolic-boolean-normalize '(not r))))
  (test '(not r) result))

;; r normalizes to r
(let-values (((result trace) (symbolic-boolean-normalize 'r)))
  (test 'r result))

;; (and (not (and q (not p))) (not (not p))) normalizes to p
(let-values (((result trace) (symbolic-boolean-normalize '(and (not (and q (not p))) (not (not p))))))
  (test 'p result))

;; (and (and (and r (or p q)) (or (not r) (and q q))) (or (or (not r) r) r)) normalizes to (and (or (not r) q) (and (or p q) r))
(let-values (((result trace) (symbolic-boolean-normalize '(and (and (and r (or p q)) (or (not r) (and q q))) (or (or (not r) r) r)))))
  (test '(and (or (not r) q) (and (or p q) r)) result))

;; (and p q) normalizes to (and p q)
(let-values (((result trace) (symbolic-boolean-normalize '(and p q))))
  (test '(and p q) result))

;; (or q (or (not p) r)) normalizes to (or (not p) (or q r))
(let-values (((result trace) (symbolic-boolean-normalize '(or q (or (not p) r)))))
  (test '(or (not p) (or q r)) result))

;; (or (or (not (or p q)) (or (and r q) (not p))) (and (not (or q q)) (or (and r r) q))) normalizes to (or (and (not p) (not q)) (or (and (not q) (or q r)) (or (and q r) (not p))))
(let-values (((result trace) (symbolic-boolean-normalize '(or (or (not (or p q)) (or (and r q) (not p))) (and (not (or q q)) (or (and r r) q))))))
  (test '(or (and (not p) (not q)) (or (and (not q) (or q r)) (or (and q r) (not p)))) result))

;; (not (not p)) normalizes to p
(let-values (((result trace) (symbolic-boolean-normalize '(not (not p)))))
  (test 'p result))

;; (and (not (or (and p q) r)) (and r (not r))) normalizes to #f
(let-values (((result trace) (symbolic-boolean-normalize '(and (not (or (and p q) r)) (and r (not r))))))
  (test '#f result))

;; (or q (or (and (and p r) (or p r)) (not (not p)))) normalizes to (or (and (or p r) (and p r)) (or p q))
(let-values (((result trace) (symbolic-boolean-normalize '(or q (or (and (and p r) (or p r)) (not (not p)))))))
  (test '(or (and (or p r) (and p r)) (or p q)) result))

;; p normalizes to p
(let-values (((result trace) (symbolic-boolean-normalize 'p)))
  (test 'p result))

;; (not p) normalizes to (not p)
(let-values (((result trace) (symbolic-boolean-normalize '(not p))))
  (test '(not p) result))

;; r normalizes to r
(let-values (((result trace) (symbolic-boolean-normalize 'r)))
  (test 'r result))

;; q normalizes to q
(let-values (((result trace) (symbolic-boolean-normalize 'q)))
  (test 'q result))

;; (or (and (or (or q r) (not q)) (not (or p p))) (and (and (not q) q) (not r))) normalizes to (not p)
(let-values (((result trace) (symbolic-boolean-normalize '(or (and (or (or q r) (not q)) (not (or p p))) (and (and (not q) q) (not r))))))
  (test '(not p) result))

;; (or (and (and (not p) q) (and q q)) (and (and (and q r) r) (and (or r p) (not p)))) normalizes to (or (and (not p) (and (or p r) (and q r))) (and (not p) q))
(let-values (((result trace) (symbolic-boolean-normalize '(or (and (and (not p) q) (and q q)) (and (and (and q r) r) (and (or r p) (not p)))))))
  (test '(or (and (not p) (and (or p r) (and q r))) (and (not p) q)) result))

;; (not (or (or (or q p) (and q r)) p)) normalizes to (and (not p) (not q))
(let-values (((result trace) (symbolic-boolean-normalize '(not (or (or (or q p) (and q r)) p)))))
  (test '(and (not p) (not q)) result))

;; (and (or (and (or q p) (and q p)) (or (or p r) q)) (or q r)) normalizes to (and (or (and (or p q) (and p q)) (or p (or q r))) (or q r))
(let-values (((result trace) (symbolic-boolean-normalize '(and (or (and (or q p) (and q p)) (or (or p r) q)) (or q r)))))
  (test '(and (or (and (or p q) (and p q)) (or p (or q r))) (or q r)) result))

;; (or r q) normalizes to (or q r)
(let-values (((result trace) (symbolic-boolean-normalize '(or r q))))
  (test '(or q r) result))

;; (or (and (or r (not q)) r) (not (or (and p r) (and q r)))) normalizes to (or (and (or (not p) (not r)) (or (not q) (not r))) r)
(let-values (((result trace) (symbolic-boolean-normalize '(or (and (or r (not q)) r) (not (or (and p r) (and q r)))))))
  (test '(or (and (or (not p) (not r)) (or (not q) (not r))) r) result))

;; (and p r) normalizes to (and p r)
(let-values (((result trace) (symbolic-boolean-normalize '(and p r))))
  (test '(and p r) result))

;; (and p q) normalizes to (and p q)
(let-values (((result trace) (symbolic-boolean-normalize '(and p q))))
  (test '(and p q) result))

;; (and r (or (and (and r r) p) (or (or q q) (or r q)))) normalizes to (and (or (and p r) (or q r)) r)
(let-values (((result trace) (symbolic-boolean-normalize '(and r (or (and (and r r) p) (or (or q q) (or r q)))))))
  (test '(and (or (and p r) (or q r)) r) result))

;; (not (or (or (and r p) q) (and (not p) q))) normalizes to (and (not q) (or (not p) (not r)))
(let-values (((result trace) (symbolic-boolean-normalize '(not (or (or (and r p) q) (and (not p) q))))))
  (test '(and (not q) (or (not p) (not r))) result))

;; q normalizes to q
(let-values (((result trace) (symbolic-boolean-normalize 'q)))
  (test 'q result))

;; (or r (and (and (not q) (and r p)) (not (not r)))) normalizes to (or (and (not q) (and p r)) r)
(let-values (((result trace) (symbolic-boolean-normalize '(or r (and (and (not q) (and r p)) (not (not r)))))))
  (test '(or (and (not q) (and p r)) r) result))

;; (or (and (and p r) p) (or q (not (and p r)))) normalizes to (or (and p r) (or (not p) (or (not r) q)))
(let-values (((result trace) (symbolic-boolean-normalize '(or (and (and p r) p) (or q (not (and p r)))))))
  (test '(or (and p r) (or (not p) (or (not r) q))) result))

;; (and (and q (not q)) (and (or r (not r)) (not q))) normalizes to #f
(let-values (((result trace) (symbolic-boolean-normalize '(and (and q (not q)) (and (or r (not r)) (not q))))))
  (test '#f result))

;; q normalizes to q
(let-values (((result trace) (symbolic-boolean-normalize 'q)))
  (test 'q result))

;; (not (or r (or (or p q) p))) normalizes to (and (not p) (and (not q) (not r)))
(let-values (((result trace) (symbolic-boolean-normalize '(not (or r (or (or p q) p))))))
  (test '(and (not p) (and (not q) (not r))) result))

;; (or p (and r (or r (or q r)))) normalizes to (or p r)
(let-values (((result trace) (symbolic-boolean-normalize '(or p (and r (or r (or q r)))))))
  (test '(or p r) result))

;; p normalizes to p
(let-values (((result trace) (symbolic-boolean-normalize 'p)))
  (test 'p result))

;; q normalizes to q
(let-values (((result trace) (symbolic-boolean-normalize 'q)))
  (test 'q result))

;; (and (and (not (not p)) p) p) normalizes to p
(let-values (((result trace) (symbolic-boolean-normalize '(and (and (not (not p)) p) p))))
  (test 'p result))

;; q normalizes to q
(let-values (((result trace) (symbolic-boolean-normalize 'q)))
  (test 'q result))

;; (or (not (and (not r) r)) (not (or p (or r p)))) normalizes to #t
(let-values (((result trace) (symbolic-boolean-normalize '(or (not (and (not r) r)) (not (or p (or r p)))))))
  (test '#t result))

;; q normalizes to q
(let-values (((result trace) (symbolic-boolean-normalize 'q)))
  (test 'q result))

;; (and p q) normalizes to (and p q)
(let-values (((result trace) (symbolic-boolean-normalize '(and p q))))
  (test '(and p q) result))

;; (and (not (or (and q r) (and r q))) (not (or (and r p) (not q)))) normalizes to (and (or (not p) (not r)) (and (or (not q) (not r)) q))
(let-values (((result trace) (symbolic-boolean-normalize '(and (not (or (and q r) (and r q))) (not (or (and r p) (not q)))))))
  (test '(and (or (not p) (not r)) (and (or (not q) (not r)) q)) result))

;; (and (not (not (or q q))) (and (or (or q q) r) (or (not p) q))) normalizes to q
(let-values (((result trace) (symbolic-boolean-normalize '(and (not (not (or q q))) (and (or (or q q) r) (or (not p) q))))))
  (test 'q result))

;; (and (not (not r)) q) normalizes to (and q r)
(let-values (((result trace) (symbolic-boolean-normalize '(and (not (not r)) q))))
  (test '(and q r) result))

;; (not (and (not (not q)) (not (or q r)))) normalizes to #t
(let-values (((result trace) (symbolic-boolean-normalize '(not (and (not (not q)) (not (or q r)))))))
  (test '#t result))

;; (not (or (not (or r r)) p)) normalizes to (and (not p) r)
(let-values (((result trace) (symbolic-boolean-normalize '(not (or (not (or r r)) p)))))
  (test '(and (not p) r) result))

;; p normalizes to p
(let-values (((result trace) (symbolic-boolean-normalize 'p)))
  (test 'p result))

;; r normalizes to r
(let-values (((result trace) (symbolic-boolean-normalize 'r)))
  (test 'r result))

;; (and r p) normalizes to (and p r)
(let-values (((result trace) (symbolic-boolean-normalize '(and r p))))
  (test '(and p r) result))

;; (not r) normalizes to (not r)
(let-values (((result trace) (symbolic-boolean-normalize '(not r))))
  (test '(not r) result))

;; (and (or (not (and r p)) (and (not r) p)) (not q)) normalizes to (and (not q) (or (and (not r) p) (or (not p) (not r))))
(let-values (((result trace) (symbolic-boolean-normalize '(and (or (not (and r p)) (and (not r) p)) (not q)))))
  (test '(and (not q) (or (and (not r) p) (or (not p) (not r)))) result))

;; q normalizes to q
(let-values (((result trace) (symbolic-boolean-normalize 'q)))
  (test 'q result))

;; r normalizes to r
(let-values (((result trace) (symbolic-boolean-normalize 'r)))
  (test 'r result))


(test-end)
(test-exit)
