;;; sage-rewriting-integer-ring-test.scm — Generated by Sage oracle
;;; Oracle: SageMath version 10.8, Release Date: 2025-12-18
;;; Oracle source: Sage-builtin
;;; Date: 2026-06-07
;;; Seed: 42
;;; DO NOT EDIT — regenerate with:
;;;   make sage-snapshot

(import (scheme base)
        (chibi test)
        (wile algebra)
        (wile algebra symbolic)
        (wile algebra rewrite))

(test-begin "sage-rewriting-integer-ring")

;; Evaluate a normalized term to its integer value.
;; The normalizer produces symbolic terms (not arithmetic results),
;; so we need this to compare against Sage's computed values.
(define (term-value t)
  (cond
    ((number? t) t)
    ((not (pair? t)) (error "term-value: unexpected atom" t))
    ((eq? (car t) '+)
     (+ (term-value (cadr t)) (term-value (caddr t))))
    ((eq? (car t) '*)
     (* (term-value (cadr t)) (term-value (caddr t))))
    ((eq? (car t) 'neg)
     (- (term-value (cadr t))))
    (else (error "term-value: unknown operator" (car t)))))

(define proto
  (sexp-term-protocol
    (lambda (a b)
      (cond
        ((and (number? a) (number? b)) (< a b))
        ((number? a) #t)
        ((number? b) #f)
        (else #f)))))

(define norm
  (make-recursive-normalizer
    (ring->theory (integer-ring) '+ '* 'neg)
    proto))

;; Original: (+ (+ -4 (neg 1)) -4) = -9
(let-values (((result trace) (norm '(+ (+ -4 (neg 1)) -4))))
  (test -9 (term-value result)))

;; Original: 3 = 3
(let-values (((result trace) (norm '3)))
  (test 3 (term-value result)))

;; Original: (neg 5) = -5
(let-values (((result trace) (norm '(neg 5))))
  (test -5 (term-value result)))

;; Original: (* 4 -5) = -20
(let-values (((result trace) (norm '(* 4 -5))))
  (test -20 (term-value result)))

;; Original: (+ (* -2 (* 1 0)) (+ (neg 1) -1)) = -2
(let-values (((result trace) (norm '(+ (* -2 (* 1 0)) (+ (neg 1) -1)))))
  (test -2 (term-value result)))

;; Original: (neg (* (neg 5) -1)) = -5
(let-values (((result trace) (norm '(neg (* (neg 5) -1)))))
  (test -5 (term-value result)))

;; Original: (+ (* 5 (+ (+ 5 -1) (neg 5))) 5) = 0
(let-values (((result trace) (norm '(+ (* 5 (+ (+ 5 -1) (neg 5))) 5))))
  (test 0 (term-value result)))

;; Original: -2 = -2
(let-values (((result trace) (norm '-2)))
  (test -2 (term-value result)))

;; Original: 1 = 1
(let-values (((result trace) (norm '1)))
  (test 1 (term-value result)))

;; Original: 5 = 5
(let-values (((result trace) (norm '5)))
  (test 5 (term-value result)))

;; Original: (+ (+ -5 (* -2 (neg 0))) 2) = -3
(let-values (((result trace) (norm '(+ (+ -5 (* -2 (neg 0))) 2))))
  (test -3 (term-value result)))

;; Original: (neg (* 3 (neg (neg 1)))) = -3
(let-values (((result trace) (norm '(neg (* 3 (neg (neg 1)))))))
  (test -3 (term-value result)))

;; Original: (+ (+ (+ -3 (* 4 -4)) (neg (neg -1))) (+ (+ (neg -1) (* -4 -1)) (* -1 (+ 3 -4)))) = -14
(let-values (((result trace) (norm '(+ (+ (+ -3 (* 4 -4)) (neg (neg -1))) (+ (+ (neg -1) (* -4 -1)) (* -1 (+ 3 -4)))))))
  (test -14 (term-value result)))

;; Original: (* (neg (+ (+ 3 3) (neg 0))) (+ (* -2 (+ -4 2)) (neg (+ 5 2)))) = 18
(let-values (((result trace) (norm '(* (neg (+ (+ 3 3) (neg 0))) (+ (* -2 (+ -4 2)) (neg (+ 5 2)))))))
  (test 18 (term-value result)))

;; Original: (+ 4 (+ (neg (neg -1)) (neg (* 3 2)))) = -3
(let-values (((result trace) (norm '(+ 4 (+ (neg (neg -1)) (neg (* 3 2)))))))
  (test -3 (term-value result)))

;; Original: -2 = -2
(let-values (((result trace) (norm '-2)))
  (test -2 (term-value result)))

;; Original: -5 = -5
(let-values (((result trace) (norm '-5)))
  (test -5 (term-value result)))

;; Original: (+ (+ 5 -4) (* -2 2)) = -3
(let-values (((result trace) (norm '(+ (+ 5 -4) (* -2 2)))))
  (test -3 (term-value result)))

;; Original: -3 = -3
(let-values (((result trace) (norm '-3)))
  (test -3 (term-value result)))

;; Original: (neg (+ (* -4 (* 1 1)) (neg 5))) = 9
(let-values (((result trace) (norm '(neg (+ (* -4 (* 1 1)) (neg 5))))))
  (test 9 (term-value result)))

;; Original: (+ 0 (+ -2 (+ (* 2 -2) (+ 2 3)))) = -1
(let-values (((result trace) (norm '(+ 0 (+ -2 (+ (* 2 -2) (+ 2 3)))))))
  (test -1 (term-value result)))

;; Original: 5 = 5
(let-values (((result trace) (norm '5)))
  (test 5 (term-value result)))

;; Original: (+ (+ 2 (* (+ 1 -5) (* 2 -1))) (neg (neg (* -3 -2)))) = 16
(let-values (((result trace) (norm '(+ (+ 2 (* (+ 1 -5) (* 2 -1))) (neg (neg (* -3 -2)))))))
  (test 16 (term-value result)))

;; Original: -5 = -5
(let-values (((result trace) (norm '-5)))
  (test -5 (term-value result)))

;; Original: (neg 0) = 0
(let-values (((result trace) (norm '(neg 0))))
  (test 0 (term-value result)))

;; Original: 4 = 4
(let-values (((result trace) (norm '4)))
  (test 4 (term-value result)))

;; Original: (neg 3) = -3
(let-values (((result trace) (norm '(neg 3))))
  (test -3 (term-value result)))

;; Original: -3 = -3
(let-values (((result trace) (norm '-3)))
  (test -3 (term-value result)))

;; Original: -4 = -4
(let-values (((result trace) (norm '-4)))
  (test -4 (term-value result)))

;; Original: (+ (neg 4) -4) = -8
(let-values (((result trace) (norm '(+ (neg 4) -4))))
  (test -8 (term-value result)))

;; Original: (neg (* (+ (* -2 -1) (neg 5)) 0)) = 0
(let-values (((result trace) (norm '(neg (* (+ (* -2 -1) (neg 5)) 0)))))
  (test 0 (term-value result)))

;; Original: (+ 4 (+ -2 (+ (+ -2 0) 2))) = 2
(let-values (((result trace) (norm '(+ 4 (+ -2 (+ (+ -2 0) 2))))))
  (test 2 (term-value result)))

;; Original: (neg (neg (neg (* 5 -4)))) = 20
(let-values (((result trace) (norm '(neg (neg (neg (* 5 -4)))))))
  (test 20 (term-value result)))

;; Original: (+ -4 (+ 4 0)) = 0
(let-values (((result trace) (norm '(+ -4 (+ 4 0)))))
  (test 0 (term-value result)))

;; Original: 5 = 5
(let-values (((result trace) (norm '5)))
  (test 5 (term-value result)))

;; Original: (neg (+ 1 (+ -3 (* -3 2)))) = 8
(let-values (((result trace) (norm '(neg (+ 1 (+ -3 (* -3 2)))))))
  (test 8 (term-value result)))

;; Original: (* (+ -3 (* (+ 1 -3) 0)) (+ (+ (neg -4) (neg 1)) (neg -2))) = -15
(let-values (((result trace) (norm '(* (+ -3 (* (+ 1 -3) 0)) (+ (+ (neg -4) (neg 1)) (neg -2))))))
  (test -15 (term-value result)))

;; Original: (+ (+ 0 (* (neg -2) -4)) (+ (+ 2 (+ -2 -5)) (* (+ -1 0) (* 5 3)))) = -28
(let-values (((result trace) (norm '(+ (+ 0 (* (neg -2) -4)) (+ (+ 2 (+ -2 -5)) (* (+ -1 0) (* 5 3)))))))
  (test -28 (term-value result)))

;; Original: (+ -1 -1) = -2
(let-values (((result trace) (norm '(+ -1 -1))))
  (test -2 (term-value result)))

;; Original: 4 = 4
(let-values (((result trace) (norm '4)))
  (test 4 (term-value result)))

;; Original: (neg (* (neg 4) -5)) = -20
(let-values (((result trace) (norm '(neg (* (neg 4) -5)))))
  (test -20 (term-value result)))

;; Original: (+ (neg (neg (+ 0 1))) 5) = 6
(let-values (((result trace) (norm '(+ (neg (neg (+ 0 1))) 5))))
  (test 6 (term-value result)))

;; Original: (neg (+ (* (neg 1) (neg -1)) (+ (* 5 -3) (* 1 3)))) = 13
(let-values (((result trace) (norm '(neg (+ (* (neg 1) (neg -1)) (+ (* 5 -3) (* 1 3)))))))
  (test 13 (term-value result)))

;; Original: (* 1 (neg (* (neg -2) (neg -3)))) = -6
(let-values (((result trace) (norm '(* 1 (neg (* (neg -2) (neg -3)))))))
  (test -6 (term-value result)))

;; Original: (* (neg (+ (+ 5 -1) -2)) -5) = 10
(let-values (((result trace) (norm '(* (neg (+ (+ 5 -1) -2)) -5))))
  (test 10 (term-value result)))

;; Original: 2 = 2
(let-values (((result trace) (norm '2)))
  (test 2 (term-value result)))

;; Original: (+ (neg (neg (* 1 -2))) -5) = -7
(let-values (((result trace) (norm '(+ (neg (neg (* 1 -2))) -5))))
  (test -7 (term-value result)))

;; Original: (+ (+ 3 (neg -4)) (* (neg (* 4 3)) (neg (+ 2 2)))) = 55
(let-values (((result trace) (norm '(+ (+ 3 (neg -4)) (* (neg (* 4 3)) (neg (+ 2 2)))))))
  (test 55 (term-value result)))

;; Original: -2 = -2
(let-values (((result trace) (norm '-2)))
  (test -2 (term-value result)))

;; Original: (* (neg (+ -4 (+ -1 0))) (neg -3)) = 15
(let-values (((result trace) (norm '(* (neg (+ -4 (+ -1 0))) (neg -3)))))
  (test 15 (term-value result)))

;; Original: -3 = -3
(let-values (((result trace) (norm '-3)))
  (test -3 (term-value result)))

;; Original: (+ (* (* 1 (neg -5)) (neg (+ 0 -1))) (* (neg (neg -2)) (* (+ 1 0) (* -3 2)))) = 17
(let-values (((result trace) (norm '(+ (* (* 1 (neg -5)) (neg (+ 0 -1))) (* (neg (neg -2)) (* (+ 1 0) (* -3 2)))))))
  (test 17 (term-value result)))

;; Original: (neg (* (neg 5) (* -1 (+ 2 0)))) = -10
(let-values (((result trace) (norm '(neg (* (neg 5) (* -1 (+ 2 0)))))))
  (test -10 (term-value result)))

;; Original: (* 1 -4) = -4
(let-values (((result trace) (norm '(* 1 -4))))
  (test -4 (term-value result)))

;; Original: (neg (* -4 (neg -5))) = 20
(let-values (((result trace) (norm '(neg (* -4 (neg -5))))))
  (test 20 (term-value result)))

;; Original: (+ (neg -3) (+ (+ (* 0 -3) (neg -4)) (+ (+ 4 -5) (neg 5)))) = 1
(let-values (((result trace) (norm '(+ (neg -3) (+ (+ (* 0 -3) (neg -4)) (+ (+ 4 -5) (neg 5)))))))
  (test 1 (term-value result)))

;; Original: (* (neg 4) (neg -1)) = -4
(let-values (((result trace) (norm '(* (neg 4) (neg -1)))))
  (test -4 (term-value result)))

;; Original: (neg (neg (* (neg 0) 5))) = 0
(let-values (((result trace) (norm '(neg (neg (* (neg 0) 5))))))
  (test 0 (term-value result)))

;; Original: (* (+ (* (* -3 1) 3) (* (neg 2) (neg 4))) -2) = 2
(let-values (((result trace) (norm '(* (+ (* (* -3 1) 3) (* (neg 2) (neg 4))) -2))))
  (test 2 (term-value result)))

;; Original: (+ 2 2) = 4
(let-values (((result trace) (norm '(+ 2 2))))
  (test 4 (term-value result)))

;; Original: (neg (+ (* -2 (* 0 -1)) (neg (neg -5)))) = 5
(let-values (((result trace) (norm '(neg (+ (* -2 (* 0 -1)) (neg (neg -5)))))))
  (test 5 (term-value result)))

;; Original: (+ 1 (+ (neg (* -5 -4)) 1)) = -18
(let-values (((result trace) (norm '(+ 1 (+ (neg (* -5 -4)) 1)))))
  (test -18 (term-value result)))

;; Original: (* (* (neg (neg 3)) (neg (* -1 -2))) -2) = 12
(let-values (((result trace) (norm '(* (* (neg (neg 3)) (neg (* -1 -2))) -2))))
  (test 12 (term-value result)))

;; Original: (neg (neg -2)) = -2
(let-values (((result trace) (norm '(neg (neg -2)))))
  (test -2 (term-value result)))

;; Original: (* (neg (+ (* -2 0) -5)) (+ -5 (neg (neg 2)))) = -15
(let-values (((result trace) (norm '(* (neg (+ (* -2 0) -5)) (+ -5 (neg (neg 2)))))))
  (test -15 (term-value result)))

;; Original: -5 = -5
(let-values (((result trace) (norm '-5)))
  (test -5 (term-value result)))

;; Original: (* (* -5 2) -4) = 40
(let-values (((result trace) (norm '(* (* -5 2) -4))))
  (test 40 (term-value result)))

;; Original: (+ (neg -3) (* -2 1)) = 1
(let-values (((result trace) (norm '(+ (neg -3) (* -2 1)))))
  (test 1 (term-value result)))

;; Original: (neg 3) = -3
(let-values (((result trace) (norm '(neg 3))))
  (test -3 (term-value result)))

;; Original: (* 4 (* (+ (neg -4) (+ 5 -2)) -4)) = -112
(let-values (((result trace) (norm '(* 4 (* (+ (neg -4) (+ 5 -2)) -4)))))
  (test -112 (term-value result)))

;; Original: -3 = -3
(let-values (((result trace) (norm '-3)))
  (test -3 (term-value result)))

;; Original: (+ 2 (* -2 -1)) = 4
(let-values (((result trace) (norm '(+ 2 (* -2 -1)))))
  (test 4 (term-value result)))

;; Original: (* -2 (neg (+ (neg -2) (* -3 -4)))) = 28
(let-values (((result trace) (norm '(* -2 (neg (+ (neg -2) (* -3 -4)))))))
  (test 28 (term-value result)))

;; Original: -1 = -1
(let-values (((result trace) (norm '-1)))
  (test -1 (term-value result)))

;; Original: (neg (* -1 (* (* 2 -4) (* 0 4)))) = 0
(let-values (((result trace) (norm '(neg (* -1 (* (* 2 -4) (* 0 4)))))))
  (test 0 (term-value result)))

;; Original: -4 = -4
(let-values (((result trace) (norm '-4)))
  (test -4 (term-value result)))

;; Original: 5 = 5
(let-values (((result trace) (norm '5)))
  (test 5 (term-value result)))

;; Original: (neg (+ (neg (neg -5)) (+ (neg 2) (+ 4 1)))) = 2
(let-values (((result trace) (norm '(neg (+ (neg (neg -5)) (+ (neg 2) (+ 4 1)))))))
  (test 2 (term-value result)))

;; Original: (* (* (* (+ -3 0) (* -1 5)) (neg -4)) (* 1 (+ (neg 2) (+ 3 0)))) = 60
(let-values (((result trace) (norm '(* (* (* (+ -3 0) (* -1 5)) (neg -4)) (* 1 (+ (neg 2) (+ 3 0)))))))
  (test 60 (term-value result)))

;; Original: (* (+ 3 -1) (neg (+ (neg -2) (* 3 -5)))) = 26
(let-values (((result trace) (norm '(* (+ 3 -1) (neg (+ (neg -2) (* 3 -5)))))))
  (test 26 (term-value result)))

;; Original: (+ -4 (+ (+ (neg -1) (* 1 2)) (+ (+ 1 -2) (neg -3)))) = 1
(let-values (((result trace) (norm '(+ -4 (+ (+ (neg -1) (* 1 2)) (+ (+ 1 -2) (neg -3)))))))
  (test 1 (term-value result)))

;; Original: (* (* (neg -5) -1) (neg (* (* 3 2) (neg 3)))) = -90
(let-values (((result trace) (norm '(* (* (neg -5) -1) (neg (* (* 3 2) (neg 3)))))))
  (test -90 (term-value result)))

;; Original: (* (neg 1) 1) = -1
(let-values (((result trace) (norm '(* (neg 1) 1))))
  (test -1 (term-value result)))

;; Original: 2 = 2
(let-values (((result trace) (norm '2)))
  (test 2 (term-value result)))

;; Original: (* (neg (neg (* -5 -3))) (neg (+ (* -4 3) (+ -3 1)))) = 210
(let-values (((result trace) (norm '(* (neg (neg (* -5 -3))) (neg (+ (* -4 3) (+ -3 1)))))))
  (test 210 (term-value result)))

;; Original: (+ -1 (neg (+ (neg 3) (* 5 2)))) = -8
(let-values (((result trace) (norm '(+ -1 (neg (+ (neg 3) (* 5 2)))))))
  (test -8 (term-value result)))

;; Original: (+ (+ (* (neg -4) (+ 5 -4)) (neg -5)) -5) = 4
(let-values (((result trace) (norm '(+ (+ (* (neg -4) (+ 5 -4)) (neg -5)) -5))))
  (test 4 (term-value result)))

;; Original: 0 = 0
(let-values (((result trace) (norm '0)))
  (test 0 (term-value result)))

;; Original: (+ (neg (+ -4 (* 4 5))) 4) = -12
(let-values (((result trace) (norm '(+ (neg (+ -4 (* 4 5))) 4))))
  (test -12 (term-value result)))

;; Original: 2 = 2
(let-values (((result trace) (norm '2)))
  (test 2 (term-value result)))

;; Original: (* -5 (* (neg (+ 2 0)) (* (* -1 2) (+ 1 2)))) = -60
(let-values (((result trace) (norm '(* -5 (* (neg (+ 2 0)) (* (* -1 2) (+ 1 2)))))))
  (test -60 (term-value result)))

;; Original: 1 = 1
(let-values (((result trace) (norm '1)))
  (test 1 (term-value result)))

;; Original: (neg -1) = 1
(let-values (((result trace) (norm '(neg -1))))
  (test 1 (term-value result)))

;; Original: 5 = 5
(let-values (((result trace) (norm '5)))
  (test 5 (term-value result)))

;; Original: (+ (neg (+ (neg 2) (* -2 4))) (+ (neg 5) (+ (neg 5) 2))) = 2
(let-values (((result trace) (norm '(+ (neg (+ (neg 2) (* -2 4))) (+ (neg 5) (+ (neg 5) 2))))))
  (test 2 (term-value result)))

;; Original: 0 = 0
(let-values (((result trace) (norm '0)))
  (test 0 (term-value result)))

;; Original: (+ (* (+ 3 (* 3 3)) (+ 2 (* 0 -4))) (+ -2 (neg (* 3 0)))) = 22
(let-values (((result trace) (norm '(+ (* (+ 3 (* 3 3)) (+ 2 (* 0 -4))) (+ -2 (neg (* 3 0)))))))
  (test 22 (term-value result)))

;; Original: 1 = 1
(let-values (((result trace) (norm '1)))
  (test 1 (term-value result)))

;; Original: 3 = 3
(let-values (((result trace) (norm '3)))
  (test 3 (term-value result)))

;; Original: 0 = 0
(let-values (((result trace) (norm '0)))
  (test 0 (term-value result)))


(test-end)
(test-exit)
