;;; sage-structures-semiring-matrix-test.scm — Generated by Sage oracle
;;; Oracle: SageMath version 10.8, Release Date: 2025-12-18
;;; Oracle source: hybrid
;;; Date: 2026-06-07
;;; Seed: 42
;;; DO NOT EDIT — regenerate with:
;;;   make sage-snapshot

(import (scheme base)
        (chibi test)
        (wile algebra))

(test-begin "sage-structures-semiring-matrix")

(test 10 (let ((S (counting-semiring))) (semiring-matrix-permanent (semiring-matrix-from-rows S '((1 2) (3 4))))))
(test '((1 0) (0 1)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((1 2) (3 4))) 0))))
(test '((1 2) (3 4)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((1 2) (3 4))) 1))))
(test '((7 10) (15 22)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((1 2) (3 4))) 2))))
(test '((37 54) (81 118)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((1 2) (3 4))) 3))))
(test '((7 10) (15 22)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((1 2) (3 4))) (semiring-matrix-from-rows S '((1 2) (3 4)))))))
(test '((19 22) (43 50)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((1 2) (3 4))) (semiring-matrix-from-rows S '((5 6) (7 8)))))))
(test '((1 3) (3 7)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((1 2) (3 4))) (semiring-matrix-from-rows S '((1 1) (0 1)))))))
(test '((4 6) (10 12)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((1 2) (3 4))) (semiring-matrix-from-rows S '((2 0) (1 3)))))))
(test 82 (let ((S (counting-semiring))) (semiring-matrix-permanent (semiring-matrix-from-rows S '((5 6) (7 8))))))
(test '((1 0) (0 1)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((5 6) (7 8))) 0))))
(test '((5 6) (7 8)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((5 6) (7 8))) 1))))
(test '((67 78) (91 106)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((5 6) (7 8))) 2))))
(test '((881 1026) (1197 1394)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((5 6) (7 8))) 3))))
(test '((23 34) (31 46)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((5 6) (7 8))) (semiring-matrix-from-rows S '((1 2) (3 4)))))))
(test '((67 78) (91 106)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((5 6) (7 8))) (semiring-matrix-from-rows S '((5 6) (7 8)))))))
(test '((5 11) (7 15)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((5 6) (7 8))) (semiring-matrix-from-rows S '((1 1) (0 1)))))))
(test '((16 18) (22 24)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((5 6) (7 8))) (semiring-matrix-from-rows S '((2 0) (1 3)))))))
(test 1 (let ((S (counting-semiring))) (semiring-matrix-permanent (semiring-matrix-from-rows S '((1 1) (0 1))))))
(test '((1 0) (0 1)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((1 1) (0 1))) 0))))
(test '((1 1) (0 1)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((1 1) (0 1))) 1))))
(test '((1 2) (0 1)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((1 1) (0 1))) 2))))
(test '((1 3) (0 1)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((1 1) (0 1))) 3))))
(test '((4 6) (3 4)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((1 1) (0 1))) (semiring-matrix-from-rows S '((1 2) (3 4)))))))
(test '((12 14) (7 8)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((1 1) (0 1))) (semiring-matrix-from-rows S '((5 6) (7 8)))))))
(test '((1 2) (0 1)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((1 1) (0 1))) (semiring-matrix-from-rows S '((1 1) (0 1)))))))
(test '((3 3) (1 3)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((1 1) (0 1))) (semiring-matrix-from-rows S '((2 0) (1 3)))))))
(test 6 (let ((S (counting-semiring))) (semiring-matrix-permanent (semiring-matrix-from-rows S '((2 0) (1 3))))))
(test '((1 0) (0 1)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((2 0) (1 3))) 0))))
(test '((2 0) (1 3)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((2 0) (1 3))) 1))))
(test '((4 0) (5 9)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((2 0) (1 3))) 2))))
(test '((8 0) (19 27)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S '((2 0) (1 3))) 3))))
(test '((2 4) (10 14)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((2 0) (1 3))) (semiring-matrix-from-rows S '((1 2) (3 4)))))))
(test '((10 12) (26 30)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((2 0) (1 3))) (semiring-matrix-from-rows S '((5 6) (7 8)))))))
(test '((2 2) (1 4)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((2 0) (1 3))) (semiring-matrix-from-rows S '((1 1) (0 1)))))))
(test '((4 0) (5 9)) (let ((S (counting-semiring))) (semiring-matrix->rows (semiring-matrix-mul (semiring-matrix-from-rows S '((2 0) (1 3))) (semiring-matrix-from-rows S '((2 0) (1 3)))))))
(test 3 (let ((S (tropical-semiring))) (semiring-matrix-permanent (semiring-matrix-from-rows S '((4 1) (2 5))))))
(test 0 (let ((S (tropical-semiring))) (semiring-matrix-permanent (semiring-matrix-from-rows S '((0 3) (7 0))))))
(test 4 (let ((S (tropical-semiring))) (semiring-matrix-permanent (semiring-matrix-from-rows S '((2 9) (9 2))))))
(test '((#t #t #t) (#f #t #t) (#f #f #t)) (let ((S (boolean-semiring))) (semiring-matrix->rows (semiring-matrix-closure (semiring-matrix-from-rows S '((#f #t #f) (#f #f #t) (#f #f #f)))))))
(test '((#t #f) (#t #t)) (let ((S (boolean-semiring))) (semiring-matrix->rows (semiring-matrix-closure (semiring-matrix-from-rows S '((#t #f) (#t #f)))))))

(test-end)
(test-exit)
