(("%char-set" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetCtor" "extensions/charsets/charsets.go:56")
 ("%empty-char-set" "" () "github.com/aalpar/wile/extensions/charsets.primEmptyCharSet" "extensions/charsets/charsets.go:87")
 ("%make-lazy-promise" "any" ("procedure") "github.com/aalpar/wile/internal/extensions/all.PrimMakeLazyPromise" "internal/extensions/all/prim_all.go:377")
 ("%make-named-charset" "" () "github.com/aalpar/wile/extensions/charsets.primMakeNamedCharSet" "extensions/charsets/charsets.go:577")
 ("%parameter-convert" "any" ("procedure" "any") "github.com/aalpar/wile/registry/core.PrimParameterConvert" "registry/core/prim_parameters.go:89")
 ("%parameter-raw-set!" "void" ("procedure" "any") "github.com/aalpar/wile/registry/core.PrimParameterRawSet" "registry/core/prim_parameters.go:73")
 ("*" "number" ("...number") "github.com/aalpar/wile/registry/core.PrimMul" "registry/core/prim_arithmetic.go:47")
 ("+" "number" ("...number") "github.com/aalpar/wile/registry/core.PrimAdd" "registry/core/prim_arithmetic.go:28")
 ("-" "number" ("number" "...number") "github.com/aalpar/wile/registry/core.PrimSub" "registry/core/prim_arithmetic.go:36")
 ("/" "number" ("number" "...number") "github.com/aalpar/wile/registry/core.PrimDiv" "registry/core/prim_arithmetic.go:55")
 ("<" "boolean" ("real" "...real") "github.com/aalpar/wile/registry/core.PrimNumLt" "registry/core/prim_arithmetic.go:131")
 ("<=" "boolean" ("real" "...real") "github.com/aalpar/wile/registry/core.PrimNumLe" "registry/core/prim_arithmetic.go:150")
 ("=" "boolean" ("number" "...number") "github.com/aalpar/wile/registry/core.PrimNumEq" "registry/core/prim_arithmetic.go:122")
 (">" "boolean" ("real" "...real") "github.com/aalpar/wile/registry/core.PrimNumGt" "registry/core/prim_arithmetic.go:140")
 (">=" "boolean" ("real" "...real") "github.com/aalpar/wile/registry/core.PrimNumGe" "registry/core/prim_arithmetic.go:164")
 ("abort-current-continuation" "any" ("any" "...any") "github.com/aalpar/wile/registry/core.PrimAbortCurrentContinuation" "registry/core/prim_prompt.go:159")
 ("abs" "real" ("real") "github.com/aalpar/wile/registry/core.PrimAbs" "registry/core/prim_arithmetic.go:176")
 ("acos" "number" ("number") "github.com/aalpar/wile/extensions/math.init.makeComplexPrimitive.func14" "extensions/math/prim_transcendental.go:33")
 ("angle" "flonum" ("number") "github.com/aalpar/wile/extensions/math.PrimAngle" "extensions/math/prim_complex.go:231")
 ("append" "list" ("...any") "github.com/aalpar/wile/registry/core.PrimAppend" "registry/core/prim_lists.go:86")
 ("apply" "any" ("procedure" "...any") "github.com/aalpar/wile/registry/core.PrimApply" "registry/core/prim_control.go:29")
 ("apropos" "list" ("string") "github.com/aalpar/wile/registry/core.PrimApropos" "registry/core/prim_reflection.go:397")
 ("asin" "number" ("number") "github.com/aalpar/wile/extensions/math.init.makeComplexPrimitive.func13" "extensions/math/prim_transcendental.go:33")
 ("assq" "any" ("any" "list") "github.com/aalpar/wile/registry/core.PrimAssq" "registry/core/prim_lists.go:312")
 ("assv" "any" ("any" "list") "github.com/aalpar/wile/registry/core.PrimAssv" "registry/core/prim_lists.go:317")
 ("atan" "number" ("number" "...number") "github.com/aalpar/wile/extensions/math.PrimAtan" "extensions/math/prim_transcendental.go:81")
 ("atomic-compare-and-swap!" "boolean" ("any" "any" "any") "github.com/aalpar/wile/extensions/gointerop.PrimAtomicCompareAndSwap" "extensions/gointerop/prim_gointerop.go:527")
 ("atomic-load" "any" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimAtomicLoad" "extensions/gointerop/prim_gointerop.go:478")
 ("atomic-store!" "void" ("any" "any") "github.com/aalpar/wile/extensions/gointerop.PrimAtomicStore" "extensions/gointerop/prim_gointerop.go:495")
 ("atomic-swap!" "any" ("any" "any") "github.com/aalpar/wile/extensions/gointerop.PrimAtomicSwap" "extensions/gointerop/prim_gointerop.go:509")
 ("atomic?" "boolean" ("any") "github.com/aalpar/wile/extensions/gointerop.init.MakeTypePredicate.func10" "registry/helpers/type.go:26")
 ("available-libraries" "list" () "github.com/aalpar/wile/extensions/introspection.PrimAvailableLibraries" "extensions/introspection/prim_introspection.go:135")
 ("binary-port?" "boolean" ("any") "github.com/aalpar/wile/internal/extensions/io.PrimBinaryPortQ" "internal/extensions/io/prim_ports.go:278")
 ("boolean?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func36" "registry/helpers/type.go:26")
 ("bound-identifier=?" "boolean" ("any" "any") "github.com/aalpar/wile/registry/core.PrimBoundIdentifierEqualQ" "registry/core/prim_syntax.go:160")
 ("box" "any" ("any") "github.com/aalpar/wile/registry/core.PrimBox" "registry/core/prim_boxes.go:26")
 ("box?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func29" "registry/helpers/type.go:26")
 ("bytevector" "bytevector" ("...integer") "github.com/aalpar/wile/registry/core.PrimBytevector" "registry/core/prim_byte_vectors.go:56")
 ("bytevector-append" "bytevector" ("...bytevector") "github.com/aalpar/wile/registry/core.PrimBytevectorAppend" "registry/core/prim_byte_vectors.go:176")
 ("bytevector-copy" "bytevector" ("bytevector" "...integer") "github.com/aalpar/wile/registry/core.PrimBytevectorCopy" "registry/core/prim_byte_vectors.go:125")
 ("bytevector-copy!" "void" ("bytevector" "integer" "bytevector" "...integer") "github.com/aalpar/wile/registry/core.PrimBytevectorCopyBang" "registry/core/prim_byte_vectors.go:145")
 ("bytevector-length" "integer" ("bytevector") "github.com/aalpar/wile/registry/core.PrimBytevectorLength" "registry/core/prim_byte_vectors.go:90")
 ("bytevector-u8-ref" "integer" ("bytevector" "integer") "github.com/aalpar/wile/registry/core.PrimBytevectorU8Ref" "registry/core/prim_byte_vectors.go:96")
 ("bytevector-u8-set!" "void" ("bytevector" "integer" "integer") "github.com/aalpar/wile/registry/core.PrimBytevectorU8Set" "registry/core/prim_byte_vectors.go:106")
 ("bytevector?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func43" "registry/helpers/type.go:26")
 ("call-with-composable-continuation" "any" ("procedure" "any") "github.com/aalpar/wile/registry/core.PrimCallWithComposableContinuation" "registry/core/prim_prompt.go:215")
 ("call-with-continuation-barrier" "any" ("procedure") "github.com/aalpar/wile/registry/core.PrimCallWithContinuationBarrier" "registry/core/prim_barrier.go:39")
 ("call-with-continuation-prompt" "any" ("procedure" "any" "procedure") "github.com/aalpar/wile/registry/core.PrimCallWithContinuationPrompt" "registry/core/prim_prompt.go:70")
 ("call-with-current-continuation" "any" ("procedure") "github.com/aalpar/wile/registry/core.PrimCallCC" "registry/core/prim_control.go:137")
 ("call-with-exit" "any" ("procedure") "github.com/aalpar/wile/registry/core.PrimCallWithExit" "registry/core/prim_exit.go:40")
 ("call-with-immediate-continuation-mark" "any" ("any" "procedure" "...any") "github.com/aalpar/wile/registry/core.PrimCallWithImmediateContMark" "registry/core/prim_cont_marks.go:162")
 ("call-with-input-file" "any" ("string" "procedure") "github.com/aalpar/wile/extensions/files.PrimCallWithInputFile" "extensions/files/prim_files.go:184")
 ("call-with-output-file" "any" ("string" "procedure") "github.com/aalpar/wile/extensions/files.PrimCallWithOutputFile" "extensions/files/prim_files.go:193")
 ("call-with-values" "any" ("procedure" "procedure") "github.com/aalpar/wile/registry/core.PrimCallWithValues" "registry/core/prim_control.go:319")
 ("call/cc" "any" ("procedure") "github.com/aalpar/wile/registry/core.PrimCallCC" "registry/core/prim_control.go:137")
 ("car" "any" ("pair") "github.com/aalpar/wile/registry/core.PrimCar" "registry/core/prim_pairs.go:37")
 ("cdr" "any" ("pair") "github.com/aalpar/wile/registry/core.PrimCdr" "registry/core/prim_pairs.go:53")
 ("ceiling" "real" ("real") "github.com/aalpar/wile/extensions/math.init.makeRealNumberPrimitive.func2" "extensions/math/prim_rounding.go:36")
 ("channel-capacity" "integer" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimChannelCapacity" "extensions/gointerop/prim_gointerop.go:196")
 ("channel-close!" "void" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimChannelClose" "extensions/gointerop/prim_gointerop.go:155")
 ("channel-closed?" "boolean" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimChannelClosedQ" "extensions/gointerop/prim_gointerop.go:172")
 ("channel-length" "integer" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimChannelLength" "extensions/gointerop/prim_gointerop.go:184")
 ("channel-receive" "any" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimChannelReceive" "extensions/gointerop/prim_gointerop.go:80")
 ("channel-send!" "void" ("any" "any") "github.com/aalpar/wile/extensions/gointerop.PrimChannelSend" "extensions/gointerop/prim_gointerop.go:62")
 ("channel-try-receive" "any" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimChannelTryReceive" "extensions/gointerop/prim_gointerop.go:119")
 ("channel-try-send!" "boolean" ("any" "any") "github.com/aalpar/wile/extensions/gointerop.PrimChannelTrySend" "extensions/gointerop/prim_gointerop.go:101")
 ("channel?" "boolean" ("any") "github.com/aalpar/wile/extensions/gointerop.init.MakeTypePredicate.func6" "registry/helpers/type.go:26")
 ("char->integer" "integer" ("character") "github.com/aalpar/wile/registry/core.PrimCharToInteger" "registry/core/prim_characters.go:26")
 ("char-alphabetic?" "boolean" ("character") "github.com/aalpar/wile/internal/extensions/all.init.MakeCharPredicate.func21" "registry/helpers/type.go:58")
 ("char-ci<=?" "boolean" ("character" "...character") "github.com/aalpar/wile/internal/extensions/all.addMoreChars.makeCharCiComparePrimitive.func1" "internal/extensions/all/prim_characters.go:47")
 ("char-ci<?" "boolean" ("character" "...character") "github.com/aalpar/wile/internal/extensions/all.addMoreChars.makeCharCiComparePrimitive.func1" "internal/extensions/all/prim_characters.go:47")
 ("char-ci=?" "boolean" ("character" "...character") "github.com/aalpar/wile/internal/extensions/all.addMoreChars.makeCharCiComparePrimitive.func1" "internal/extensions/all/prim_characters.go:47")
 ("char-ci>=?" "boolean" ("character" "...character") "github.com/aalpar/wile/internal/extensions/all.addMoreChars.makeCharCiComparePrimitive.func1" "internal/extensions/all/prim_characters.go:47")
 ("char-ci>?" "boolean" ("character" "...character") "github.com/aalpar/wile/internal/extensions/all.addMoreChars.makeCharCiComparePrimitive.func1" "internal/extensions/all/prim_characters.go:47")
 ("char-downcase" "character" ("character") "github.com/aalpar/wile/internal/extensions/all.init.MakeCharTransform.func27" "registry/helpers/type.go:71")
 ("char-foldcase" "character" ("character") "github.com/aalpar/wile/internal/extensions/all.init.MakeCharTransform.func28" "registry/helpers/type.go:71")
 ("char-lower-case?" "boolean" ("character") "github.com/aalpar/wile/internal/extensions/all.init.MakeCharPredicate.func25" "registry/helpers/type.go:58")
 ("char-numeric?" "boolean" ("character") "github.com/aalpar/wile/internal/extensions/all.init.MakeCharPredicate.func22" "registry/helpers/type.go:58")
 ("char-ready?" "boolean" ("...textual-input-port") "github.com/aalpar/wile/internal/extensions/io.PrimCharReadyQ" "internal/extensions/io/prim_read_write.go:410")
 ("char-set->list" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetToList" "extensions/charsets/charsets.go:233")
 ("char-set->string" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetToString" "extensions/charsets/charsets.go:246")
 ("char-set-complement" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetComplement" "extensions/charsets/charsets.go:365")
 ("char-set-contains?" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetContains" "extensions/charsets/charsets.go:34")
 ("char-set-copy" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetCopy" "extensions/charsets/charsets.go:92")
 ("char-set-difference" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetDifference" "extensions/charsets/charsets.go:339")
 ("char-set-intersection" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetIntersection" "extensions/charsets/charsets.go:326")
 ("char-set-ranges" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetRanges" "extensions/charsets/charsets.go:259")
 ("char-set-size" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetSize" "extensions/charsets/charsets.go:47")
 ("char-set-union" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetUnion" "extensions/charsets/charsets.go:313")
 ("char-set-xor" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetXor" "extensions/charsets/charsets.go:352")
 ("char-set<=" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetSubset" "extensions/charsets/charsets.go:298")
 ("char-set=" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetEqual" "extensions/charsets/charsets.go:283")
 ("char-set?" "" () "github.com/aalpar/wile/extensions/charsets.primCharSetQ" "extensions/charsets/charsets.go:28")
 ("char-upcase" "character" ("character") "github.com/aalpar/wile/internal/extensions/all.init.MakeCharTransform.func26" "registry/helpers/type.go:71")
 ("char-upper-case?" "boolean" ("character") "github.com/aalpar/wile/internal/extensions/all.init.MakeCharPredicate.func24" "registry/helpers/type.go:58")
 ("char-whitespace?" "boolean" ("character") "github.com/aalpar/wile/internal/extensions/all.init.MakeCharPredicate.func23" "registry/helpers/type.go:58")
 ("char<=?" "boolean" ("character" "...character") "github.com/aalpar/wile/registry/core.addCharacters.makeCharComparePrimitive.func1" "registry/core/prim_characters.go:70")
 ("char<?" "boolean" ("character" "...character") "github.com/aalpar/wile/registry/core.addCharacters.makeCharComparePrimitive.func1" "registry/core/prim_characters.go:70")
 ("char=?" "boolean" ("character" "...character") "github.com/aalpar/wile/registry/core.addCharacters.makeCharComparePrimitive.func1" "registry/core/prim_characters.go:70")
 ("char>=?" "boolean" ("character" "...character") "github.com/aalpar/wile/registry/core.addCharacters.makeCharComparePrimitive.func1" "registry/core/prim_characters.go:70")
 ("char>?" "boolean" ("character" "...character") "github.com/aalpar/wile/registry/core.addCharacters.makeCharComparePrimitive.func1" "registry/core/prim_characters.go:70")
 ("char?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func40" "registry/helpers/type.go:26")
 ("close-input-port" "void" ("input-port") "github.com/aalpar/wile/internal/extensions/io.PrimCloseInputPort" "internal/extensions/io/prim_ports.go:110")
 ("close-output-port" "void" ("output-port") "github.com/aalpar/wile/internal/extensions/io.PrimCloseOutputPort" "internal/extensions/io/prim_ports.go:134")
 ("close-port" "void" ("port") "github.com/aalpar/wile/internal/extensions/io.PrimClosePort" "internal/extensions/io/prim_ports.go:92")
 ("command-line" "list" () "github.com/aalpar/wile/extensions/system.PrimCommandLine" "extensions/system/prim_system.go:43")
 ("compile" "procedure" ("any") "github.com/aalpar/wile/extensions/eval.PrimCompile" "extensions/eval/prim_eval.go:502")
 ("complex-inexact-with-accuracy" "" ("number") "github.com/aalpar/wile/extensions/math.PrimComplexInexactWithAccuracy" "extensions/math/prim_conversion.go:422")
 ("complex?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func42" "registry/helpers/type.go:26")
 ("condition-variable-broadcast!" "void" ("any") "github.com/aalpar/wile/extensions/threads.PrimConditionVariableBroadcast" "extensions/threads/prim_threads.go:590")
 ("condition-variable-name" "string" ("any") "github.com/aalpar/wile/extensions/threads.PrimConditionVariableName" "extensions/threads/prim_threads.go:537")
 ("condition-variable-signal!" "void" ("any") "github.com/aalpar/wile/extensions/threads.PrimConditionVariableSignal" "extensions/threads/prim_threads.go:578")
 ("condition-variable-specific" "any" ("any") "github.com/aalpar/wile/extensions/threads.PrimConditionVariableSpecific" "extensions/threads/prim_threads.go:548")
 ("condition-variable-specific-set!" "void" ("any" "any") "github.com/aalpar/wile/extensions/threads.PrimConditionVariableSpecificSet" "extensions/threads/prim_threads.go:564")
 ("condition-variable?" "boolean" ("any") "github.com/aalpar/wile/extensions/threads.init.MakeTypePredicate.func7" "registry/helpers/type.go:26")
 ("cons" "pair" ("any" "any") "github.com/aalpar/wile/registry/core.PrimCons" "registry/core/prim_pairs.go:26")
 ("continuation-mark-set->list" "list" ("any" "any") "github.com/aalpar/wile/registry/core.PrimContinuationMarkSetToList" "registry/core/prim_cont_marks.go:45")
 ("continuation-mark-set->list*" "list" ("any" "list" "...any") "github.com/aalpar/wile/registry/core.PrimContinuationMarkSetToListStar" "registry/core/prim_cont_marks.go:81")
 ("continuation-mark-set-first" "any" ("any" "any" "...any") "github.com/aalpar/wile/registry/core.PrimContinuationMarkSetFirst" "registry/core/prim_cont_marks.go:56")
 ("continuation-mark-set?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func30" "registry/helpers/type.go:26")
 ("continuation-marks" "any" ("any" "...any") "github.com/aalpar/wile/registry/core.PrimContinuationMarks" "registry/core/prim_cont_marks.go:126")
 ("continuation-prompt-available?" "boolean" ("any") "github.com/aalpar/wile/registry/core.PrimContinuationPromptAvailableQ" "registry/core/prim_prompt.go:194")
 ("continuation-prompt-tag?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func47" "registry/helpers/type.go:26")
 ("continuation?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func31" "registry/helpers/type.go:26")
 ("cos" "number" ("number") "github.com/aalpar/wile/extensions/math.init.makeComplexPrimitive.func11" "extensions/math/prim_transcendental.go:33")
 ("count-paths-cyclic" "" ("integer" "list" "integer") "github.com/aalpar/wile/extensions/algebragraph.PrimCountPathsCyclic" "extensions/algebragraph/prim_count_paths.go:149")
 ("count-paths-in-dag" "" ("integer" "list" "integer") "github.com/aalpar/wile/extensions/algebragraph.PrimCountPathsInDAG" "extensions/algebragraph/prim_count_paths.go:115")
 ("create-directory" "void" ("string") "github.com/aalpar/wile/extensions/files.PrimCreateDirectory" "extensions/files/prim_directory.go:31")
 ("current-continuation-marks" "any" ("...any") "github.com/aalpar/wile/registry/core.PrimCurrentContinuationMarks" "registry/core/prim_cont_marks.go:26")
 ("current-directory" "string" () "github.com/aalpar/wile/extensions/files.PrimCurrentDirectory" "extensions/files/prim_directory.go:119")
 ("current-error-context" "any" () "github.com/aalpar/wile/registry/core.PrimCurrentErrorContext" "registry/core/prim_error_context.go:27")
 ("current-jiffy" "integer" () "github.com/aalpar/wile/extensions/system.PrimCurrentJiffy" "extensions/system/prim_system.go:110")
 ("current-load-depth" "integer" () "github.com/aalpar/wile/extensions/eval.PrimCurrentLoadDepth" "extensions/eval/prim_eval.go:218")
 ("current-load-directory" "any" () "github.com/aalpar/wile/extensions/eval.PrimCurrentLoadDirectory" "extensions/eval/prim_eval.go:205")
 ("current-load-path" "any" () "github.com/aalpar/wile/extensions/eval.PrimCurrentLoadPath" "extensions/eval/prim_eval.go:192")
 ("current-second" "flonum" () "github.com/aalpar/wile/extensions/system.PrimCurrentSecond" "extensions/system/prim_system.go:101")
 ("current-thread" "any" () "github.com/aalpar/wile/extensions/threads.PrimCurrentThread" "extensions/threads/prim_threads.go:83")
 ("current-time" "any" () "github.com/aalpar/wile/extensions/threads.PrimCurrentTime" "extensions/threads/prim_threads.go:606")
 ("datum->syntax" "any" ("any" "any") "github.com/aalpar/wile/registry/core.PrimDatumToSyntax" "registry/core/prim_syntax.go:62")
 ("default-continuation-prompt-tag" "any" () "github.com/aalpar/wile/registry/core.PrimDefaultContinuationPromptTag" "registry/core/prim_prompt.go:50")
 ("delete-directory" "void" ("string") "github.com/aalpar/wile/extensions/files.PrimDeleteDirectory" "extensions/files/prim_directory.go:54")
 ("delete-file" "void" ("string") "github.com/aalpar/wile/extensions/files.PrimDeleteFile" "extensions/files/prim_files.go:108")
 ("denominator" "real" ("real") "github.com/aalpar/wile/extensions/math.PrimDenominator" "extensions/math/prim_rational.go:64")
 ("digit-value" "any" ("character") "github.com/aalpar/wile/internal/extensions/all.PrimDigitValue" "internal/extensions/all/prim_characters.go:98")
 ("directory-files" "list" ("string") "github.com/aalpar/wile/extensions/files.PrimDirectoryFiles" "extensions/files/prim_directory.go:88")
 ("disassemble" "list" ("procedure") "github.com/aalpar/wile/extensions/introspection.PrimDisassemble" "extensions/introspection/prim_disassemble.go:25")
 ("display" "void" ("any" "...textual-output-port") "github.com/aalpar/wile/internal/extensions/io.PrimDisplay" "internal/extensions/io/prim_write.go:85")
 ("doc-topic" "list" ("string") "github.com/aalpar/wile/registry/core.PrimDocTopic" "registry/core/prim_reflection.go:329")
 ("doc-topics" "list" () "github.com/aalpar/wile/registry/core.PrimDocTopics" "registry/core/prim_reflection.go:303")
 ("emergency-exit" "any" ("...any") "github.com/aalpar/wile/extensions/system.PrimEmergencyExit" "extensions/system/prim_system.go:95")
 ("environment" "any" ("...list") "github.com/aalpar/wile/extensions/eval.PrimEnvironment" "extensions/eval/prim_eval.go:341")
 ("environment-bound-names" "list" ("any") "github.com/aalpar/wile/extensions/introspection.PrimEnvironmentBoundNames" "extensions/introspection/prim_introspection.go:47")
 ("environment-bound?" "boolean" ("any" "symbol") "github.com/aalpar/wile/extensions/introspection.PrimEnvironmentBoundQ" "extensions/introspection/prim_introspection.go:98")
 ("environment-ref" "any" ("any" "symbol") "github.com/aalpar/wile/extensions/introspection.PrimEnvironmentRef" "extensions/introspection/prim_introspection.go:71")
 ("environment?" "boolean" ("any") "github.com/aalpar/wile/extensions/introspection.init.MakeTypePredicate.func2" "registry/helpers/type.go:26")
 ("eof-object" "any" () "github.com/aalpar/wile/internal/extensions/io.PrimEofObject" "internal/extensions/io/prim_ports.go:162")
 ("eof-object?" "boolean" ("any") "github.com/aalpar/wile/internal/extensions/io.PrimEofObjectQ" "internal/extensions/io/prim_ports.go:169")
 ("eq?" "boolean" ("any" "any") "github.com/aalpar/wile/registry/core.PrimEqQ" "registry/core/prim_equality.go:26")
 ("equal?" "boolean" ("any" "any") "github.com/aalpar/wile/registry/core.PrimEqualQ" "registry/core/prim_equality.go:50")
 ("eqv?" "boolean" ("any" "any") "github.com/aalpar/wile/registry/core.PrimEqvQ" "registry/core/prim_equality.go:41")
 ("error" "any" ("string" "...any") "github.com/aalpar/wile/registry/core.PrimError" "registry/core/prim_exceptions.go:268")
 ("error-context-marks" "any" ("any") "github.com/aalpar/wile/registry/core.PrimErrorContextMarks" "registry/core/prim_error_context.go:74")
 ("error-context-source" "any" ("any") "github.com/aalpar/wile/registry/core.PrimErrorContextSource" "registry/core/prim_error_context.go:44")
 ("error-context-stack-trace" "list" ("any") "github.com/aalpar/wile/registry/core.PrimErrorContextStackTrace" "registry/core/prim_error_context.go:62")
 ("error-context?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func32" "registry/helpers/type.go:26")
 ("error-object-irritants" "list" ("any") "github.com/aalpar/wile/registry/core.PrimErrorObjectIrritants" "registry/core/prim_exceptions.go:330")
 ("error-object-message" "string" ("any") "github.com/aalpar/wile/registry/core.PrimErrorObjectMessage" "registry/core/prim_exceptions.go:319")
 ("error-object-source" "any" ("any") "github.com/aalpar/wile/registry/core.PrimErrorObjectSource" "registry/core/prim_error_context.go:90")
 ("error-object-stack-trace" "list" ("any") "github.com/aalpar/wile/registry/core.PrimErrorObjectStackTrace" "registry/core/prim_error_context.go:107")
 ("error-object?" "boolean" ("any") "github.com/aalpar/wile/registry/core.PrimErrorObjectQ" "registry/core/prim_exceptions.go:310")
 ("eval" "any" ("...any") "github.com/aalpar/wile/extensions/eval.PrimEval" "extensions/eval/prim_eval.go:51")
 ("even?" "boolean" ("integer") "github.com/aalpar/wile/registry/core.PrimEvenQ" "registry/core/prim_predicates.go:234")
 ("exact" "number" ("number") "github.com/aalpar/wile/registry/core.PrimExact" "registry/core/prim_arithmetic.go:340")
 ("exact->inexact" "number" ("number") "github.com/aalpar/wile/registry/core.PrimInexact" "registry/core/prim_arithmetic.go:358")
 ("exact-integer-sqrt" "" ("integer") "github.com/aalpar/wile/extensions/math.PrimExactIntegerSqrt" "extensions/math/prim_rational.go:226")
 ("exact?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeNumericPredicate[...].func45" "registry/helpers/type.go:45")
 ("exit" "any" ("...any") "github.com/aalpar/wile/extensions/system.PrimExit" "extensions/system/prim_system.go:89")
 ("exp" "number" ("number") "github.com/aalpar/wile/extensions/math.init.makeComplexPrimitive.func9" "extensions/math/prim_transcendental.go:33")
 ("expand" "any" ("any") "github.com/aalpar/wile/extensions/eval.PrimExpand" "extensions/eval/prim_eval.go:416")
 ("expand-once" "any" ("any") "github.com/aalpar/wile/extensions/eval.PrimExpandOnce" "extensions/eval/prim_eval.go:455")
 ("expt" "number" ("number" "number") "github.com/aalpar/wile/extensions/math.PrimExpt" "extensions/math/prim_transcendental.go:275")
 ("features" "list" () "github.com/aalpar/wile/extensions/introspection.PrimFeatures" "extensions/introspection/prim_introspection.go:120")
 ("file-error?" "boolean" ("any") "github.com/aalpar/wile/registry/core.PrimFileErrorQ" "registry/core/prim_exceptions.go:350")
 ("file-exists?" "boolean" ("string") "github.com/aalpar/wile/extensions/files.PrimFileExistsQ" "extensions/files/prim_files.go:88")
 ("finite?" "boolean" ("number") "github.com/aalpar/wile/extensions/math.PrimFiniteQ" "extensions/math/prim_rounding.go:198")
 ("floor" "real" ("real") "github.com/aalpar/wile/extensions/math.init.makeRealNumberPrimitive.func4" "extensions/math/prim_rounding.go:36")
 ("floor-quotient" "real" ("real" "real") "github.com/aalpar/wile/extensions/math.PrimFloorQuotient" "extensions/math/prim_rounding.go:165")
 ("floor-remainder" "real" ("real" "real") "github.com/aalpar/wile/extensions/math.PrimFloorRemainder" "extensions/math/prim_rounding.go:172")
 ("floor/" "" ("real" "real") "github.com/aalpar/wile/extensions/math.PrimFloorDiv" "extensions/math/prim_rounding.go:158")
 ("flush-output-port" "void" ("...output-port") "github.com/aalpar/wile/internal/extensions/io.PrimFlushOutputPort" "internal/extensions/io/prim_write.go:209")
 ("force" "any" ("any") "github.com/aalpar/wile/internal/extensions/all.PrimForce" "internal/extensions/all/prim_all.go:358")
 ("free-identifier=?" "boolean" ("any" "any") "github.com/aalpar/wile/registry/core.PrimFreeIdentifierEqualQ" "registry/core/prim_syntax.go:190")
 ("gcd" "real" ("...real") "github.com/aalpar/wile/registry/core.PrimGcd" "registry/core/prim_arithmetic.go:313")
 ("generate-temporaries" "list" ("any") "github.com/aalpar/wile/registry/core.PrimGenerateTemporaries" "registry/core/prim_syntax.go:132")
 ("get-environment-variable" "any" ("string") "github.com/aalpar/wile/internal/extensions/envvars.PrimGetEnvironmentVariable" "internal/extensions/envvars/prim_envvars.go:48")
 ("get-environment-variables" "list" () "github.com/aalpar/wile/internal/extensions/envvars.PrimGetEnvironmentVariables" "internal/extensions/envvars/prim_envvars.go:86")
 ("get-output-bytevector" "bytevector" ("binary-output-port") "github.com/aalpar/wile/internal/extensions/io.PrimGetOutputBytevector" "internal/extensions/io/prim_ports.go:243")
 ("get-output-string" "string" ("textual-output-port") "github.com/aalpar/wile/internal/extensions/io.PrimGetOutputString" "internal/extensions/io/prim_ports.go:197")
 ("hashtable-clear!" "void" ("hashtable") "github.com/aalpar/wile/registry/core.PrimHashtableClear" "registry/core/prim_hashtables.go:147")
 ("hashtable-copy" "hashtable" ("hashtable") "github.com/aalpar/wile/registry/core.PrimHashtableCopy" "registry/core/prim_hashtables.go:136")
 ("hashtable-delete!" "void" ("hashtable" "any") "github.com/aalpar/wile/registry/core.PrimHashtableDelete" "registry/core/prim_hashtables.go:88")
 ("hashtable-keys" "list" ("hashtable") "github.com/aalpar/wile/registry/core.PrimHashtableKeys" "registry/core/prim_hashtables.go:103")
 ("hashtable-ref" "any" ("hashtable" "any" "...any") "github.com/aalpar/wile/registry/core.PrimHashtableRef" "registry/core/prim_hashtables.go:41")
 ("hashtable-set!" "void" ("hashtable" "any" "any") "github.com/aalpar/wile/registry/core.PrimHashtableSet" "registry/core/prim_hashtables.go:73")
 ("hashtable-size" "integer" ("hashtable") "github.com/aalpar/wile/registry/core.PrimHashtableSize" "registry/core/prim_hashtables.go:125")
 ("hashtable-values" "list" ("hashtable") "github.com/aalpar/wile/registry/core.PrimHashtableValues" "registry/core/prim_hashtables.go:114")
 ("hashtable?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func33" "registry/helpers/type.go:26")
 ("identifier?" "boolean" ("any") "github.com/aalpar/wile/registry/core.PrimIdentifierQ" "registry/core/prim_syntax.go:32")
 ("imag-part" "real" ("number") "github.com/aalpar/wile/extensions/math.PrimImagPart" "extensions/math/prim_complex.go:181")
 ("inexact" "number" ("number") "github.com/aalpar/wile/registry/core.PrimInexact" "registry/core/prim_arithmetic.go:358")
 ("inexact->exact" "number" ("number") "github.com/aalpar/wile/registry/core.PrimExact" "registry/core/prim_arithmetic.go:340")
 ("inexact-accuracy" "" ("number") "github.com/aalpar/wile/extensions/math.PrimInexactAccuracy" "extensions/math/prim_conversion.go:353")
 ("inexact-lossless?" "boolean" ("number") "github.com/aalpar/wile/extensions/math.PrimInexactLosslessQ" "extensions/math/prim_conversion.go:334")
 ("inexact-with-accuracy" "" ("number") "github.com/aalpar/wile/extensions/math.PrimInexactWithAccuracy" "extensions/math/prim_conversion.go:385")
 ("inexact?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeNumericPredicate[...].func46" "registry/helpers/type.go:45")
 ("infinite?" "boolean" ("number") "github.com/aalpar/wile/extensions/math.PrimInfiniteQ" "extensions/math/prim_rounding.go:208")
 ("input-port-open?" "boolean" ("input-port") "github.com/aalpar/wile/internal/extensions/io.PrimInputPortOpenQ" "internal/extensions/io/prim_ports.go:56")
 ("input-port?" "boolean" ("any") "github.com/aalpar/wile/internal/extensions/io.init.MakeTypePredicate.func5" "registry/helpers/type.go:26")
 ("integer->char" "character" ("integer") "github.com/aalpar/wile/registry/core.PrimIntegerToChar" "registry/core/prim_characters.go:40")
 ("integer?" "boolean" ("any") "github.com/aalpar/wile/registry/core.PrimIntegerQ" "registry/core/prim_predicates.go:119")
 ("interaction-environment" "any" () "github.com/aalpar/wile/extensions/introspection.PrimInteractionEnvironment" "extensions/introspection/prim_introspection.go:35")
 ("jiffies-per-second" "integer" () "github.com/aalpar/wile/extensions/system.PrimJiffiesPerSecond" "extensions/system/prim_system.go:119")
 ("lcm" "real" ("...real") "github.com/aalpar/wile/registry/core.PrimLcm" "registry/core/prim_arithmetic.go:320")
 ("length" "integer" ("list") "github.com/aalpar/wile/registry/core.PrimLength" "registry/core/prim_lists.go:161")
 ("library-description" "any" ("list") "github.com/aalpar/wile/registry/core.PrimLibraryDescription" "registry/core/prim_reflection.go:365")
 ("list" "list" ("...any") "github.com/aalpar/wile/registry/core.PrimList" "registry/core/prim_lists.go:32")
 ("list->char-set" "" () "github.com/aalpar/wile/extensions/charsets.primListToCharSet" "extensions/charsets/charsets.go:117")
 ("list->string" "string" ("list") "github.com/aalpar/wile/registry/core.PrimListToString" "registry/core/prim_strings.go:155")
 ("list->vector" "vector" ("list") "github.com/aalpar/wile/registry/core.PrimListToVector" "registry/core/prim_vectors.go:101")
 ("list-copy" "list" ("list") "github.com/aalpar/wile/registry/core.PrimListCopy" "registry/core/prim_lists.go:257")
 ("list-ref" "any" ("list" "integer") "github.com/aalpar/wile/registry/core.PrimListRef" "registry/core/prim_lists.go:186")
 ("list-set!" "void" ("pair" "integer" "any") "github.com/aalpar/wile/registry/core.PrimListSet" "registry/core/prim_lists.go:207")
 ("list-tail" "any" ("list" "integer") "github.com/aalpar/wile/registry/core.PrimListTail" "registry/core/prim_lists.go:241")
 ("load" "any" ("string") "github.com/aalpar/wile/extensions/eval.PrimLoad" "extensions/eval/prim_eval.go:115")
 ("log" "number" ("number" "...number") "github.com/aalpar/wile/extensions/math.PrimLog" "extensions/math/prim_transcendental.go:54")
 ("magnitude" "real" ("number") "github.com/aalpar/wile/extensions/math.PrimMagnitude" "extensions/math/prim_complex.go:200")
 ("make-atomic" "any" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimMakeAtomic" "extensions/gointerop/prim_gointerop.go:461")
 ("make-bytevector" "bytevector" ("integer" "...integer") "github.com/aalpar/wile/registry/core.PrimMakeBytevector" "registry/core/prim_byte_vectors.go:29")
 ("make-channel" "any" ("...any") "github.com/aalpar/wile/extensions/gointerop.PrimMakeChannel" "extensions/gointerop/prim_gointerop.go:33")
 ("make-compile-time-value" "any" ("any") "github.com/aalpar/wile/extensions/eval.PrimMakeCompileTimeValue" "extensions/eval/prim_eval.go:609")
 ("make-condition-variable" "any" ("...any") "github.com/aalpar/wile/extensions/threads.PrimMakeConditionVariable" "extensions/threads/prim_threads.go:525")
 ("make-continuation-prompt-tag" "any" ("...symbol") "github.com/aalpar/wile/registry/core.PrimMakeContinuationPromptTag" "registry/core/prim_prompt.go:31")
 ("make-hashtable" "hashtable" () "github.com/aalpar/wile/registry/core.PrimMakeHashtable" "registry/core/prim_hashtables.go:26")
 ("make-list" "list" ("integer" "...any") "github.com/aalpar/wile/registry/core.PrimMakeList" "registry/core/prim_lists.go:55")
 ("make-mutex" "any" ("...any") "github.com/aalpar/wile/extensions/threads.PrimMakeMutex" "extensions/threads/prim_threads.go:329")
 ("make-namespace" "any" ("...any") "github.com/aalpar/wile/internal/extensions/namespace.PrimMakeNamespace" "internal/extensions/namespace/prim_namespace.go:51")
 ("make-once" "any" () "github.com/aalpar/wile/extensions/gointerop.PrimMakeOnce" "extensions/gointerop/prim_gointerop.go:390")
 ("make-opaque-record-type" "any" ("symbol" "list") "github.com/aalpar/wile/internal/extensions/all.PrimMakeOpaqueRecordType" "internal/extensions/all/prim_all.go:56")
 ("make-parameter" "procedure" ("any" "...procedure") "github.com/aalpar/wile/registry/core.PrimMakeParameter" "registry/core/prim_parameters.go:32")
 ("make-polar" "complex" ("real" "real") "github.com/aalpar/wile/extensions/math.PrimMakePolar" "extensions/math/prim_complex.go:142")
 ("make-promise" "any" ("any") "github.com/aalpar/wile/internal/extensions/all.PrimMakePromise" "internal/extensions/all/prim_all.go:293")
 ("make-record-type" "any" ("symbol" "list") "github.com/aalpar/wile/internal/extensions/all.PrimMakeRecordType" "internal/extensions/all/prim_all.go:35")
 ("make-rectangular" "number" ("real" "real") "github.com/aalpar/wile/extensions/math.PrimMakeRectangular" "extensions/math/prim_complex.go:29")
 ("make-rw-mutex" "any" ("...any") "github.com/aalpar/wile/extensions/gointerop.PrimMakeRWMutex" "extensions/gointerop/prim_gointerop.go:275")
 ("make-string" "string" ("integer" "...character") "github.com/aalpar/wile/registry/core.PrimMakeString" "registry/core/prim_strings.go:55")
 ("make-thread" "any" ("procedure" "...any") "github.com/aalpar/wile/extensions/threads.PrimMakeThread" "extensions/threads/prim_threads.go:103")
 ("make-vector" "vector" ("integer" "...any") "github.com/aalpar/wile/registry/core.PrimMakeVector" "registry/core/prim_vectors.go:26")
 ("make-wait-group" "any" () "github.com/aalpar/wile/extensions/gointerop.PrimMakeWaitGroup" "extensions/gointerop/prim_gointerop.go:212")
 ("max" "real" ("real" "...real") "github.com/aalpar/wile/registry/core.PrimMax" "registry/core/prim_arithmetic.go:198")
 ("memq" "any" ("any" "list") "github.com/aalpar/wile/registry/core.PrimMemq" "registry/core/prim_lists.go:301")
 ("memv" "any" ("any" "list") "github.com/aalpar/wile/registry/core.PrimMemv" "registry/core/prim_lists.go:307")
 ("min" "real" ("real" "...real") "github.com/aalpar/wile/registry/core.PrimMin" "registry/core/prim_arithmetic.go:191")
 ("modulo" "real" ("real" "real") "github.com/aalpar/wile/registry/core.PrimModulo" "registry/core/prim_arithmetic.go:308")
 ("mutex-lock!" "boolean" ("any" "...any") "github.com/aalpar/wile/extensions/threads.PrimMutexLock" "extensions/threads/prim_threads.go:395")
 ("mutex-name" "string" ("any") "github.com/aalpar/wile/extensions/threads.PrimMutexName" "extensions/threads/prim_threads.go:341")
 ("mutex-specific" "any" ("any") "github.com/aalpar/wile/extensions/threads.PrimMutexSpecific" "extensions/threads/prim_threads.go:352")
 ("mutex-specific-set!" "void" ("any" "any") "github.com/aalpar/wile/extensions/threads.PrimMutexSpecificSet" "extensions/threads/prim_threads.go:368")
 ("mutex-state" "any" ("any") "github.com/aalpar/wile/extensions/threads.PrimMutexState" "extensions/threads/prim_threads.go:383")
 ("mutex-unlock!" "boolean" ("any" "...any") "github.com/aalpar/wile/extensions/threads.PrimMutexUnlock" "extensions/threads/prim_threads.go:461")
 ("mutex?" "boolean" ("any") "github.com/aalpar/wile/extensions/threads.init.MakeTypePredicate.func6" "registry/helpers/type.go:26")
 ("namespace-bound-names" "list" ("any") "github.com/aalpar/wile/internal/extensions/namespace.PrimNamespaceBoundNames" "internal/extensions/namespace/prim_namespace.go:222")
 ("namespace-bound?" "boolean" ("any" "symbol") "github.com/aalpar/wile/internal/extensions/namespace.PrimNamespaceBound" "internal/extensions/namespace/prim_namespace.go:189")
 ("namespace-define!" "void" ("any" "symbol" "any") "github.com/aalpar/wile/internal/extensions/namespace.PrimNamespaceDefine" "internal/extensions/namespace/prim_namespace.go:119")
 ("namespace-derive" "any" ("any") "github.com/aalpar/wile/internal/extensions/namespace.PrimNamespaceDerive" "internal/extensions/namespace/prim_namespace.go:109")
 ("namespace-name" "any" ("any") "github.com/aalpar/wile/internal/extensions/namespace.PrimNamespaceName" "internal/extensions/namespace/prim_namespace.go:35")
 ("namespace-ref" "any" ("any" "...symbol") "github.com/aalpar/wile/internal/extensions/namespace.PrimNamespaceRef" "internal/extensions/namespace/prim_namespace.go:144")
 ("namespace-require" "void" ("any" "list") "github.com/aalpar/wile/internal/extensions/namespace.PrimNamespaceRequire" "internal/extensions/namespace/prim_namespace.go:241")
 ("namespace-undefine!" "void" ("any" "symbol") "github.com/aalpar/wile/internal/extensions/namespace.PrimNamespaceUndefine" "internal/extensions/namespace/prim_namespace.go:206")
 ("namespace?" "boolean" ("any") "github.com/aalpar/wile/internal/extensions/namespace.init.MakeTypePredicate.func2" "registry/helpers/type.go:26")
 ("nan?" "boolean" ("number") "github.com/aalpar/wile/extensions/math.PrimNanQ" "extensions/math/prim_rounding.go:218")
 ("newline" "void" ("...textual-output-port") "github.com/aalpar/wile/internal/extensions/io.PrimNewline" "internal/extensions/io/prim_write.go:101")
 ("null-environment" "any" ("integer") "github.com/aalpar/wile/extensions/eval.PrimNullEnvironment" "extensions/eval/prim_eval.go:256")
 ("null?" "boolean" ("any") "github.com/aalpar/wile/registry/core.PrimNullQ" "registry/core/prim_predicates.go:98")
 ("number->string" "string" ("number" "...integer") "github.com/aalpar/wile/extensions/math.PrimNumberToString" "extensions/math/prim_conversion.go:48")
 ("number?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func41" "registry/helpers/type.go:26")
 ("numerator" "real" ("real") "github.com/aalpar/wile/extensions/math.PrimNumerator" "extensions/math/prim_rational.go:27")
 ("odd?" "boolean" ("integer") "github.com/aalpar/wile/registry/core.PrimOddQ" "registry/core/prim_predicates.go:220")
 ("once-do!" "boolean" ("any" "procedure") "github.com/aalpar/wile/extensions/gointerop.PrimOnceDo" "extensions/gointerop/prim_gointerop.go:405")
 ("once-done?" "boolean" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimOnceDoneQ" "extensions/gointerop/prim_gointerop.go:445")
 ("once?" "boolean" ("any") "github.com/aalpar/wile/extensions/gointerop.init.MakeTypePredicate.func9" "registry/helpers/type.go:26")
 ("opaque-tag" "symbol" ("any") "github.com/aalpar/wile/registry/core.PrimOpaqueTag" "registry/core/prim_opaque.go:33")
 ("opaque?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func34" "registry/helpers/type.go:26")
 ("open-binary-input-file" "binary-input-port" ("string") "github.com/aalpar/wile/extensions/files.PrimOpenBinaryInputFile" "extensions/files/prim_files.go:72")
 ("open-binary-output-file" "binary-output-port" ("string") "github.com/aalpar/wile/extensions/files.PrimOpenBinaryOutputFile" "extensions/files/prim_files.go:80")
 ("open-input-bytevector" "binary-input-port" ("bytevector") "github.com/aalpar/wile/internal/extensions/io.PrimOpenInputBytevector" "internal/extensions/io/prim_ports.go:213")
 ("open-input-file" "textual-input-port" ("string") "github.com/aalpar/wile/extensions/files.PrimOpenInputFile" "extensions/files/prim_files.go:56")
 ("open-input-string" "textual-input-port" ("string") "github.com/aalpar/wile/internal/extensions/io.PrimOpenInputString" "internal/extensions/io/prim_ports.go:176")
 ("open-output-bytevector" "binary-output-port" () "github.com/aalpar/wile/internal/extensions/io.PrimOpenOutputBytevector" "internal/extensions/io/prim_ports.go:231")
 ("open-output-file" "textual-output-port" ("string") "github.com/aalpar/wile/extensions/files.PrimOpenOutputFile" "extensions/files/prim_files.go:64")
 ("open-output-string" "textual-output-port" () "github.com/aalpar/wile/internal/extensions/io.PrimOpenOutputString" "internal/extensions/io/prim_ports.go:186")
 ("output-port-open?" "boolean" ("output-port") "github.com/aalpar/wile/internal/extensions/io.PrimOutputPortOpenQ" "internal/extensions/io/prim_ports.go:74")
 ("output-port?" "boolean" ("any") "github.com/aalpar/wile/internal/extensions/io.init.MakeTypePredicate.func6" "registry/helpers/type.go:26")
 ("pair?" "boolean" ("any") "github.com/aalpar/wile/registry/core.PrimPairQ" "registry/core/prim_predicates.go:108")
 ("parameter?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func35" "registry/helpers/type.go:26")
 ("peek-char" "any" ("...textual-input-port") "github.com/aalpar/wile/internal/extensions/io.PrimPeekChar" "internal/extensions/io/prim_read_write.go:329")
 ("peek-u8" "any" ("...binary-input-port") "github.com/aalpar/wile/internal/extensions/io.PrimPeekU8" "internal/extensions/io/prim_binary.go:59")
 ("port?" "boolean" ("any") "github.com/aalpar/wile/internal/extensions/io.init.MakeTypePredicate.func4" "registry/helpers/type.go:26")
 ("primitive-spec-category" "string" () "github.com/aalpar/wile/registry/core.PrimPrimitiveSpecCategory" "registry/core/prim_reflection.go:625")
 ("primitive-spec-go-function" "string" () "github.com/aalpar/wile/registry/core.PrimPrimitiveSpecGoFunction" "registry/core/prim_reflection.go:600")
 ("primitive-spec-go-source" "string" () "github.com/aalpar/wile/registry/core.PrimPrimitiveSpecGoSource" "registry/core/prim_reflection.go:614")
 ("primitive-spec-name" "string" () "github.com/aalpar/wile/registry/core.PrimPrimitiveSpecName" "registry/core/prim_reflection.go:553")
 ("primitive-spec-param-count" "integer" () "github.com/aalpar/wile/registry/core.PrimPrimitiveSpecParamCount" "registry/core/prim_reflection.go:578")
 ("primitive-spec-return-type" "string" () "github.com/aalpar/wile/registry/core.PrimPrimitiveSpecReturnType" "registry/core/prim_reflection.go:564")
 ("primitive-spec-variadic?" "boolean" () "github.com/aalpar/wile/registry/core.PrimPrimitiveSpecVariadicQ" "registry/core/prim_reflection.go:588")
 ("primitive-spec?" "boolean" () "github.com/aalpar/wile/registry/core.PrimPrimitiveSpecQ" "registry/core/prim_reflection.go:546")
 ("procedure-arity" "any" ("procedure") "github.com/aalpar/wile/registry/core.PrimProcedureArity" "registry/core/prim_reflection.go:97")
 ("procedure-bound-symbols" "any" ("procedure") "github.com/aalpar/wile/registry/core.PrimProcedureBoundSymbols" "registry/core/prim_reflection.go:214")
 ("procedure-documentation" "any" ("procedure") "github.com/aalpar/wile/registry/core.PrimProcedureDocumentation" "registry/core/prim_reflection.go:268")
 ("procedure-name" "any" ("procedure") "github.com/aalpar/wile/registry/core.PrimProcedureName" "registry/core/prim_reflection.go:129")
 ("procedure-source-location" "any" ("procedure") "github.com/aalpar/wile/registry/core.PrimProcedureSourceLocation" "registry/core/prim_reflection.go:162")
 ("procedure-type" "symbol" ("procedure") "github.com/aalpar/wile/registry/core.PrimProcedureType" "registry/core/prim_reflection.go:238")
 ("procedure?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func44" "registry/helpers/type.go:26")
 ("process-kill" "void" ("any" "symbol") "github.com/aalpar/wile/extensions/process.PrimProcessKill" "extensions/process/prim_process.go:205")
 ("process-spawn" "any" ("string" "...string") "github.com/aalpar/wile/extensions/process.PrimProcessSpawn" "extensions/process/prim_process.go:61")
 ("process-stderr" "textual-input-port" ("any") "github.com/aalpar/wile/extensions/process.PrimProcessStderr" "extensions/process/prim_process.go:149")
 ("process-stdin" "textual-output-port" ("any") "github.com/aalpar/wile/extensions/process.PrimProcessStdin" "extensions/process/prim_process.go:159")
 ("process-stdout" "textual-input-port" ("any") "github.com/aalpar/wile/extensions/process.PrimProcessStdout" "extensions/process/prim_process.go:139")
 ("process-wait" "integer" ("any") "github.com/aalpar/wile/extensions/process.PrimProcessWait" "extensions/process/prim_process.go:170")
 ("process?" "boolean" ("any") "github.com/aalpar/wile/extensions/process.PrimProcessQ" "extensions/process/prim_process.go:238")
 ("promise?" "boolean" ("any") "github.com/aalpar/wile/internal/extensions/all.init.MakeTypePredicate.func20" "registry/helpers/type.go:26")
 ("quotient" "real" ("real" "real") "github.com/aalpar/wile/registry/core.PrimQuotient" "registry/core/prim_arithmetic.go:266")
 ("raise" "any" ("any") "github.com/aalpar/wile/registry/core.PrimRaise" "registry/core/prim_exceptions.go:224")
 ("raise-continuable" "any" ("any") "github.com/aalpar/wile/registry/core.PrimRaiseContinuable" "registry/core/prim_exceptions.go:243")
 ("rational?" "boolean" ("any") "github.com/aalpar/wile/registry/core.PrimRationalQ" "registry/core/prim_predicates.go:151")
 ("rationalize" "real" ("real" "real") "github.com/aalpar/wile/extensions/math.PrimRationalize" "extensions/math/prim_rational.go:101")
 ("read" "any" ("...textual-input-port") "github.com/aalpar/wile/internal/extensions/io.PrimRead" "internal/extensions/io/prim_read_write.go:208")
 ("read-bytevector" "any" ("integer" "...binary-input-port") "github.com/aalpar/wile/internal/extensions/io.PrimReadBytevector" "internal/extensions/io/prim_binary.go:132")
 ("read-bytevector!" "any" ("bytevector" "...binary-input-port") "github.com/aalpar/wile/internal/extensions/io.PrimReadBytevectorBang" "internal/extensions/io/prim_binary.go:187")
 ("read-char" "any" ("...textual-input-port") "github.com/aalpar/wile/internal/extensions/io.PrimReadChar" "internal/extensions/io/prim_read_write.go:308")
 ("read-error?" "boolean" ("any") "github.com/aalpar/wile/registry/core.PrimReadErrorQ" "registry/core/prim_exceptions.go:341")
 ("read-line" "any" ("...textual-input-port") "github.com/aalpar/wile/internal/extensions/io.PrimReadLine" "internal/extensions/io/prim_read_write.go:358")
 ("read-string" "any" ("integer" "...textual-input-port") "github.com/aalpar/wile/internal/extensions/io.PrimReadString" "internal/extensions/io/prim_read_write.go:421")
 ("read-syntax" "any" ("...textual-input-port") "github.com/aalpar/wile/internal/extensions/io.PrimReadSyntax" "internal/extensions/io/prim_read_write.go:276")
 ("read-token" "any" ("...textual-input-port") "github.com/aalpar/wile/internal/extensions/io.PrimReadToken" "internal/extensions/io/prim_read_write.go:244")
 ("read-u8" "any" ("...binary-input-port") "github.com/aalpar/wile/internal/extensions/io.PrimReadU8" "internal/extensions/io/prim_binary.go:37")
 ("real-part" "real" ("number") "github.com/aalpar/wile/extensions/math.PrimRealPart" "extensions/math/prim_complex.go:164")
 ("real?" "boolean" ("any") "github.com/aalpar/wile/registry/core.PrimRealQ" "registry/core/prim_predicates.go:133")
 ("record-accessor" "procedure" ("any" "symbol") "github.com/aalpar/wile/internal/extensions/all.PrimRecordAccessor" "internal/extensions/all/prim_all.go:175")
 ("record-constructor" "procedure" ("any" "list") "github.com/aalpar/wile/internal/extensions/all.PrimRecordConstructor" "internal/extensions/all/prim_all.go:105")
 ("record-modifier" "procedure" ("any" "symbol") "github.com/aalpar/wile/internal/extensions/all.PrimRecordModifier" "internal/extensions/all/prim_all.go:181")
 ("record-predicate" "procedure" ("any") "github.com/aalpar/wile/internal/extensions/all.PrimRecordPredicate" "internal/extensions/all/prim_all.go:137")
 ("record-type" "any" ("any") "github.com/aalpar/wile/internal/extensions/all.PrimRecordType" "internal/extensions/all/prim_all.go:91")
 ("record-type?" "boolean" ("any") "github.com/aalpar/wile/internal/extensions/all.init.MakeTypePredicate.func18" "registry/helpers/type.go:26")
 ("record?" "boolean" ("any") "github.com/aalpar/wile/internal/extensions/all.init.MakeTypePredicate.func19" "registry/helpers/type.go:26")
 ("registered-primitives" "list" () "github.com/aalpar/wile/registry/core.PrimRegisteredPrimitives" "registry/core/prim_reflection.go:525")
 ("remainder" "real" ("real" "real") "github.com/aalpar/wile/registry/core.PrimRemainder" "registry/core/prim_arithmetic.go:277")
 ("reverse" "list" ("list") "github.com/aalpar/wile/registry/core.PrimReverse" "registry/core/prim_lists.go:137")
 ("round" "real" ("real") "github.com/aalpar/wile/extensions/math.init.makeRealNumberPrimitive.func8" "extensions/math/prim_rounding.go:36")
 ("rw-mutex-read-lock!" "void" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimRWMutexReadLock" "extensions/gointerop/prim_gointerop.go:310")
 ("rw-mutex-read-unlock!" "void" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimRWMutexReadUnlock" "extensions/gointerop/prim_gointerop.go:323")
 ("rw-mutex-try-read-lock!" "boolean" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimRWMutexTryReadLock" "extensions/gointerop/prim_gointerop.go:362")
 ("rw-mutex-try-write-lock!" "boolean" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimRWMutexTryWriteLock" "extensions/gointerop/prim_gointerop.go:374")
 ("rw-mutex-write-lock!" "void" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimRWMutexWriteLock" "extensions/gointerop/prim_gointerop.go:336")
 ("rw-mutex-write-unlock!" "void" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimRWMutexWriteUnlock" "extensions/gointerop/prim_gointerop.go:349")
 ("rw-mutex?" "boolean" ("any") "github.com/aalpar/wile/extensions/gointerop.init.MakeTypePredicate.func8" "registry/helpers/type.go:26")
 ("sat-cnf-flat-model" "" () "github.com/aalpar/wile/extensions/sat.PrimSatCNFFlatModel" "extensions/sat/prim_sat.go:105")
 ("sat-cnf-flat?" "" ("vector" "any") "github.com/aalpar/wile/extensions/sat.PrimSatCNFFlat" "extensions/sat/prim_sat.go:38")
 ("scheme-report-environment" "any" ("integer") "github.com/aalpar/wile/extensions/eval.PrimSchemeReportEnvironment" "extensions/eval/prim_eval.go:230")
 ("seconds->time" "any" ("number") "github.com/aalpar/wile/extensions/threads.PrimSecondsToTime" "extensions/threads/prim_threads.go:631")
 ("set-box!" "void" ("any" "any") "github.com/aalpar/wile/registry/core.PrimSetBox" "registry/core/prim_boxes.go:51")
 ("set-car!" "void" ("pair" "any") "github.com/aalpar/wile/registry/core.PrimSetCar" "registry/core/prim_pairs.go:66")
 ("set-cdr!" "void" ("pair" "any") "github.com/aalpar/wile/registry/core.PrimSetCdr" "registry/core/prim_pairs.go:78")
 ("set-current-directory!" "void" ("string") "github.com/aalpar/wile/extensions/files.PrimSetCurrentDirectory" "extensions/files/prim_directory.go:134")
 ("sin" "number" ("number") "github.com/aalpar/wile/extensions/math.init.makeComplexPrimitive.func10" "extensions/math/prim_transcendental.go:33")
 ("sqrt" "number" ("number") "github.com/aalpar/wile/extensions/math.PrimSqrt" "extensions/math/prim_transcendental.go:141")
 ("string" "string" ("...character") "github.com/aalpar/wile/registry/core.PrimString" "registry/core/prim_strings.go:30")
 ("string->char-set" "" () "github.com/aalpar/wile/extensions/charsets.primStringToCharSet" "extensions/charsets/charsets.go:104")
 ("string->list" "list" ("string" "...integer") "github.com/aalpar/wile/registry/core.PrimStringToList" "registry/core/prim_strings.go:131")
 ("string->number" "any" ("string" "...integer") "github.com/aalpar/wile/extensions/math.PrimStringToNumber" "extensions/math/prim_conversion.go:106")
 ("string->symbol" "symbol" ("string") "github.com/aalpar/wile/registry/core.PrimStringToSymbol" "registry/core/prim_strings.go:197")
 ("string->utf8" "bytevector" ("string" "...integer") "github.com/aalpar/wile/registry/core.PrimStringToUtf8" "registry/core/prim_byte_vectors.go:241")
 ("string->vector" "vector" ("string" "...integer") "github.com/aalpar/wile/registry/core.PrimStringToVector" "registry/core/prim_vectors.go:252")
 ("string-append" "string" ("...string") "github.com/aalpar/wile/registry/core.PrimStringAppend" "registry/core/prim_strings.go:209")
 ("string-ci<=?" "boolean" ("string" "...string") "github.com/aalpar/wile/internal/extensions/all.addMoreStrings.makeStringCiComparePrimitive.func1" "internal/extensions/all/prim_strings.go:137")
 ("string-ci<?" "boolean" ("string" "...string") "github.com/aalpar/wile/internal/extensions/all.addMoreStrings.makeStringCiComparePrimitive.func1" "internal/extensions/all/prim_strings.go:137")
 ("string-ci=?" "boolean" ("string" "...string") "github.com/aalpar/wile/internal/extensions/all.addMoreStrings.makeStringCiComparePrimitive.func1" "internal/extensions/all/prim_strings.go:137")
 ("string-ci>=?" "boolean" ("string" "...string") "github.com/aalpar/wile/internal/extensions/all.addMoreStrings.makeStringCiComparePrimitive.func1" "internal/extensions/all/prim_strings.go:137")
 ("string-ci>?" "boolean" ("string" "...string") "github.com/aalpar/wile/internal/extensions/all.addMoreStrings.makeStringCiComparePrimitive.func1" "internal/extensions/all/prim_strings.go:137")
 ("string-copy" "string" ("string" "...integer") "github.com/aalpar/wile/registry/core.PrimStringCopy" "registry/core/prim_strings.go:267")
 ("string-copy!" "void" ("string" "integer" "string" "...integer") "github.com/aalpar/wile/internal/extensions/all.PrimStringCopyTo" "internal/extensions/all/prim_strings.go:51")
 ("string-downcase" "string" ("string") "github.com/aalpar/wile/internal/extensions/all.init.makeStringCaser.func30" "internal/extensions/all/prim_strings.go:145")
 ("string-fill!" "void" ("string" "character" "...integer") "github.com/aalpar/wile/internal/extensions/all.PrimStringFill" "internal/extensions/all/prim_strings.go:94")
 ("string-foldcase" "string" ("string") "github.com/aalpar/wile/internal/extensions/all.init.makeStringCaser.func31" "internal/extensions/all/prim_strings.go:145")
 ("string-length" "integer" ("string") "github.com/aalpar/wile/registry/core.PrimStringLength" "registry/core/prim_strings.go:76")
 ("string-ref" "character" ("string" "integer") "github.com/aalpar/wile/registry/core.PrimStringRef" "registry/core/prim_strings.go:87")
 ("string-set!" "void" ("string" "integer" "character") "github.com/aalpar/wile/registry/core.PrimStringSet" "registry/core/prim_strings.go:104")
 ("string-upcase" "string" ("string") "github.com/aalpar/wile/internal/extensions/all.init.makeStringCaser.func29" "internal/extensions/all/prim_strings.go:145")
 ("string<=?" "boolean" ("string" "...string") "github.com/aalpar/wile/registry/core.addStrings.makeStringComparePrimitive.func1" "registry/core/prim_strings.go:303")
 ("string<?" "boolean" ("string" "...string") "github.com/aalpar/wile/registry/core.addStrings.makeStringComparePrimitive.func1" "registry/core/prim_strings.go:303")
 ("string=?" "boolean" ("string" "...string") "github.com/aalpar/wile/registry/core.addStrings.makeStringComparePrimitive.func1" "registry/core/prim_strings.go:303")
 ("string>=?" "boolean" ("string" "...string") "github.com/aalpar/wile/registry/core.addStrings.makeStringComparePrimitive.func1" "registry/core/prim_strings.go:303")
 ("string>?" "boolean" ("string" "...string") "github.com/aalpar/wile/registry/core.addStrings.makeStringComparePrimitive.func1" "registry/core/prim_strings.go:303")
 ("string?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func37" "registry/helpers/type.go:26")
 ("substring" "string" ("string" "integer" "integer") "github.com/aalpar/wile/registry/core.PrimSubstring" "registry/core/prim_strings.go:240")
 ("symbol->string" "string" ("symbol") "github.com/aalpar/wile/registry/core.PrimSymbolToString" "registry/core/prim_strings.go:186")
 ("symbol?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func38" "registry/helpers/type.go:26")
 ("syntax->datum" "any" ("any") "github.com/aalpar/wile/registry/core.PrimSyntaxToDatum" "registry/core/prim_syntax.go:43")
 ("syntax->list" "any" ("any") "github.com/aalpar/wile/registry/core.PrimSyntaxToList" "registry/core/prim_syntax_loc.go:117")
 ("syntax-column" "any" ("any") "github.com/aalpar/wile/registry/core.PrimSyntaxColumn" "registry/core/prim_syntax_loc.go:78")
 ("syntax-line" "any" ("any") "github.com/aalpar/wile/registry/core.PrimSyntaxLine" "registry/core/prim_syntax_loc.go:66")
 ("syntax-local-identifier-as-binding" "any" ("any") "github.com/aalpar/wile/extensions/eval.PrimSyntaxLocalIdentifierAsBinding" "extensions/eval/prim_eval.go:683")
 ("syntax-local-introduce" "any" ("any") "github.com/aalpar/wile/extensions/eval.PrimSyntaxLocalIntroduce" "extensions/eval/prim_eval.go:633")
 ("syntax-local-value" "any" ("any") "github.com/aalpar/wile/extensions/eval.PrimSyntaxLocalValue" "extensions/eval/prim_eval.go:546")
 ("syntax-local-value/immediate" "any" ("any") "github.com/aalpar/wile/extensions/eval.PrimSyntaxLocalValueImmediate" "extensions/eval/prim_eval.go:595")
 ("syntax-position" "any" ("any") "github.com/aalpar/wile/registry/core.PrimSyntaxPosition" "registry/core/prim_syntax_loc.go:90")
 ("syntax-source" "any" ("any") "github.com/aalpar/wile/registry/core.PrimSyntaxSource" "registry/core/prim_syntax_loc.go:54")
 ("syntax-span" "any" ("any") "github.com/aalpar/wile/registry/core.PrimSyntaxSpan" "registry/core/prim_syntax_loc.go:102")
 ("system" "integer" ("string") "github.com/aalpar/wile/extensions/process.PrimSystem" "extensions/process/prim_process.go:32")
 ("tan" "number" ("number") "github.com/aalpar/wile/extensions/math.init.makeComplexPrimitive.func12" "extensions/math/prim_transcendental.go:33")
 ("textual-port?" "boolean" ("any") "github.com/aalpar/wile/internal/extensions/io.PrimTextualPortQ" "internal/extensions/io/prim_ports.go:263")
 ("thread-join!" "any" ("any" "...any") "github.com/aalpar/wile/extensions/threads.PrimThreadJoin" "extensions/threads/prim_threads.go:261")
 ("thread-name" "string" ("any") "github.com/aalpar/wile/extensions/threads.PrimThreadName" "extensions/threads/prim_threads.go:153")
 ("thread-sleep!" "void" ("any") "github.com/aalpar/wile/extensions/threads.PrimThreadSleep" "extensions/threads/prim_threads.go:220")
 ("thread-specific" "any" ("any") "github.com/aalpar/wile/extensions/threads.PrimThreadSpecific" "extensions/threads/prim_threads.go:164")
 ("thread-specific-set!" "void" ("any" "any") "github.com/aalpar/wile/extensions/threads.PrimThreadSpecificSet" "extensions/threads/prim_threads.go:180")
 ("thread-start!" "any" ("any") "github.com/aalpar/wile/extensions/threads.PrimThreadStart" "extensions/threads/prim_threads.go:194")
 ("thread-terminate!" "void" ("any") "github.com/aalpar/wile/extensions/threads.PrimThreadTerminate" "extensions/threads/prim_threads.go:248")
 ("thread-yield!" "void" () "github.com/aalpar/wile/extensions/threads.PrimThreadYield" "extensions/threads/prim_threads.go:211")
 ("thread?" "boolean" ("any") "github.com/aalpar/wile/extensions/threads.init.MakeTypePredicate.func5" "registry/helpers/type.go:26")
 ("time->seconds" "flonum" ("any") "github.com/aalpar/wile/extensions/threads.PrimTimeToSeconds" "extensions/threads/prim_threads.go:620")
 ("time?" "boolean" ("any") "github.com/aalpar/wile/extensions/threads.init.MakeTypePredicate.func8" "registry/helpers/type.go:26")
 ("truncate" "real" ("real") "github.com/aalpar/wile/extensions/math.init.makeRealNumberPrimitive.func6" "extensions/math/prim_rounding.go:36")
 ("truncate-quotient" "real" ("real" "real") "github.com/aalpar/wile/extensions/math.PrimTruncateQuotient" "extensions/math/prim_rounding.go:186")
 ("truncate-remainder" "real" ("real" "real") "github.com/aalpar/wile/extensions/math.PrimTruncateRemainder" "extensions/math/prim_rounding.go:193")
 ("truncate/" "" ("real" "real") "github.com/aalpar/wile/extensions/math.PrimTruncateDiv" "extensions/math/prim_rounding.go:179")
 ("u8-ready?" "boolean" ("...binary-input-port") "github.com/aalpar/wile/internal/extensions/io.PrimU8ReadyQ" "internal/extensions/io/prim_binary.go:88")
 ("ucs-range->char-set" "" () "github.com/aalpar/wile/extensions/charsets.primUcsRangeToCharSet" "extensions/charsets/charsets.go:143")
 ("unbox" "any" ("any") "github.com/aalpar/wile/registry/core.PrimUnbox" "registry/core/prim_boxes.go:40")
 ("utf8->string" "string" ("bytevector" "...integer") "github.com/aalpar/wile/registry/core.PrimUtf8ToString" "registry/core/prim_byte_vectors.go:209")
 ("values" "any" ("...any") "github.com/aalpar/wile/registry/core.PrimValues" "registry/core/prim_control.go:291")
 ("vector" "vector" ("...any") "github.com/aalpar/wile/registry/core.PrimVector" "registry/core/prim_vectors.go:51")
 ("vector->list" "list" ("vector" "...integer") "github.com/aalpar/wile/registry/core.PrimVectorToList" "registry/core/prim_vectors.go:84")
 ("vector->string" "string" ("vector" "...integer") "github.com/aalpar/wile/registry/core.PrimVectorToString" "registry/core/prim_vectors.go:223")
 ("vector-append" "vector" ("...vector") "github.com/aalpar/wile/registry/core.PrimVectorAppend" "registry/core/prim_vectors.go:198")
 ("vector-copy" "vector" ("vector" "...integer") "github.com/aalpar/wile/registry/core.PrimVectorCopy" "registry/core/prim_vectors.go:108")
 ("vector-copy!" "void" ("vector" "integer" "...vector") "github.com/aalpar/wile/registry/core.PrimVectorCopyTo" "registry/core/prim_vectors.go:131")
 ("vector-fill!" "void" ("vector" "any" "...integer") "github.com/aalpar/wile/registry/core.PrimVectorFill" "registry/core/prim_vectors.go:174")
 ("vector-length" "integer" ("vector") "github.com/aalpar/wile/registry/core.PrimVectorLength" "registry/core/prim_vectors.go:57")
 ("vector-ref" "any" ("vector" "integer") "github.com/aalpar/wile/registry/core.PrimVectorRef" "registry/core/prim_vectors.go:64")
 ("vector-set!" "void" ("vector" "integer" "any") "github.com/aalpar/wile/registry/core.PrimVectorSet" "registry/core/prim_vectors.go:73")
 ("vector?" "boolean" ("any") "github.com/aalpar/wile/registry/core.init.MakeTypePredicate.func39" "registry/helpers/type.go:26")
 ("void?" "boolean" ("any") "github.com/aalpar/wile/registry/core.PrimVoidQ" "registry/core/prim_predicates.go:90")
 ("wait-group-add!" "void" ("any" "integer") "github.com/aalpar/wile/extensions/gointerop.PrimWaitGroupAdd" "extensions/gointerop/prim_gointerop.go:227")
 ("wait-group-done!" "void" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimWaitGroupDone" "extensions/gointerop/prim_gointerop.go:245")
 ("wait-group-wait!" "void" ("any") "github.com/aalpar/wile/extensions/gointerop.PrimWaitGroupWait" "extensions/gointerop/prim_gointerop.go:258")
 ("wait-group?" "boolean" ("any") "github.com/aalpar/wile/extensions/gointerop.init.MakeTypePredicate.func7" "registry/helpers/type.go:26")
 ("with-exception-handler" "any" ("procedure" "procedure") "github.com/aalpar/wile/registry/core.PrimWithExceptionHandler" "registry/core/prim_exceptions.go:30")
 ("with-timeout" "any" ("integer" "procedure" "procedure") "github.com/aalpar/wile/registry/core.PrimWithTimeout" "registry/core/prim_timer.go:38")
 ("write" "void" ("any" "...textual-output-port") "github.com/aalpar/wile/internal/extensions/io.PrimWrite" "internal/extensions/io/prim_write.go:48")
 ("write-bytevector" "void" ("bytevector" "...binary-output-port") "github.com/aalpar/wile/internal/extensions/io.PrimWriteBytevector" "internal/extensions/io/prim_binary.go:235")
 ("write-char" "void" ("character" "...textual-output-port") "github.com/aalpar/wile/internal/extensions/io.PrimWriteChar" "internal/extensions/io/prim_write.go:64")
 ("write-shared" "void" ("any" "...textual-output-port") "github.com/aalpar/wile/internal/extensions/io.PrimWriteShared" "internal/extensions/io/prim_write.go:138")
 ("write-simple" "void" ("any" "...textual-output-port") "github.com/aalpar/wile/internal/extensions/io.PrimWriteSimple" "internal/extensions/io/prim_write.go:118")
 ("write-string" "void" ("string" "...textual-output-port") "github.com/aalpar/wile/internal/extensions/io.PrimWriteString" "internal/extensions/io/prim_write.go:155")
 ("write-u8" "void" ("integer" "...binary-output-port") "github.com/aalpar/wile/internal/extensions/io.PrimWriteU8" "internal/extensions/io/prim_binary.go:98"))
