;; stdlib/lib/srfi/14/iteration.scm
;;
;; Iteration / query layer built on %char-set-walk-ranges. Per design §6.C:
;; this layer plus the helper avoids ~140k FFI round-trips for
;; named-set walks (Phase 4).

(define (char-set-fold proc init cs)
  (%char-set-walk-ranges cs proc init))

(define (char-set-for-each proc cs)
  (%char-set-walk-ranges cs (lambda (ch _) (proc ch) #f) #f)
  (if #f #f))

(define (char-set-map proc cs)
  ;; proc :: char → char. Result is a char-set of the mapped chars.
  (list->char-set
    (%char-set-walk-ranges cs (lambda (ch acc) (cons (proc ch) acc)) '())))

(define char-set-filter
  (case-lambda
    ((pred cs) (char-set-filter pred cs (char-set)))
    ((pred cs base)
     (list->char-set
       (%char-set-walk-ranges cs
         (lambda (ch acc) (if (pred ch) (cons ch acc) acc))
         '())
       base))))

(define char-set-filter! char-set-filter)

(define (char-set-count pred cs)
  (%char-set-walk-ranges cs
    (lambda (ch acc) (if (pred ch) (+ acc 1) acc))
    0))

;; char-set-every and char-set-any short-circuit on first failure/success.
;; %char-set-walk-ranges doesn't natively support early exit, so we use
;; call-with-current-continuation to bail out.
(define (char-set-every pred cs)
  (call-with-current-continuation
    (lambda (return)
      (%char-set-walk-ranges cs
        (lambda (ch _)
          (if (pred ch) #t (return #f)))
        #t))))

(define (char-set-any pred cs)
  (call-with-current-continuation
    (lambda (return)
      (%char-set-walk-ranges cs
        (lambda (ch _)
          (if (pred ch) (return #t) #f))
        #f))))

;; SRFI-14 char-set-unfold: build a char-set by repeatedly applying mapper
;; to seeds generated by successor, stopping when stop? returns true.
(define char-set-unfold
  (case-lambda
    ((stop? mapper successor seed)
     (char-set-unfold stop? mapper successor seed (char-set)))
    ((stop? mapper successor seed base)
     (let loop ((seed seed) (acc '()))
       (if (stop? seed)
           (list->char-set acc base)
           (loop (successor seed) (cons (mapper seed) acc)))))))

(define char-set-unfold! char-set-unfold)
