;; ================================================================
;; Chapter 07 -- Group actions: orbits, stabilizers, Burnside
;;
;; What you will learn:
;;   - Preset groups shipped by (wile algebra group): trivial, cyclic,
;;     symmetric, product.
;;   - How `<group-action>` wraps a group + a set + an act function.
;;   - Orbit (BFS or enumerate) and stabilizer (filter).
;;   - Fixed points and Burnside's lemma for orbit counting.
;;   - Canonical orbit representatives with a user-supplied total order.
;;
;; Prerequisites: chapter 02 (groups as records).
;; Sub-libraries used: (wile algebra group).
;; ================================================================

(import (scheme base) (scheme write)
        (srfi 132)                ; sort (not in scheme base)
        (wile algebra group))
(include "../lib/check.scm")

;; ----------------------------------------------------------------
;; Part 1: Preset groups.
;; ----------------------------------------------------------------

(define E   (trivial-group))
(define Z5  (cyclic-group 5))
(define S3  (symmetric-group 3))
(define C2xC3 (product-group (cyclic-group 2) (cyclic-group 3)))

(check= (group-order E)       1    "|E| = 1")
(check= (group-order Z5)      5    "|Z_5| = 5")
(check= (group-order S3)      6    "|S_3| = 3! = 6")
(check= (group-order C2xC3)   6    "|Z_2 × Z_3| = 6")

(check-true (finite-group? Z5)                  "Z_5 is a finite group")
(check-true (finitely-generated-group? Z5)      "Z_5 is finitely generated")

;; Group operations on cyclic group Z_5.
(check= (group-op       Z5 2 4)  1   "2 + 4 mod 5 = 1")
(check= (group-identity Z5)      0   "identity is 0")
(check= (group-inverse  Z5 2)    3   "inverse of 2 is 3 (2+3=5=0)")

;; ----------------------------------------------------------------
;; Part 2: enumerate-finite-group + subgroup-generated.
;;
;; enumerate-finite-group produces the element set by BFS from the
;; generators. Useful when you have a finitely-generated group and
;; want to promote it to finite.
;; ----------------------------------------------------------------

;; enumerate-finite-group returns a group record (idempotent when the
;; group already has elements). Use group-elements on the result.
(check= (length (group-elements (enumerate-finite-group Z5)))
        5
        "enumerate Z_5 exposes 5 elements")

;; `subgroup-generated G gens` returns the smallest subgroup containing
;; `gens` (as a group record). In Z_6 the subgroup generated by 2 is
;; {0, 2, 4}.
(define Z6 (cyclic-group 6))
(define H-in-Z6 (subgroup-generated Z6 '(2)))
(check-true (group? H-in-Z6)
            "subgroup generated by {2} in Z_6 is a group")
(check= (group-order H-in-Z6)  3
        "|<2>| = 3 in Z_6")

;; ----------------------------------------------------------------
;; Part 3: Preset actions.
;;
;; `permutation-action S_n n` is S_n acting on {0..n-1} by application.
;; `regular-action G` is G acting on itself by left multiplication.
;; `conjugation-action G` is G acting on itself by conjugation.
;; `trivial-action G set?` is G acting as the identity on a given set.
;; ----------------------------------------------------------------

(define nat-S3 (permutation-action S3 3))
(check-true (group-action? nat-S3)             "nat-S3 is a group action")

;; S_3 natural action on {0, 1, 2}: permutation vector #(2 0 1) sends
;; 0 -> 2, 1 -> 0, 2 -> 1.
(check= (group-action-act nat-S3 #(2 0 1) 0)  2   "permutation action: 0 -> 2")
(check= (group-action-act nat-S3 #(2 0 1) 1)  0   "permutation action: 1 -> 0")

;; Regular action: each group element acts by multiplication.
(define reg-Z5 (regular-action Z5))
(check= (group-action-act reg-Z5 3 2)  0   "3 + 2 mod 5 = 0 (regular action)")

;; ----------------------------------------------------------------
;; Part 4: Orbits.
;;
;; An orbit of X under the action is all points reachable by applying
;; group elements. For the natural S_3 action on {0, 1, 2}, every point
;; has orbit {0, 1, 2} (the action is transitive).
;; ----------------------------------------------------------------

(check= (sort < (orbit nat-S3 0))  '(0 1 2)
        "S_3 acts transitively on {0,1,2}")
(check= (length (orbit nat-S3 1))  3
        "every point has orbit of size 3")

;; The regular action of any group is transitive on the group itself.
(check= (length (orbit reg-Z5 0))  5   "regular action of Z_5: transitive")

;; ----------------------------------------------------------------
;; Part 5: Stabilizers.
;;
;; Stab_G(x) = { g in G : g·x = x }.
;; For natural S_3 on {0,1,2}, Stab(0) consists of permutations fixing 0,
;; i.e., permutations of {1,2}. There are 2 (identity and the (1 2)
;; transposition), so |Stab| = 2 and by orbit-stabilizer |orbit| · |stab| = |G|:
;; 3 · 2 = 6 = |S_3|.
;; ----------------------------------------------------------------

(check= (length (stabilizer nat-S3 0))  2
        "|Stab_{S_3}(0)| = 2")
(check= (* (length (orbit nat-S3 0)) (length (stabilizer nat-S3 0)))
        (group-order S3)
        "orbit-stabilizer: |orbit| * |stab| = |G|")

;; ----------------------------------------------------------------
;; Part 6: Fixed points.
;;
;; fixed-points action g X returns points of X that g fixes.
;; The identity of S_3 fixes all of {0,1,2}. The transposition
;; #(1 0 2) fixes only 2.
;; ----------------------------------------------------------------

(check= (length (fixed-points nat-S3 #(0 1 2) '(0 1 2)))  3
        "identity fixes everything")

(check= (fixed-points nat-S3 #(1 0 2) '(0 1 2))  '(2)
        "transposition (0 1) fixes 2 only")

(check= (fixed-points nat-S3 #(1 2 0) '(0 1 2))  '()
        "3-cycle fixes nothing")

;; ----------------------------------------------------------------
;; Part 7: Burnside's lemma.
;;
;; Classical application: count k-bead necklaces with c colors under
;; rotation (= action of C_k on c^k colorings).
;;
;; For c = 2 colors, k = 4 beads:
;;   - identity fixes all 2^4 = 16 colorings
;;   - 90° rotation fixes 2 (monochromatic)
;;   - 180° rotation fixes 4 (alternating and monochromatic)
;;   - 270° rotation fixes 2 (monochromatic)
;; Average: (16 + 2 + 4 + 2) / 4 = 6 distinct necklaces.
;; ----------------------------------------------------------------

;; Build the rotation action: Z_4 rotating length-4 lists.
(define (rotate-n n lst)
  ;; Rotate list left by n positions.
  (if (zero? n)
      lst
      (rotate-n (- n 1) (append (cdr lst) (list (car lst))))))

(define Z4 (cyclic-group 4))

(define necklace-action
  (make-group-action
    Z4
    (lambda (c) (and (list? c) (= (length c) 4)))
    rotate-n))

;; Enumerate all 16 2-colorings of a length-4 string.
(define (colorings n)
  (if (zero? n)
      '(())
      (let ((tails (colorings (- n 1))))
        (append
          (map (lambda (t) (cons 0 t)) tails)
          (map (lambda (t) (cons 1 t)) tails)))))

(define two-of-four (colorings 4))
(check= (length two-of-four) 16   "2^4 = 16 colorings")

(check= (burnside-count necklace-action two-of-four)
        6
        "6 distinct 4-bead 2-color necklaces under rotation")

;; Sanity: 2-bead 2-color necklaces under C_2 rotation = 3.
(define Z2 (cyclic-group 2))
(define two-necklace
  (make-group-action
    Z2
    (lambda (c) (and (list? c) (= (length c) 2)))
    rotate-n))

(check= (burnside-count two-necklace (colorings 2))
        3
        "3 distinct 2-bead 2-color necklaces (00, 01~10, 11)")

;; ----------------------------------------------------------------
;; Part 8: Conjugation and conjugacy classes.
;;
;; Orbits of the conjugation action on G = conjugacy classes of G.
;; S_3 has three conjugacy classes: identity, transpositions (3 of them),
;; 3-cycles (2 of them). Sum to 1 + 3 + 2 = 6 = |S_3|.
;; ----------------------------------------------------------------

(define conj-S3 (conjugation-action S3))
(check-true (group-action? conj-S3)   "conjugation action built")

;; Orbit of identity is just {identity}.
(check= (length (orbit conj-S3 #(0 1 2)))  1
        "identity has conjugacy class of size 1")

;; Orbit of a transposition has 3 elements (all transpositions).
(check= (length (orbit conj-S3 #(1 0 2)))  3
        "transpositions form conjugacy class of size 3")

;; Orbit of a 3-cycle has 2 elements.
(check= (length (orbit conj-S3 #(1 2 0)))  2
        "3-cycles form conjugacy class of size 2")

;; ----------------------------------------------------------------
;; Part 9: orbit-representative with a user-supplied total order.
;;
;; Picks the LESS?-minimum element of an orbit deterministically. The
;; result only depends on the action and the ordering -- the starting
;; point x is arbitrary within its orbit.
;; ----------------------------------------------------------------

;; Pick the lex-smallest vector in an S_3 orbit.
(define (vec<? a b)
  (let loop ((i 0))
    (cond
      ((= i 3) #f)
      ((< (vector-ref a i) (vector-ref b i)) #t)
      ((> (vector-ref a i) (vector-ref b i)) #f)
      (else (loop (+ i 1))))))

(define conj-rep-from-transposition
  (orbit-representative conj-S3 #(1 0 2) vec<?))
(define conj-rep-from-other-transposition
  (orbit-representative conj-S3 #(0 2 1) vec<?))

;; Both starting points are in the same conjugacy class, so the
;; representatives agree.
(check= conj-rep-from-transposition
        conj-rep-from-other-transposition
        "same conjugacy class => same representative")

(display "chapter 07 complete") (newline)
