#!/usr/bin/env sage
"""
Validate Wile algebra libraries against SageMath.

Usage:
    sage tools/sage/verify_algebra.sage                    # both phases, live
    sage tools/sage/verify_algebra.sage --phase structures # phase 1 only
    sage tools/sage/verify_algebra.sage --phase rewriting  # phase 2 only
    sage tools/sage/verify_algebra.sage --snapshot         # write .scm files
    sage tools/sage/verify_algebra.sage --seed 123         # custom RNG seed
"""

from sage.all import *
import argparse
import subprocess
import sys
import os
import random
from datetime import date
from itertools import combinations, permutations
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

WILE_BIN = os.environ.get("WILE", "./dist/darwin/arm64/wile")
SNAPSHOT_DIR = Path("test/wile/sage-generated")
DEFAULT_SEED = 42
SAGE_VERSION = version()

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(description="Sage oracle for Wile algebra validation")
    p.add_argument("--phase", choices=["structures", "rewriting"],
                   help="Run only one phase (default: both)")
    p.add_argument("--snapshot", action="store_true",
                   help="Write static .scm test files")
    p.add_argument("--seed", type=int, default=DEFAULT_SEED,
                   help=f"RNG seed (default: {DEFAULT_SEED})")
    p.add_argument("--verbose", "-v", action="store_true",
                   help="Print each test case as it runs")
    return p.parse_args()

# ---------------------------------------------------------------------------
# Wile subprocess
# ---------------------------------------------------------------------------

def run_wile(scheme_code):
    """Run Scheme code in Wile subprocess, return stdout string."""
    try:
        result = subprocess.run(
            [WILE_BIN, "-e", scheme_code],
            capture_output=True, text=True, timeout=30,
        )
    except subprocess.TimeoutExpired:
        raise RuntimeError(
            f"Wile timed out after 30s. Code (first 200 chars): {scheme_code[:200]}"
        )
    if result.returncode != 0:
        raise RuntimeError(f"Wile error (exit {result.returncode}): {result.stderr.strip()}")
    return result.stdout.strip()

# ---------------------------------------------------------------------------
# Snapshot writer
# ---------------------------------------------------------------------------

def scm_header(name, seed, filename, oracle_source):
    """Return the standard header comment for generated .scm files."""
    return (
        f";;; {filename} — Generated by Sage oracle\n"
        f";;; Oracle: {SAGE_VERSION}\n"
        f";;; Oracle source: {oracle_source}\n"
        f";;; Date: {date.today().isoformat()}\n"
        f";;; Seed: {seed}\n"
        f";;; DO NOT EDIT — regenerate with:\n"
        f";;;   make sage-snapshot\n"
    )

def write_snapshot(filename, test_name, imports, body, seed, oracle_source="Sage-builtin"):
    """Write a complete .scm test file to SNAPSHOT_DIR."""
    path = SNAPSHOT_DIR / filename
    with open(path, "w") as f:
        f.write(scm_header(test_name, seed, filename, oracle_source))
        f.write(f"\n(import (scheme base)\n        (chibi test)\n")
        for i, imp in enumerate(imports):
            if i == len(imports) - 1:
                f.write(f"        {imp})\n")
            else:
                f.write(f"        {imp}\n")
        f.write(f"\n(test-begin \"{test_name}\")\n\n")
        f.write(body)
        f.write(f"\n(test-end)\n(test-exit)\n")
    print(f"  Wrote {path}")

# ---------------------------------------------------------------------------
# Shared value-formatting + dual-mode driver for new structure validators
# ---------------------------------------------------------------------------

def to_wile_display(v):
    """Format a Python value as the string Wile prints via (display v).
    Supported: bool, int, str (a quoted symbol token like 'neg-inf'),
    ('num', token) for a bare self-evaluating number literal like 1/3,
    list (Scheme list), and ('pair', (lo, hi)) for a cons pair."""
    if isinstance(v, bool):
        return "#t" if v else "#f"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, str):
        return v
    if isinstance(v, tuple) and len(v) == 2 and v[0] == "num":
        return v[1]
    if isinstance(v, tuple) and len(v) == 2 and v[0] == "pair":
        lo, hi = v[1]
        return f"({to_wile_display(lo)} . {to_wile_display(hi)})"
    if isinstance(v, list):
        return "(" + " ".join(to_wile_display(x) for x in v) + ")"
    raise ValueError(f"to_wile_display: cannot format {v!r}")

def to_wile_test_literal(v):
    """Format a Python value as the EXPECTED arg of (test EXPECTED expr).
    Scalars (bool, int) and number literals (('num', token), e.g. 1/3) are
    bare and self-evaluating; compound values (lists, pairs, symbols) are
    quoted so they compare by equal? against Wile's result."""
    if isinstance(v, bool):
        return "#t" if v else "#f"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, tuple) and len(v) == 2 and v[0] == "num":
        return v[1]
    return "'" + to_wile_display(v)

def run_live_check(imports, preamble, cases):
    """Run `cases` under Wile and compare each result against its expected
    value. Returns the failure count (0 = all pass) and prints per-case FAIL
    lines plus an OK/FAILED summary."""
    imp = " ".join(f"(import {i})" for i in imports)
    disp = " ".join(f"(display {e}) (display #\\newline)" for e, _ in cases)
    output = run_wile(f"{imp} {preamble} (begin {disp})")
    results = output.split("\n") if output else []
    if len(results) != len(cases):
        print(f"\n    ERROR: expected {len(cases)} lines, got {len(results)}")
        return len(cases)
    failures = 0
    for i, (e, expected) in enumerate(cases):
        want = to_wile_display(expected)
        got = results[i].strip()
        if got != want:
            failures += 1
            print(f"\n    FAIL: {e}\n      got {got!r}, expected {want!r}")
    print(f"OK ({len(cases)} cases)" if failures == 0
          else f"\n    {failures}/{len(cases)} FAILED")
    return failures

def check_or_snapshot(args, filename, test_name, imports, cases, oracle_source,
                      preamble=""):
    """cases: list of (expr_str, expected_python_value). Each expr is a
    self-contained Scheme expression evaluated under `imports`.
    `preamble`: optional Scheme definitions injected before the cases in both
    the live run and the snapshot (e.g. helper procedures a validator needs).

    The live Wile cross-check runs in BOTH modes: in check mode it is the
    check; in snapshot mode it guards the fixture so a Wile/Sage disagreement
    is never baked into a committed snapshot. This mirrors the rewriting
    validators' "not writing snapshot due to N failures" guard."""
    failures = run_live_check(imports, preamble, cases)
    if args.snapshot:
        if failures > 0:
            print(f"    WARNING: not writing snapshot due to {failures} failures")
            return failures
        body = (preamble + "\n" if preamble else "") + "".join(
            f"(test {to_wile_test_literal(exp)} {e})\n" for e, exp in cases)
        write_snapshot(filename, test_name, imports, body, args.seed, oracle_source)
    return failures

# ---------------------------------------------------------------------------
# Phase 1: Structure validators
# ---------------------------------------------------------------------------

def validate_integer_ring(args):
    """Validate Wile's (integer-ring) against Sage's ZZ."""
    print("  integer-ring...", end=" ", flush=True)
    samples = list(range(-10, 11))
    cases = []
    for a in samples:
        for b in samples:
            cases.append((f"(ring-plus R {a} {b})", int(ZZ(a) + ZZ(b))))
            cases.append((f"(ring-times R {a} {b})", int(ZZ(a) * ZZ(b))))
            cases.append((f"(ring-minus R {a} {b})", int(ZZ(a) - ZZ(b))))
        cases.append((f"(ring-negate R {a})", int(-ZZ(a))))
    return check_or_snapshot(
        args,
        "sage-structures-integer-ring-test.scm",
        "sage-structures-integer-ring",
        ["(wile algebra)"],
        cases,
        "Sage-builtin",
        preamble="(define R (integer-ring))",
    )


def format_rational_for_wile(q):
    """Format a Sage rational for Wile: integers as '3', fractions as '1/3'."""
    if q.denominator() == 1:
        return str(q.numerator())
    return f"{q.numerator()}/{q.denominator()}"


def format_rational_expected(q):
    """Format expected Sage rational to match Wile's display output."""
    if q.denominator() == 1:
        return str(int(q.numerator()))
    return f"{int(q.numerator())}/{int(q.denominator())}"


def validate_rational_field(args):
    """Validate Wile's (rational-field) against Sage's QQ.

    Expected values are exact rationals asserted directly as self-evaluating
    number literals (the ('num', ...) sentinel), e.g. (test 1/3 (field-plus ...)),
    so the fixture compares by equal? rather than string-matching display output."""
    print("  rational-field...", end=" ", flush=True)
    # Sample values: QQ(n)/QQ(d) for n in -3..3, d in 1..3, deduplicated
    sample_set = set()
    for n in range(-3, 4):
        for d in range(1, 4):
            sample_set.add(QQ(n) / QQ(d))
    samples = sorted(sample_set)

    def lit(q):
        return ("num", format_rational_expected(q))

    cases = []
    for a in samples:
        wa = format_rational_for_wile(a)
        for b in samples:
            wb = format_rational_for_wile(b)
            cases.append((f"(field-plus F {wa} {wb})", lit(a + b)))
            cases.append((f"(field-times F {wa} {wb})", lit(a * b)))
            if b != 0:
                cases.append((f"(field-divide F {wa} {wb})", lit(a / b)))
        cases.append((f"(field-negate F {wa})", lit(-a)))
        if a != 0:
            cases.append((f"(field-reciprocal F {wa})", lit(1 / a)))
    return check_or_snapshot(
        args,
        "sage-structures-rational-field-test.scm",
        "sage-structures-rational-field",
        ["(wile algebra)"],
        cases,
        "Sage-builtin",
        preamble="(define F (rational-field))",
    )


def validate_modular_ring(args):
    """Validate Wile's (modular-ring N) against Sage's Zmod(N).

    One ring per modulus is bound in the preamble (R2, R3, ...) so all moduli's
    cases share a single flat (test ...) fixture."""
    print("  modular-ring...", end=" ", flush=True)
    moduli = [2, 3, 5, 7, 12]
    preamble = "\n".join(f"(define R{N} (modular-ring {N}))" for N in moduli)
    cases = []
    for N in moduli:
        R_sage = Zmod(N)
        for a in range(N):
            for b in range(N):
                cases.append((f"(ring-plus R{N} {a} {b})", int(R_sage(a) + R_sage(b))))
                cases.append((f"(ring-times R{N} {a} {b})", int(R_sage(a) * R_sage(b))))
                cases.append((f"(ring-minus R{N} {a} {b})", int(R_sage(a) - R_sage(b))))
            cases.append((f"(ring-negate R{N} {a})", int(-R_sage(a))))
    return check_or_snapshot(
        args,
        "sage-structures-modular-ring-test.scm",
        "sage-structures-modular-ring",
        ["(wile algebra)"],
        cases,
        "Sage-builtin",
        preamble=preamble,
    )


def validate_powerset_lattice(args):
    """Validate Wile's (powerset-lattice) against Python set operations.

    Intentionally NOT routed through check_or_snapshot (TODO #215 exempts it):
    Wile's lattice-join/meet return sets in input-order, not a canonical order,
    so the live check compares the full set (order-insensitive, via parse_set)
    while the snapshot asserts only cardinality (length) to stay robust against
    that ordering. check_or_snapshot uses one expression for both modes and
    cannot express that divergence without weakening the live set-membership
    check. The other five structure validators have scalar results and migrate
    cleanly; this one keeps its hand-rolled dual mode."""
    print("  powerset-lattice...", end=" ", flush=True)
    universe = [1, 2, 3]
    subsets = []
    for r in range(len(universe) + 1):
        for s in combinations(universe, r):
            subsets.append(frozenset(s))
    cases = []
    failures = 0

    for a in subsets:
        for b in subsets:
            cases.append((a, b, "join", a | b))
            cases.append((a, b, "meet", a & b))
            cases.append((a, b, "leq?", a <= b))

    def fmt_set(s):
        if not s:
            return "'()"
        return "'" + "(" + " ".join(str(x) for x in sorted(s)) + ")"

    def parse_set(s):
        s = s.strip()
        if s == "()" or s == "":
            return frozenset()
        if s.startswith("(") and s.endswith(")"):
            s = s[1:-1]
        if not s.strip():
            return frozenset()
        return frozenset(int(x) for x in s.split())

    if not args.snapshot:
        scheme = "(import (wile algebra)) (let ((L (powerset-lattice '(1 2 3)))) "
        tests = []
        for a, b, op, expected in cases:
            if op == "join":
                tests.append(
                    f"(write (lattice-join L {fmt_set(a)} {fmt_set(b)}))"
                    f" (display #\\newline)")
            elif op == "meet":
                tests.append(
                    f"(write (lattice-meet L {fmt_set(a)} {fmt_set(b)}))"
                    f" (display #\\newline)")
            elif op == "leq?":
                tests.append(
                    f"(display (lattice-leq? L {fmt_set(a)} {fmt_set(b)}))"
                    f" (display #\\newline)")
        scheme += " ".join(tests) + ")"
        output = run_wile(scheme)
        results = output.strip().split("\n")
        if len(results) != len(cases):
            print(f"\n    ERROR: expected {len(cases)} output lines, got {len(results)}")
            return len(cases)
        for i, (a, b, op, expected) in enumerate(cases):
            if op == "leq?":
                expected_str = "#t" if expected else "#f"
                if results[i] != expected_str:
                    failures += 1
                    print(f"\n    FAIL: (lattice-leq? L {fmt_set(a)}"
                          f" {fmt_set(b)}) = {results[i]},"
                          f" expected {expected_str}")
            else:
                if parse_set(results[i]) != expected:
                    failures += 1
                    wile_op = ("lattice-join" if op == "join"
                               else "lattice-meet")
                    print(f"\n    FAIL: ({wile_op} L {fmt_set(a)}"
                          f" {fmt_set(b)}) = {results[i]},"
                          f" expected {sorted(expected)}")
        if failures == 0:
            print(f"OK ({len(cases)} cases)")
        else:
            print(f"\n    {failures}/{len(cases)} FAILED")
    else:
        body = "(let ((L (powerset-lattice '(1 2 3))))\n"
        for a, b, op, expected in cases:
            if op == "leq?":
                exp = "#t" if expected else "#f"
                body += (f"  (test {exp}"
                         f" (lattice-leq? L {fmt_set(a)} {fmt_set(b)}))\n")
            elif op == "join":
                body += (f"  (test {len(expected)}"
                         f" (length (lattice-join L"
                         f" {fmt_set(a)} {fmt_set(b)})))\n")
            elif op == "meet":
                body += (f"  (test {len(expected)}"
                         f" (length (lattice-meet L"
                         f" {fmt_set(a)} {fmt_set(b)})))\n")
        body += ")\n"
        write_snapshot(
            "sage-structures-powerset-lattice-test.scm",
            "sage-structures-powerset-lattice",
            ["(wile algebra)"],
            body,
            args.seed,
        )

    return failures


def validate_boolean_semiring(args):
    """Validate Wile's (boolean-semiring) against truth tables."""
    print("  boolean-semiring...", end=" ", flush=True)
    def tf(v):
        return "#t" if v else "#f"
    cases = []
    for a in [False, True]:
        for b in [False, True]:
            cases.append((f"(semiring-plus S {tf(a)} {tf(b)})", a or b))
            cases.append((f"(semiring-times S {tf(a)} {tf(b)})", a and b))
    return check_or_snapshot(
        args,
        "sage-structures-boolean-semiring-test.scm",
        "sage-structures-boolean-semiring",
        ["(wile algebra)"],
        cases,
        "Sage-builtin",
        preamble="(define S (boolean-semiring))",
    )


def validate_tropical_semiring(args):
    """Validate Wile's (tropical-semiring) against Sage's TropicalSemiring.

    Samples 0..10 stay finite (away from the tropical zero, +inf), so every
    result is an integer."""
    print("  tropical-semiring...", end=" ", flush=True)
    T = TropicalSemiring(ZZ)
    samples = list(range(0, 11))
    cases = []
    for a in samples:
        for b in samples:
            cases.append((f"(semiring-plus S {a} {b})", int((T(a) + T(b)).lift())))   # min
            cases.append((f"(semiring-times S {a} {b})", int((T(a) * T(b)).lift())))  # +
    return check_or_snapshot(
        args,
        "sage-structures-tropical-semiring-test.scm",
        "sage-structures-tropical-semiring",
        ["(wile algebra)"],
        cases,
        "Sage-builtin",
        preamble="(define S (tropical-semiring))",
    )


def validate_polynomial(args):
    """Validate (wile algebra) polynomials against Sage PolynomialRing."""
    print("  polynomial...", end=" ", flush=True)
    Rz = PolynomialRing(ZZ, 'x')
    Rq = PolynomialRing(QQ, 'x')
    coeff_samples = [[], [5], [1, 1], [2, -1], [1, 2, 3], [0, 0, 1], [-1, 0, 1]]

    def zlit(cs):
        return "'(" + " ".join(str(int(c)) for c in cs) + ")"

    def zcoeffs(p):
        return [int(c) for c in p.list()]

    def qcoeffs(p):
        return [format_rational_for_wile(QQ(c)) for c in p.list()]

    cases = []
    P = "(make-poly (integer-ring) "
    for ca in coeff_samples:
        pa = Rz(ca)
        cases.append((f"(poly-coeffs (poly-negate {P}{zlit(ca)})))", zcoeffs(-pa)))
        cases.append((f"(poly-coeffs (poly-derivative {P}{zlit(ca)})))",
                      zcoeffs(pa.derivative())))
        cases.append((f"(poly-degree {P}{zlit(ca)}))", int(pa.degree())))
        cases.append((f"(poly-leading-coeff {P}{zlit(ca)}))",
                      int(pa.list()[-1]) if pa != 0 else int(0)))
        for x in [-2, -1, 0, 1, 2, 3]:
            cases.append((f"(poly-eval {P}{zlit(ca)}) {x})", int(pa(x))))
        for cb in coeff_samples:
            pb = Rz(cb)
            cases.append((f"(poly-coeffs (poly-plus {P}{zlit(ca)}) {P}{zlit(cb)})))",
                          zcoeffs(pa + pb)))
            cases.append((f"(poly-coeffs (poly-minus {P}{zlit(ca)}) {P}{zlit(cb)})))",
                          zcoeffs(pa - pb)))
            cases.append((f"(poly-coeffs (poly-times {P}{zlit(ca)}) {P}{zlit(cb)})))",
                          zcoeffs(pa * pb)))

    # gcd over QQ (Wile requires a field; Sage gcd over QQ is monic — matches).
    Q = "(make-poly (field->ring (rational-field)) "
    gcd_pairs = [([-1, 0, 1], [-1, 1]), ([1, 2, 1], [1, 1]), ([1, 0, 0, 1], [1, 1])]
    for ca, cb in gcd_pairs:
        g = (Rq(ca).gcd(Rq(cb))).monic()
        cases.append((f"(poly-coeffs (poly-gcd {Q}{zlit(ca)}) {Q}{zlit(cb)}) (rational-field)))",
                      qcoeffs(g)))

    return check_or_snapshot(
        args, "sage-structures-polynomial-test.scm",
        "sage-structures-polynomial", ["(wile algebra)"], cases, "Sage-builtin")


def validate_semiring_matrix(args):
    """Validate (wile algebra) semiring matrices. counting -> Sage Matrix(ZZ);
    tropical/boolean -> in-harness Python reference."""
    print("  semiring-matrix...", end=" ", flush=True)
    cases = []

    def rows_lit(rows, fmt):
        return "'(" + " ".join("(" + " ".join(fmt(x) for x in r) + ")"
                               for r in rows) + ")"

    # --- counting semiring: Sage Matrix(ZZ) ---
    Cnt = "(counting-semiring)"
    int_mats = [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[1, 1], [0, 1]], [[2, 0], [1, 3]]]
    def ilit(rows): return rows_lit(rows, lambda x: str(int(x)))
    for A in int_mats:
        MA = Matrix(ZZ, A)
        cases.append((
            f"(let ((S {Cnt})) (semiring-matrix-permanent (semiring-matrix-from-rows S {ilit(A)})))",
            int(MA.permanent())))
        for k in [0, 1, 2, 3]:
            cases.append((
                f"(let ((S {Cnt})) (semiring-matrix->rows (semiring-matrix-power (semiring-matrix-from-rows S {ilit(A)}) {k})))",
                [[int(x) for x in row] for row in (MA ** k)]))
        for B in int_mats:
            MB = Matrix(ZZ, B)
            cases.append((
                f"(let ((S {Cnt})) (semiring-matrix->rows (semiring-matrix-mul "
                f"(semiring-matrix-from-rows S {ilit(A)}) (semiring-matrix-from-rows S {ilit(B)}))))",
                [[int(x) for x in row] for row in (MA * MB)]))

    # --- tropical semiring (min,+): Python reference for permanent ---
    Trop = "(tropical-semiring)"
    trop_mats = [[[4, 1], [2, 5]], [[0, 3], [7, 0]], [[2, 9], [9, 2]]]
    def tperm(M):
        n = len(M)
        return min(sum(M[i][p[i]] for i in range(n))
                   for p in permutations(range(n)))
    for A in trop_mats:
        cases.append((
            f"(let ((S {Trop})) (semiring-matrix-permanent (semiring-matrix-from-rows S {ilit(A)})))",
            int(tperm(A))))

    # --- boolean semiring: Python reference for closure (reflexive-transitive) ---
    Bool = "(boolean-semiring)"
    def blit(rows): return rows_lit(rows, lambda b: "#t" if b else "#f")
    bool_mats = [
        [[False, True, False], [False, False, True], [False, False, False]],
        [[True, False], [True, False]],
    ]
    def bclosure(M):
        n = len(M)
        # reflexive-transitive closure (I + M + M^2 + ...), Floyd-Warshall style
        R = [[(M[i][j] or i == j) for j in range(n)] for i in range(n)]
        for k in range(n):
            for i in range(n):
                for j in range(n):
                    if R[i][k] and R[k][j]:
                        R[i][j] = True
        return R
    for A in bool_mats:
        cases.append((
            f"(let ((S {Bool})) (semiring-matrix->rows (semiring-matrix-closure (semiring-matrix-from-rows S {blit(A)}))))",
            bclosure(A)))

    return check_or_snapshot(
        args, "sage-structures-semiring-matrix-test.scm",
        "sage-structures-semiring-matrix", ["(wile algebra)"], cases, "hybrid")


def validate_graph(args):
    """Validate (wile algebra combinatorial-graph) invariants against Sage."""
    print("  graph...", end=" ", flush=True)
    # (wile preset ctor, Sage graph) pairs — both 0-indexed.
    # All presets get spanning-tree-count.
    presets = [
        ("(complete-graph 3)", graphs.CompleteGraph(3)),
        ("(complete-graph 4)", graphs.CompleteGraph(4)),
        ("(cycle-graph 4)",    graphs.CycleGraph(4)),
        ("(cycle-graph 5)",    graphs.CycleGraph(5)),
        ("(path-graph 4)",     graphs.PathGraph(4)),
        ("(complete-bipartite-graph 2 3)", graphs.CompleteBipartiteGraph(2, 3)),
        ("(petersen-graph)",   graphs.PetersenGraph()),
    ]
    # Chromatic polynomial only for graphs within Wile's deletion-contraction
    # cap (|V|+|E| <= 20).  K_n / C_n / tree have closed-form fast paths and
    # always work; K_{2,3} (5V+6E=11) falls through to general case and fits.
    # Petersen (10V+15E=25) exceeds the cap and raises, so it is excluded.
    chrom_presets = [
        ("(complete-graph 3)", graphs.CompleteGraph(3)),
        ("(complete-graph 4)", graphs.CompleteGraph(4)),
        ("(cycle-graph 4)",    graphs.CycleGraph(4)),
        ("(cycle-graph 5)",    graphs.CycleGraph(5)),
        ("(path-graph 4)",     graphs.PathGraph(4)),
        ("(complete-bipartite-graph 2 3)", graphs.CompleteBipartiteGraph(2, 3)),
    ]
    cases = []
    for ctor, G in presets:
        cases.append((f"(graph-spanning-tree-count {ctor})",
                      int(G.spanning_trees_count())))
    for ctor, G in chrom_presets:
        # chromatic polynomial: Wile = ascending integer coeff list.
        chrom = [int(c) for c in G.chromatic_polynomial().coefficients(sparse=False)]
        cases.append((f"(graph-chromatic-polynomial {ctor})", chrom))
    return check_or_snapshot(
        args, "sage-structures-graph-test.scm",
        "sage-structures-graph", ["(wile algebra)"], cases, "Sage-builtin")


def validate_group(args):
    """Validate (wile algebra) groups. cyclic ops -> Sage Zmod(n);
    burnside-count -> Sage orbit counting under cyclic rotation."""
    print("  group...", end=" ", flush=True)
    cases = []

    # --- cyclic group Z/nZ: group-op/-inverse/-order via Sage Zmod(n) ---
    for n in [2, 3, 5, 6]:
        Zn = Zmod(n)
        cases.append((f"(group-order (cyclic-group {n}))", int(n)))
        for a in range(n):
            cases.append((f"(group-inverse (cyclic-group {n}) {a})",
                          int(Zn(-a))))
            for b in range(n):
                cases.append((f"(group-op (cyclic-group {n}) {a} {b})",
                              int(Zn(a + b))))

    # --- Burnside: count distinct k-colourings of an n-cycle under rotation ---
    # Wile: permutation-action of the rotation group on colourings, then
    # burnside-count. Sage oracle: necklace count = (1/n) * sum_d phi(d) k^(n/d).
    def necklace_count(n, k):
        from sage.all import euler_phi, divisors
        return int(sum(euler_phi(d) * k ** (n // d) for d in divisors(n)) // n)

    # Build the rotation group action in Wile and oracle the orbit count.
    # rotation r maps colouring vector index i -> (i+1) mod n; colourings are
    # all length-n lists over 0..k-1. The Wile expression constructs the cyclic
    # rotation action on colourings and counts orbits with burnside-count.
    for n, k in [(3, 2), (4, 2), (4, 3), (5, 2), (6, 2)]:
        wile_expr = (
            f"(let* ((n {n}) (k {k})"
            f"       (colourings (all-tuples n k))"
            f"       (G (cyclic-group n))"
            f"       (act (make-group-action G (lambda (c) #t)"
            f"              (lambda (r c) (rotate-list c r)))))"
            f"  (burnside-count act colourings))")
        cases.append((wile_expr, necklace_count(n, k)))

    # The Burnside cases need two helpers (rotate-list, all-tuples) that do not
    # exist in (wile algebra); inject them via check_or_snapshot's preamble.
    preamble = (
        "(define (rotate-list lst r)\n"
        "  (let ((n (length lst)))\n"
        "    (if (= n 0) lst\n"
        "        (let loop ((i 0) (acc '()))\n"
        "          (if (= i n) (reverse acc)\n"
        "              (loop (+ i 1)\n"
        "                    (cons (list-ref lst (modulo (+ i r) n)) acc)))))))\n"
        "(define (all-tuples n k)\n"
        "  (if (= n 0) '(())\n"
        "      (let ((rest (all-tuples (- n 1) k)))\n"
        "        (apply append\n"
        "          (map (lambda (d) (map (lambda (t) (cons d t)) rest))\n"
        "               (let lp ((i 0) (a '()))\n"
        "                 (if (= i k) (reverse a) (lp (+ i 1) (cons i a)))))))))\n")
    return check_or_snapshot(
        args, "sage-structures-group-test.scm", "sage-structures-group",
        ["(wile algebra)"], cases, "hybrid", preamble=preamble)


def validate_interval(args):
    """Validate (wile algebra) interval arithmetic against a Python reference
    that mirrors Wile's inf-aware endpoint formulas."""
    print("  interval...", end=" ", flush=True)
    NEG, POS = "neg-inf", "pos-inf"

    # Finite endpoints arrive as Sage Integer (preparser); coerce results back
    # to Python int so to_wile_display's isinstance(v, int) check matches.
    def inf_add(a, b):
        if (a == POS and b == NEG) or (a == NEG and b == POS):
            return POS
        if a == POS or b == POS:
            return POS
        if a == NEG or b == NEG:
            return NEG
        return int(a + b)

    def inf_sub(a, b):  # a - b, mirrors interval.scm inf- (cond order matters)
        if (a == POS and b == POS) or (a == NEG and b == NEG):
            return POS
        if a == POS:
            return POS
        if a == NEG:
            return NEG
        if b == POS:
            return NEG
        if b == NEG:
            return POS
        return int(a - b)

    def inf_mul(a, b):
        def sign(x):
            return 0 if (x != POS and x != NEG and x == 0) else (
                1 if (x == POS or (x != NEG and x > 0)) else -1)
        if a == 0 or b == 0:
            return int(0)
        if a in (POS, NEG) or b in (POS, NEG):
            s = sign(a) * sign(b)
            return POS if s > 0 else NEG
        return int(a * b)

    def iv_add(a, b):
        return ("pair", (inf_add(a[0], b[0]), inf_add(a[1], b[1])))

    def iv_sub(a, b):
        return ("pair", (inf_sub(a[0], b[1]), inf_sub(a[1], b[0])))

    def iv_mul(a, b):
        corners = [inf_mul(a[0], b[0]), inf_mul(a[0], b[1]),
                   inf_mul(a[1], b[0]), inf_mul(a[1], b[1])]
        return ("pair", (inf_min(corners), inf_max(corners)))

    def inf_le(x, y):
        if x == NEG or y == POS:
            return True
        if y == NEG or x == POS:
            return False
        return x <= y

    def inf_min(xs):
        m = xs[0]
        for x in xs[1:]:
            m = x if inf_le(x, m) else m
        return m

    def inf_max(xs):
        m = xs[0]
        for x in xs[1:]:
            m = x if inf_le(m, x) else m
        return m

    def lit(x):
        return x if isinstance(x, str) else str(int(x))

    def ivlit(a):  # Scheme literal for an interval operand (a quoted pair)
        return f"'({lit(a[0])} . {lit(a[1])})"

    # (POS, POS) is a degenerate point-at-infinity interval; paired with the
    # others it exercises inf_add(POS, NEG) and inf_sub(POS, POS) — the documented
    # widening quirks (pos-inf + neg-inf = pos-inf, pos-inf - pos-inf = pos-inf)
    # that the finite/one-sided samples never reach.
    samples = [(1, 2), (-1, 2), (-3, -1), (0, 0),
               (NEG, 5), (-5, POS), (NEG, POS), (POS, POS)]
    cases = []
    for a in samples:
        for b in samples:
            cases.append((f"(interval-add {ivlit(a)} {ivlit(b)})", iv_add(a, b)))
            cases.append((f"(interval-sub {ivlit(a)} {ivlit(b)})", iv_sub(a, b)))
            cases.append((f"(interval-mul {ivlit(a)} {ivlit(b)})", iv_mul(a, b)))

    return check_or_snapshot(
        args, "sage-structures-interval-test.scm",
        "sage-structures-interval", ["(wile algebra)"], cases, "Python-reference")


def validate_heyting(args):
    """Validate (wile algebra) powerset Heyting algebra against a Python
    reference. The reference replicates Wile's set-op traversal order exactly
    (union/intersect/set-diff in heyting.scm preserve operand order, NOT
    universe order), so set-valued results match Wile's (display ...) output
    element-for-element. Verifies VALUES; the order is Wile's deterministic
    own order, reproduced rather than re-sorted."""
    print("  heyting...", end=" ", flush=True)
    universe = ["a", "b", "c"]          # the carrier universe (in this order)

    def subsets(u):
        out = [[]]
        for x in u:
            out += [s + [x] for s in out]
        # each subset emitted in universe order (matches Wile operand literals)
        return [[x for x in u if x in set(s)] for s in out]

    subs = subsets(universe)

    # Replicas of Wile's heyting.scm set ops (lines ~85-99). These preserve
    # operand traversal order; do NOT canonicalise to universe order.
    def union(a, b):       # cons a-not-in-b (a's order), then append b
        return [x for x in a if x not in b] + list(b)

    def intersect(a, b):   # a's elements that are in b, in a's order
        return [x for x in a if x in b]

    def set_diff(a, b):    # a's elements not in b, in a's order
        return [x for x in a if x not in b]

    def join(a, b):    return union(a, b)
    def meet(a, b):    return intersect(a, b)
    # Wile derives negate as implies(a, bottom) = union(set-diff(U,a), '());
    # union(x, '()) == x in both content and order, so set_diff(U,a) is the
    # equivalent shortcut (heyting.scm:47).
    def neg(a):        return set_diff(universe, a)
    def implies(a, b): return union(set_diff(universe, a), b)

    def slit(s):  # Scheme quoted list of symbols in universe order
        return "'(" + " ".join(s) + ")"

    def H():
        return f"(powerset-heyting '({' '.join(universe)}))"

    cases = []
    for a in subs:
        cases.append((f"(heyting-negate {H()} {slit(a)})", neg(a)))
        for b in subs:
            cases.append((f"(heyting-leq? {H()} {slit(a)} {slit(b)})",
                          set(a) <= set(b)))
            cases.append((f"(heyting-join {H()} {slit(a)} {slit(b)})",
                          join(a, b)))
            cases.append((f"(heyting-meet {H()} {slit(a)} {slit(b)})",
                          meet(a, b)))
            cases.append((f"(heyting-implies {H()} {slit(a)} {slit(b)})",
                          implies(a, b)))

    return check_or_snapshot(
        args, "sage-structures-heyting-test.scm",
        "sage-structures-heyting", ["(wile algebra)"], cases, "Python-reference")


# ---------------------------------------------------------------------------
# Phase 1 entry point
# ---------------------------------------------------------------------------

def run_phase1(args):
    print("=== Phase 1: Structure Validation ===")
    total_failures = 0
    total_failures += validate_integer_ring(args)
    total_failures += validate_rational_field(args)
    total_failures += validate_modular_ring(args)
    total_failures += validate_powerset_lattice(args)
    total_failures += validate_boolean_semiring(args)
    total_failures += validate_tropical_semiring(args)
    total_failures += validate_polynomial(args)
    total_failures += validate_semiring_matrix(args)
    total_failures += validate_graph(args)
    total_failures += validate_group(args)
    total_failures += validate_interval(args)
    total_failures += validate_heyting(args)
    if total_failures > 0:
        print(f"\nPhase 1: {total_failures} total failures")
    else:
        print("Phase 1: all passed")
    return total_failures

# ---------------------------------------------------------------------------
# Task 5: Term generator and S-expression parser
# ---------------------------------------------------------------------------

def random_term(operators, leaves, max_depth, depth=0):
    """Generate a random term tree.

    Returns either a leaf value or a tuple (op_symbol, [args...]).
    At max_depth or with 30% probability, returns a random leaf.
    Otherwise picks a random operator and recursively generates args.
    """
    if depth >= max_depth or random.random() < 0.3:
        return random.choice(leaves)
    op_symbol, arity = random.choice(operators)
    args = [random_term(operators, leaves, max_depth, depth + 1)
            for _ in range(arity)]
    return (op_symbol, args)


def term_to_sexp(term):
    """Convert a term tuple to S-expression string.

    Leaf (non-tuple): str(term)
    Tuple (op, args): "(op arg1 arg2 ...)"
    """
    if not isinstance(term, tuple):
        return str(term)
    op, args = term
    return "(" + op + " " + " ".join(term_to_sexp(a) for a in args) + ")"


def compute_term_sage(term, sage_ops):
    """Evaluate a term using a dict of Sage callables.

    sage_ops maps operator symbols to functions, plus '_leaf' for leaf conversion.
    Leaf (non-tuple): apply sage_ops['_leaf'] (or identity if missing).
    Tuple: recursively compute args, then call sage_ops[op](*computed_args).
    """
    if not isinstance(term, tuple):
        leaf_fn = sage_ops.get('_leaf')
        if leaf_fn is not None:
            return leaf_fn(term)
        return term
    op, args = term
    computed_args = [compute_term_sage(a, sage_ops) for a in args]
    return sage_ops[op](*computed_args)


def tokenize_sexp(s):
    """Split an S-expression string into a list of tokens.

    Tokens are: '(', ')', or atom strings. Handles nested parens.
    """
    tokens = []
    i = 0
    while i < len(s):
        c = s[i]
        if c in ' \t\n\r':
            i += 1
        elif c == '(':
            tokens.append('(')
            i += 1
        elif c == ')':
            tokens.append(')')
            i += 1
        else:
            # Atom: read until whitespace or paren
            j = i
            while j < len(s) and s[j] not in ' \t\n\r()':
                j += 1
            tokens.append(s[i:j])
            i = j
    return tokens


def parse_sexp(s):
    """Parse Wile's S-expression output back into term tuples.

    Atoms become int (try first), float, or string.
    Lists become (op, [args]) tuples.
    """
    tokens = tokenize_sexp(s.strip())
    if not tokens:
        raise ValueError(f"empty S-expression: {s!r}")
    result, pos = _parse_tokens(tokens, 0)
    if pos != len(tokens):
        raise ValueError(f"trailing tokens after S-expression: {' '.join(tokens[pos:])!r}")
    return result


def _parse_tokens(tokens, pos):
    """Recursive token parser. Returns (parsed_value, next_pos)."""
    if pos >= len(tokens):
        raise ValueError("unexpected end of S-expression")
    if tokens[pos] == '(':
        pos += 1  # skip '('
        elements = []
        while pos < len(tokens) and tokens[pos] != ')':
            elem, pos = _parse_tokens(tokens, pos)
            elements.append(elem)
        if pos >= len(tokens):
            raise ValueError("unclosed parenthesis in S-expression")
        pos += 1  # skip ')'
        if len(elements) == 0:
            return ((), pos)
        # First element is operator, rest are args
        return ((elements[0], elements[1:]), pos)
    else:
        atom = tokens[pos]
        # Try int first, then float, then string
        try:
            return (int(atom), pos + 1)
        except (ValueError, TypeError):
            pass
        try:
            return (float(atom), pos + 1)
        except (ValueError, TypeError):
            pass
        return (atom, pos + 1)


# ---------------------------------------------------------------------------
# Shared run -> parse -> soundness -> snapshot loop for the rewriting validators
# ---------------------------------------------------------------------------

# Both number-keyed normalizers (integer ring, rational field) sort numeric
# atoms ascending and treat compounds as "greater"; the lattice normalizer sorts
# symbol atoms lexicographically. These fragments are emitted verbatim into both
# the batch run and the snapshot, so the committed fixture re-normalizes offline
# exactly as the live check did.
_PROTO_NUMBER_FIRST = """(define proto
  (sexp-term-protocol
    (lambda (a b)
      (cond
        ((and (number? a) (number? b)) (< a b))
        ((number? a) #t)
        ((number? b) #f)
        (else #f)))))"""

_PROTO_SYMBOL_FIRST = """(define proto
  (sexp-term-protocol
    (lambda (a b)
      (cond
        ((and (symbol? a) (symbol? b))
         (string<? (symbol->string a) (symbol->string b)))
        ((symbol? a) #t)
        ((symbol? b) #f)
        (else #f)))))"""


def _norm_setup(proto, theory_expr):
    """Scheme binding `proto` and a `norm` normalizer over THEORY_EXPR. Shared
    between the batch run (setup_scheme) and the snapshot preamble so a fixture
    re-normalizes exactly as the live check did."""
    return (proto + "\n\n"
            "(define norm\n"
            "  (make-recursive-normalizer\n"
            f"    {theory_expr}\n"
            "    proto))")


def check_rewriting_or_snapshot(
        args, *, label, filename, test_name, terms, run_op,
        term_to_sexp_fn, soundness_fn, fail_detail_fn,
        snapshot_case_fn, setup_scheme="", snapshot_preamble=""):
    """Run Wile's normalizer over TERMS, check each result against a soundness
    oracle, and (in snapshot mode) emit a fixture of passing cases.

    The four rewriting validators differ only in the normalizer (`setup_scheme` +
    `run_op`), the term serializer (`term_to_sexp_fn`), the oracle
    (`soundness_fn`), and the snapshot body (`snapshot_preamble` +
    `snapshot_case_fn`). This owns the batch run, the length guard, the per-term
    parse + check, the 5-failure print cap, the don't-snapshot-on-failure guard,
    and the 100-case write cap. Unlike `check_or_snapshot`, the expected value
    here comes from running Wile and judging the output with a soundness oracle,
    not from a precomputed Python value compared by equality.

    run_op : Scheme head applied to each quoted term, e.g. "norm" or
        "symbolic-boolean-normalize". Its `result` (first of the two
        let-values) is written one term per line.
    soundness_fn(original_term, normalized_term) -> (ok, info). `info` rides to
        snapshot_case_fn on pass and to fail_detail_fn on failure (never both for
        one case), so each validator threads whatever its renderers need.
    fail_detail_fn(i, original_term, normalized_sexp, info) -> str.
    snapshot_case_fn(original_term, normalized_sexp, info) -> str (one case)."""
    print(f"  {label}...", end=" ", flush=True)
    imports = ["(wile algebra)", "(wile algebra symbolic)", "(wile algebra rewrite)"]

    lines = ["(import (wile algebra)",
             "        (wile algebra symbolic)",
             "        (wile algebra rewrite))",
             ""]
    if setup_scheme:
        lines.append(setup_scheme)
        lines.append("")
    lines.append("(begin")
    for term in terms:
        sexp = term_to_sexp_fn(term)
        lines.append(
            f"  (let-values (((result trace) ({run_op} '{sexp})))"
            f" (write result) (display #\\newline))")
    lines.append(")")

    output = run_wile("\n".join(lines))
    result_lines = output.strip().split("\n")

    count = len(terms)
    if len(result_lines) != count:
        print(f"\n    ERROR: expected {count} output lines, got {len(result_lines)}")
        return count

    failures = 0
    snapshot_cases = []
    for i, term in enumerate(terms):
        normalized_sexp = result_lines[i].strip()
        normalized_term = parse_sexp(normalized_sexp)
        ok, info = soundness_fn(term, normalized_term)
        if ok:
            snapshot_cases.append((term, normalized_sexp, info))
        else:
            failures += 1
            if args.verbose or failures <= 5:
                print(fail_detail_fn(i, term, normalized_sexp, info))

    if failures == 0:
        print(f"OK ({count} terms)")
    else:
        print(f"\n    {failures}/{count} FAILED")

    if args.snapshot and failures > 0:
        print(f"    WARNING: not writing snapshot due to {failures} failures")
    elif args.snapshot and snapshot_cases:
        body = snapshot_preamble
        for term, normalized_sexp, info in snapshot_cases[:100]:
            body += snapshot_case_fn(term, normalized_sexp, info)
        write_snapshot(filename, test_name, imports, body, args.seed)

    return failures


# ---------------------------------------------------------------------------
# Task 6: Integer ring rewriting soundness
# ---------------------------------------------------------------------------

# term-value evaluator emitted into the integer-ring fixture so each test can
# reduce the normalized symbolic term to the integer Sage computed.
_TERM_VALUE_INT = """;; Evaluate a normalized term to its integer value.
;; The normalizer produces symbolic terms (not arithmetic results),
;; so we need this to compare against Sage's computed values.
(define (term-value t)
  (cond
    ((number? t) t)
    ((not (pair? t)) (error "term-value: unexpected atom" t))
    ((eq? (car t) '+)
     (+ (term-value (cadr t)) (term-value (caddr t))))
    ((eq? (car t) '*)
     (* (term-value (cadr t)) (term-value (caddr t))))
    ((eq? (car t) 'neg)
     (- (term-value (cadr t))))
    (else (error "term-value: unknown operator" (car t)))))"""


def validate_rewriting_integer_ring(args, num_terms=1000):
    """Validate that Wile's integer ring rewriting preserves value."""
    operators = [('+', 2), ('*', 2), ('neg', 1)]
    leaves = list(range(-5, 6))  # -5..5
    terms = [random_term(operators, leaves, 4) for _ in range(num_terms)]

    sage_ops = {
        '+': lambda a, b: a + b,
        '*': lambda a, b: a * b,
        'neg': lambda a: -a,
        '_leaf': lambda x: ZZ(x),
    }

    theory = "(ring->theory (integer-ring) '+ '* 'neg)"
    setup = _norm_setup(_PROTO_NUMBER_FIRST, theory)

    def soundness(term, normalized_term):
        ov = int(compute_term_sage(term, sage_ops))
        nv = int(compute_term_sage(normalized_term, sage_ops))
        return (ov == nv, (ov, nv))

    def fail_detail(i, term, normalized_sexp, info):
        ov, nv = info
        return (f"\n    FAIL [{i}]: {term_to_sexp(term)} = {ov}, "
                f"normalized to {normalized_sexp} = {nv}")

    def snapshot_case(term, normalized_sexp, info):
        original_sexp = term_to_sexp(term)
        expected = info[0]
        return (f";; Original: {original_sexp} = {expected}\n"
                f"(let-values (((result trace) (norm '{original_sexp})))\n"
                f"  (test {expected} (term-value result)))\n\n")

    return check_rewriting_or_snapshot(
        args,
        label="integer-ring rewriting",
        filename="sage-rewriting-integer-ring-test.scm",
        test_name="sage-rewriting-integer-ring",
        terms=terms,
        run_op="norm",
        term_to_sexp_fn=term_to_sexp,
        soundness_fn=soundness,
        fail_detail_fn=fail_detail,
        snapshot_case_fn=snapshot_case,
        setup_scheme=setup,
        snapshot_preamble=_TERM_VALUE_INT + "\n\n" + setup + "\n\n",
    )


# ---------------------------------------------------------------------------
# Task 7: Boolean algebra rewriting soundness
# ---------------------------------------------------------------------------

def compute_bool(term, env):
    """Evaluate a boolean term tree under a variable assignment.

    term is either a string (variable name) or (op, [args]).
    env maps variable names to Python booleans.
    """
    # Bounds produced by complement / identity / annihilator folding under the
    # {#f, #t} carrier that symbolic-boolean-normalize uses: a contradiction
    # normalizes to #f, a tautology to #t.
    if term == '#f':
        return False
    if term == '#t':
        return True
    if isinstance(term, str):
        return env[term]
    op, args = term
    if op == 'or':
        return compute_bool(args[0], env) or compute_bool(args[1], env)
    if op == 'and':
        return compute_bool(args[0], env) and compute_bool(args[1], env)
    if op == 'not':
        return not compute_bool(args[0], env)
    raise ValueError(f"compute_bool: unknown operator {op}")


def truth_table(term):
    """Compute the 8-row truth table for a boolean term over p, q, r.

    Returns a tuple of 8 booleans, one for each assignment of
    (p, q, r) in lexicographic False/True order.
    """
    table = []
    for p in [False, True]:
        for q in [False, True]:
            for r in [False, True]:
                table.append(compute_bool(term, {'p': p, 'q': q, 'r': r}))
    return tuple(table)


def validate_rewriting_boolean(args, num_terms=500):
    """Validate that Wile's boolean algebra rewriting preserves truth tables.

    Exercises the public facade `symbolic-boolean-normalize`, which normalizes
    under the full boolean->theory over a 2-element {#f, #t} Boolean algebra, so
    a contradiction normalizes to #f and a tautology to #t. The fixture asserts
    the structural normal form directly (no term-value evaluator)."""
    operators = [('or', 2), ('and', 2), ('not', 1)]
    leaves = ['p', 'q', 'r']
    terms = [random_term(operators, leaves, 4) for _ in range(num_terms)]

    def soundness(term, normalized_term):
        ott = truth_table(term)
        ntt = truth_table(normalized_term)
        return (ott == ntt, (ott, ntt))

    def fail_detail(i, term, normalized_sexp, info):
        ott, ntt = info
        return (f"\n    FAIL [{i}]: {term_to_sexp(term)}\n"
                f"      original tt:   {ott}\n"
                f"      normalized to: {normalized_sexp}\n"
                f"      normalized tt: {ntt}")

    def snapshot_case(term, normalized_sexp, info):
        original_sexp = term_to_sexp(term)
        return (f";; {original_sexp} normalizes to {normalized_sexp}\n"
                f"(let-values (((result trace) (symbolic-boolean-normalize '{original_sexp})))\n"
                f"  (test '{normalized_sexp} result))\n\n")

    return check_rewriting_or_snapshot(
        args,
        label="boolean-algebra rewriting",
        filename="sage-rewriting-boolean-algebra-test.scm",
        test_name="sage-rewriting-boolean-algebra",
        terms=terms,
        run_op="symbolic-boolean-normalize",
        term_to_sexp_fn=term_to_sexp,
        soundness_fn=soundness,
        fail_detail_fn=fail_detail,
        snapshot_case_fn=snapshot_case,
    )


# ---------------------------------------------------------------------------
# Task 8a: Lattice rewriting soundness
# ---------------------------------------------------------------------------

def compute_lattice(term, env):
    """Evaluate a lattice term tree under a variable assignment.

    term is either a string (variable name) or (op, [args]).
    env maps variable names to Python frozensets.
    """
    # Bounds from identity / annihilator folding over the powerset carrier:
    # bottom is the empty set (), top is the full universe (1 2 3), which
    # parse_sexp yields as an int-headed compound. Neither is join/meet.
    if term == ():
        return frozenset()
    if isinstance(term, str):
        return env[term]
    op, args = term
    if op == 'join':
        return compute_lattice(args[0], env) | compute_lattice(args[1], env)
    if op == 'meet':
        return compute_lattice(args[0], env) & compute_lattice(args[1], env)
    if isinstance(op, int):
        # set literal (i j k ...) -> {i, j, k, ...}; only the top element appears
        return frozenset([op] + list(args))
    raise ValueError(f"compute_lattice: unknown operator {op}")


def lattice_table(term):
    """Compute the evaluation of a lattice term over all 64 substitutions.

    Uses 4 representative subsets of {1,2,3}: empty, singleton, two-element, full.
    Variables: a, b, c. Returns a tuple of 64 frozensets.
    """
    representatives = [
        frozenset(),
        frozenset([1]),
        frozenset([2, 3]),
        frozenset([1, 2, 3]),
    ]
    table = []
    for a in representatives:
        for b in representatives:
            for c in representatives:
                table.append(compute_lattice(term, {'a': a, 'b': b, 'c': c}))
    return tuple(table)


def validate_rewriting_lattice(args, num_terms=500):
    """Validate that Wile's lattice rewriting preserves semantic equivalence.
    Asserts the structural normal form directly (no term-value evaluator)."""
    operators = [('join', 2), ('meet', 2)]
    leaves = ['a', 'b', 'c']
    terms = [random_term(operators, leaves, 4) for _ in range(num_terms)]

    theory = "(lattice->theory (powerset-lattice '(1 2 3)) 'join 'meet)"
    setup = _norm_setup(_PROTO_SYMBOL_FIRST, theory)

    def soundness(term, normalized_term):
        olt = lattice_table(term)
        nlt = lattice_table(normalized_term)
        return (olt == nlt, None)

    def fail_detail(i, term, normalized_sexp, info):
        return (f"\n    FAIL [{i}]: {term_to_sexp(term)}\n"
                f"      normalized to: {normalized_sexp}")

    def snapshot_case(term, normalized_sexp, info):
        original_sexp = term_to_sexp(term)
        return (f";; {original_sexp} normalizes to {normalized_sexp}\n"
                f"(let-values (((result trace) (norm '{original_sexp})))\n"
                f"  (test '{normalized_sexp} result))\n\n")

    return check_rewriting_or_snapshot(
        args,
        label="lattice rewriting",
        filename="sage-rewriting-lattice-test.scm",
        test_name="sage-rewriting-lattice",
        terms=terms,
        run_op="norm",
        term_to_sexp_fn=term_to_sexp,
        soundness_fn=soundness,
        fail_detail_fn=fail_detail,
        snapshot_case_fn=snapshot_case,
        setup_scheme=setup,
        snapshot_preamble=setup + "\n\n",
    )


# ---------------------------------------------------------------------------
# Task 8b: Rational field rewriting soundness
# ---------------------------------------------------------------------------

def parse_rational_leaf(x):
    """Convert a parsed S-expression atom to a Sage rational.

    Handles integers (already int from parse_sexp), strings like '1/2',
    and negative forms like '-1/2'.
    """
    if isinstance(x, int):
        return QQ(x)
    # String form: possibly a rational like "1/2" or "-1/2"
    s = str(x)
    if '/' in s:
        parts = s.split('/')
        if len(parts) != 2:
            raise ValueError(f"parse_rational_leaf: malformed rational {s!r}")
        return QQ(int(parts[0])) / QQ(int(parts[1]))
    return QQ(int(s))


def validate_rewriting_rational_field(args, num_terms=500):
    """Validate that Wile's rational field rewriting preserves value.

    Leaves can be `recip`'d, so terms are generated lazily and any whose Sage
    evaluation divides by zero are skipped before the batch run."""
    operators = [('+', 2), ('*', 2), ('neg', 1), ('recip', 1)]
    # Small non-zero rationals to minimize division-by-zero in nested recip
    rational_leaves = [1, -1, 2, -2, 3, 1/2, -1/2, 1/3]
    # Convert to Sage QQ for leaf generation
    sage_leaves = [QQ(x) for x in rational_leaves]

    sage_ops = {
        '+': lambda a, b: a + b,
        '*': lambda a, b: a * b,
        'neg': lambda a: -a,
        'recip': lambda a: QQ(1)/a,
        '_leaf': parse_rational_leaf,
    }

    # Generate terms, skipping any that cause division by zero
    terms = []
    attempts = 0
    max_attempts = num_terms * 5
    while len(terms) < num_terms and attempts < max_attempts:
        attempts += 1
        term = random_term(operators, sage_leaves, 4)
        try:
            compute_term_sage(term, sage_ops)
            terms.append(term)
        except ZeroDivisionError:
            continue

    if len(terms) < num_terms:
        print(f"    WARNING: only generated {len(terms)}/{num_terms}"
              f" valid terms ({attempts} attempts)")

    # Format a QQ leaf for Scheme output
    def fmt_leaf(q):
        q = QQ(q)
        if q.denominator() == 1:
            return str(int(q.numerator()))
        return f"{int(q.numerator())}/{int(q.denominator())}"

    # Override term_to_sexp for rational leaves
    def rational_term_to_sexp(term):
        if not isinstance(term, tuple):
            return fmt_leaf(term)
        op, args = term
        return "(" + op + " " + " ".join(rational_term_to_sexp(a) for a in args) + ")"

    term_value = (";; Evaluate a normalized term to its rational value.\n"
                  "(define (term-value t)\n"
                  "  (cond\n"
                  "    ((number? t) t)\n"
                  "    ((not (pair? t)) (error \"term-value: unexpected atom\" t))\n"
                  "    ((eq? (car t) '+)\n"
                  "     (+ (term-value (cadr t)) (term-value (caddr t))))\n"
                  "    ((eq? (car t) '*)\n"
                  "     (* (term-value (cadr t)) (term-value (caddr t))))\n"
                  "    ((eq? (car t) 'neg)\n"
                  "     (- (term-value (cadr t))))\n"
                  "    ((eq? (car t) 'recip)\n"
                  "     (/ 1 (term-value (cadr t))))\n"
                  "    (else (error \"term-value: unknown operator\" (car t)))))")

    theory = "(field->theory (rational-field) '+ '* 'neg 'recip)"
    setup = _norm_setup(_PROTO_NUMBER_FIRST, theory)

    def soundness(term, normalized_term):
        ov = compute_term_sage(term, sage_ops)
        try:
            nv = compute_term_sage(normalized_term, sage_ops)
        except ZeroDivisionError:
            return (False, ('zerodiv', ov))
        return (ov == nv, ('val', ov, nv))

    def fail_detail(i, term, normalized_sexp, info):
        if info[0] == 'zerodiv':
            return (f"\n    FAIL [{i}]: normalized form causes division by zero\n"
                    f"      original: {rational_term_to_sexp(term)}\n"
                    f"      normalized to: {normalized_sexp}")
        ov, nv = info[1], info[2]
        return (f"\n    FAIL [{i}]: {rational_term_to_sexp(term)} = {ov}, "
                f"normalized to {normalized_sexp} = {nv}")

    def snapshot_case(term, normalized_sexp, info):
        original_sexp = rational_term_to_sexp(term)
        expected_str = format_rational_expected(info[1])
        return (f";; Original: {original_sexp} = {expected_str}\n"
                f"(let-values (((result trace) (norm '{original_sexp})))\n"
                f"  (test \"{expected_str}\" (number->string (term-value result))))\n\n")

    return check_rewriting_or_snapshot(
        args,
        label="rational-field rewriting",
        filename="sage-rewriting-rational-field-test.scm",
        test_name="sage-rewriting-rational-field",
        terms=terms,
        run_op="norm",
        term_to_sexp_fn=rational_term_to_sexp,
        soundness_fn=soundness,
        fail_detail_fn=fail_detail,
        snapshot_case_fn=snapshot_case,
        setup_scheme=setup,
        snapshot_preamble=term_value + "\n\n" + setup + "\n\n",
    )


# ---------------------------------------------------------------------------
# Phase 2 entry point
# ---------------------------------------------------------------------------

def run_phase2(args):
    print("=== Phase 2: Rewriting Soundness ===")
    total_failures = 0
    total_failures += validate_rewriting_integer_ring(args)
    total_failures += validate_rewriting_boolean(args)
    total_failures += validate_rewriting_lattice(args)
    total_failures += validate_rewriting_rational_field(args)
    if total_failures > 0:
        print(f"\nPhase 2: {total_failures} total failures")
    else:
        print("Phase 2: all passed")
    return total_failures

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()
    random.seed(int(args.seed))

    if not os.path.isfile(WILE_BIN):
        print(f"ERROR: Wile binary not found at {WILE_BIN}", file=sys.stderr)
        print(f"Build with 'make build' or set WILE=/path/to/wile", file=sys.stderr)
        sys.exit(1)

    total = 0
    if args.phase is None or args.phase == "structures":
        total += run_phase1(args)
    if args.phase is None or args.phase == "rewriting":
        total += run_phase2(args)

    if total > 0:
        print(f"\n{total} total failures")
        sys.exit(1)
    else:
        print("\nAll validations passed.")

if __name__ == "__main__":
    main()
