#!/usr/bin/env sage
"""
Validate Wile algebra libraries against SageMath.

Usage:
    sage tools/sage/verify_algebra.sage                    # both phases, live
    sage tools/sage/verify_algebra.sage --phase structures # phase 1 only
    sage tools/sage/verify_algebra.sage --phase rewriting  # phase 2 only
    sage tools/sage/verify_algebra.sage --snapshot         # write .scm files
    sage tools/sage/verify_algebra.sage --seed 123         # custom RNG seed
"""

from sage.all import *
import argparse
import subprocess
import sys
import os
import random
from datetime import date
from itertools import combinations
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

WILE_BIN = os.environ.get("WILE", "./dist/darwin/arm64/wile")
SNAPSHOT_DIR = Path("test/wile/sage-generated")
DEFAULT_SEED = 42
SAGE_VERSION = version()

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(description="Sage oracle for Wile algebra validation")
    p.add_argument("--phase", choices=["structures", "rewriting"],
                   help="Run only one phase (default: both)")
    p.add_argument("--snapshot", action="store_true",
                   help="Write static .scm test files")
    p.add_argument("--seed", type=int, default=DEFAULT_SEED,
                   help=f"RNG seed (default: {DEFAULT_SEED})")
    p.add_argument("--verbose", "-v", action="store_true",
                   help="Print each test case as it runs")
    return p.parse_args()

# ---------------------------------------------------------------------------
# Wile subprocess
# ---------------------------------------------------------------------------

def run_wile(scheme_code):
    """Run Scheme code in Wile subprocess, return stdout string."""
    try:
        result = subprocess.run(
            [WILE_BIN, "-e", scheme_code],
            capture_output=True, text=True, timeout=30,
        )
    except subprocess.TimeoutExpired:
        raise RuntimeError(
            f"Wile timed out after 30s. Code (first 200 chars): {scheme_code[:200]}"
        )
    if result.returncode != 0:
        raise RuntimeError(f"Wile error (exit {result.returncode}): {result.stderr.strip()}")
    return result.stdout.strip()

# ---------------------------------------------------------------------------
# Snapshot writer
# ---------------------------------------------------------------------------

def scm_header(name, seed, filename, oracle_source):
    """Return the standard header comment for generated .scm files."""
    return (
        f";;; {filename} — Generated by Sage oracle\n"
        f";;; Oracle: {SAGE_VERSION}\n"
        f";;; Oracle source: {oracle_source}\n"
        f";;; Date: {date.today().isoformat()}\n"
        f";;; Seed: {seed}\n"
        f";;; DO NOT EDIT — regenerate with:\n"
        f";;;   make sage-snapshot\n"
    )

def write_snapshot(filename, test_name, imports, body, seed, oracle_source="Sage-builtin"):
    """Write a complete .scm test file to SNAPSHOT_DIR."""
    path = SNAPSHOT_DIR / filename
    with open(path, "w") as f:
        f.write(scm_header(test_name, seed, filename, oracle_source))
        f.write(f"\n(import (scheme base)\n        (chibi test)\n")
        for i, imp in enumerate(imports):
            if i == len(imports) - 1:
                f.write(f"        {imp})\n")
            else:
                f.write(f"        {imp}\n")
        f.write(f"\n(test-begin \"{test_name}\")\n\n")
        f.write(body)
        f.write(f"\n(test-end)\n(test-exit)\n")
    print(f"  Wrote {path}")

# ---------------------------------------------------------------------------
# Shared value-formatting + dual-mode driver for new structure validators
# ---------------------------------------------------------------------------

def to_wile_display(v):
    """Format a Python value as the string Wile prints via (display v).
    Supported: bool, int, str (a bare symbol/number token like 'neg-inf' or
    '1/3'), list (Scheme list), and ('pair', (lo, hi)) for a cons pair."""
    if isinstance(v, bool):
        return "#t" if v else "#f"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, str):
        return v
    if isinstance(v, tuple) and len(v) == 2 and v[0] == "pair":
        lo, hi = v[1]
        return f"({to_wile_display(lo)} . {to_wile_display(hi)})"
    if isinstance(v, list):
        return "(" + " ".join(to_wile_display(x) for x in v) + ")"
    raise ValueError(f"to_wile_display: cannot format {v!r}")

def to_wile_test_literal(v):
    """Format a Python value as the EXPECTED arg of (test EXPECTED expr).
    Scalars are bare; compound values (lists, pairs, symbols) are quoted."""
    if isinstance(v, bool):
        return "#t" if v else "#f"
    if isinstance(v, int):
        return str(v)
    return "'" + to_wile_display(v)

def check_or_snapshot(args, filename, test_name, imports, cases, oracle_source):
    """cases: list of (expr_str, expected_python_value). Each expr is a
    self-contained Scheme expression evaluated under `imports`."""
    failures = 0
    if not args.snapshot:
        imp = " ".join(f"(import {i})" for i in imports)
        disp = " ".join(f"(display {e}) (display #\\newline)" for e, _ in cases)
        output = run_wile(f"{imp} (begin {disp})")
        results = output.split("\n") if output else []
        if len(results) != len(cases):
            print(f"\n    ERROR: expected {len(cases)} lines, got {len(results)}")
            return len(cases)
        for i, (e, expected) in enumerate(cases):
            want = to_wile_display(expected)
            got = results[i].strip()
            if got != want:
                failures += 1
                print(f"\n    FAIL: {e}\n      got {got!r}, expected {want!r}")
        print(f"OK ({len(cases)} cases)" if failures == 0
              else f"\n    {failures}/{len(cases)} FAILED")
    else:
        body = "".join(
            f"(test {to_wile_test_literal(exp)} {e})\n" for e, exp in cases)
        write_snapshot(filename, test_name, imports, body, args.seed, oracle_source)
    return failures

# ---------------------------------------------------------------------------
# Phase 1: Structure validators
# ---------------------------------------------------------------------------

def validate_integer_ring(args):
    """Validate Wile's (integer-ring) against Sage's ZZ."""
    print("  integer-ring...", end=" ", flush=True)
    samples = list(range(-10, 11))
    cases = []
    failures = 0

    for a in samples:
        for b in samples:
            expected_plus = ZZ(a) + ZZ(b)
            expected_times = ZZ(a) * ZZ(b)
            expected_minus = ZZ(a) - ZZ(b)
            cases.append((a, b, "ring-plus", int(expected_plus)))
            cases.append((a, b, "ring-times", int(expected_times)))
            cases.append((a, b, "ring-minus", int(expected_minus)))
        expected_neg = -ZZ(a)
        cases.append((a, None, "ring-negate", int(expected_neg)))

    if not args.snapshot:
        scheme = "(import (wile algebra)) (let ((R (integer-ring))) "
        tests = []
        for a, b, op, expected in cases:
            if b is not None:
                tests.append(f"(display ({op} R {a} {b})) (display #\\newline)")
            else:
                tests.append(f"(display ({op} R {a})) (display #\\newline)")
        scheme += " ".join(tests) + ")"
        output = run_wile(scheme)
        results = output.strip().split("\n")
        if len(results) != len(cases):
            print(f"\n    ERROR: expected {len(cases)} output lines, got {len(results)}")
            return len(cases)
        for i, (a, b, op, expected) in enumerate(cases):
            try:
                actual = int(results[i])
            except (ValueError, IndexError) as e:
                failures += 1
                print(f"\n    FAIL: cannot parse output line {i}: {results[i]!r} ({e})")
                continue
            if actual != expected:
                failures += 1
                if b is not None:
                    print(f"\n    FAIL: ({op} R {a} {b}) = {actual}, expected {expected}")
                else:
                    print(f"\n    FAIL: ({op} R {a}) = {actual}, expected {expected}")
        if failures == 0:
            print(f"OK ({len(cases)} cases)")
        else:
            print(f"\n    {failures}/{len(cases)} FAILED")
    else:
        body = "(let ((R (integer-ring)))\n"
        for a, b, op, expected in cases:
            if b is not None:
                body += f"  (test {expected} ({op} R {a} {b}))\n"
            else:
                body += f"  (test {expected} ({op} R {a}))\n"
        body += ")\n"
        write_snapshot(
            "sage-structures-integer-ring-test.scm",
            "sage-structures-integer-ring",
            ["(wile algebra)"],
            body,
            args.seed,
        )

    return failures


def format_rational_for_wile(q):
    """Format a Sage rational for Wile: integers as '3', fractions as '1/3'."""
    if q.denominator() == 1:
        return str(q.numerator())
    return f"{q.numerator()}/{q.denominator()}"


def format_rational_expected(q):
    """Format expected Sage rational to match Wile's display output."""
    if q.denominator() == 1:
        return str(int(q.numerator()))
    return f"{int(q.numerator())}/{int(q.denominator())}"


def validate_rational_field(args):
    """Validate Wile's (rational-field) against Sage's QQ."""
    print("  rational-field...", end=" ", flush=True)

    # Sample values: QQ(n)/QQ(d) for n in -3..3, d in 1..3, deduplicated
    sample_set = set()
    for n in range(-3, 4):
        for d in range(1, 4):
            sample_set.add(QQ(n) / QQ(d))
    samples = sorted(sample_set)

    cases = []
    for a in samples:
        for b in samples:
            expected_plus = a + b
            cases.append((a, b, "field-plus", expected_plus))
            expected_times = a * b
            cases.append((a, b, "field-times", expected_times))
            if b != 0:
                expected_div = a / b
                cases.append((a, b, "field-divide", expected_div))
        expected_neg = -a
        cases.append((a, None, "field-negate", expected_neg))
        if a != 0:
            expected_recip = 1 / a
            cases.append((a, None, "field-reciprocal", expected_recip))

    failures = 0

    if not args.snapshot:
        scheme = "(import (wile algebra)) (let ((F (rational-field))) "
        tests = []
        for a, b, op, expected in cases:
            wa = format_rational_for_wile(a)
            if b is not None:
                wb = format_rational_for_wile(b)
                tests.append(f"(display ({op} F {wa} {wb})) (display #\\newline)")
            else:
                tests.append(f"(display ({op} F {wa})) (display #\\newline)")
        scheme += " ".join(tests) + ")"
        output = run_wile(scheme)
        results = output.strip().split("\n")
        if len(results) != len(cases):
            print(f"\n    ERROR: expected {len(cases)} output lines, got {len(results)}")
            return len(cases)
        for i, (a, b, op, expected) in enumerate(cases):
            actual_str = results[i]
            expected_str = format_rational_expected(expected)
            if actual_str != expected_str:
                failures += 1
                wa = format_rational_for_wile(a)
                if b is not None:
                    wb = format_rational_for_wile(b)
                    print(f"\n    FAIL: ({op} F {wa} {wb}) = {actual_str}, expected {expected_str}")
                else:
                    print(f"\n    FAIL: ({op} F {wa}) = {actual_str}, expected {expected_str}")
        if failures == 0:
            print(f"OK ({len(cases)} cases)")
        else:
            print(f"\n    {failures}/{len(cases)} FAILED")
    else:
        body = "(let ((F (rational-field)))\n"
        for a, b, op, expected in cases:
            wa = format_rational_for_wile(a)
            exp_str = format_rational_expected(expected)
            # For snapshot tests: use string comparison since test framework
            # needs to match Wile's display output for rationals
            if b is not None:
                wb = format_rational_for_wile(b)
                body += f"  (test \"{exp_str}\" (number->string ({op} F {wa} {wb})))\n"
            else:
                body += f"  (test \"{exp_str}\" (number->string ({op} F {wa})))\n"
        body += ")\n"
        write_snapshot(
            "sage-structures-rational-field-test.scm",
            "sage-structures-rational-field",
            ["(wile algebra)"],
            body,
            args.seed,
        )

    return failures


def validate_modular_ring(args):
    """Validate Wile's (modular-ring N) against Sage's Zmod(N)."""
    print("  modular-ring...", end=" ", flush=True)
    moduli = [2, 3, 5, 7, 12]
    failures = 0

    # Build cases per modulus
    all_cases = {}
    for N in moduli:
        R_sage = Zmod(N)
        samples = list(range(N))
        cases = []
        for a in samples:
            for b in samples:
                expected_plus = int(R_sage(a) + R_sage(b))
                cases.append((a, b, "ring-plus", expected_plus))
                expected_times = int(R_sage(a) * R_sage(b))
                cases.append((a, b, "ring-times", expected_times))
                expected_minus = int(R_sage(a) - R_sage(b))
                cases.append((a, b, "ring-minus", expected_minus))
            expected_neg = int(-R_sage(a))
            cases.append((a, None, "ring-negate", expected_neg))
        all_cases[N] = cases

    if not args.snapshot:
        for N in moduli:
            mod_cases = all_cases[N]
            scheme = f"(import (wile algebra)) (let ((R (modular-ring {N}))) "
            tests = []
            for a, b, op, expected in mod_cases:
                if b is not None:
                    tests.append(f"(display ({op} R {a} {b})) (display #\\newline)")
                else:
                    tests.append(f"(display ({op} R {a})) (display #\\newline)")
            scheme += " ".join(tests) + ")"
            output = run_wile(scheme)
            results = output.strip().split("\n")
            if len(results) != len(mod_cases):
                print(f"\n    ERROR [mod {N}]: expected {len(mod_cases)} output lines, got {len(results)}")
                failures += len(mod_cases)
                continue
            for i, (a, b, op, expected) in enumerate(mod_cases):
                try:
                    actual = int(results[i])
                except (ValueError, IndexError) as e:
                    failures += 1
                    print(f"\n    FAIL [mod {N}]: cannot parse output line {i}: {results[i]!r} ({e})")
                    continue
                if actual != expected:
                    failures += 1
                    if b is not None:
                        print(f"\n    FAIL [mod {N}]: ({op} R {a} {b}) = {actual}, expected {expected}")
                    else:
                        print(f"\n    FAIL [mod {N}]: ({op} R {a}) = {actual}, expected {expected}")
        total_cases = sum(len(c) for c in all_cases.values())
        if failures == 0:
            print(f"OK ({total_cases} cases across {len(moduli)} moduli)")
        else:
            print(f"\n    {failures}/{total_cases} FAILED")
    else:
        body = ""
        for N in moduli:
            cases = all_cases[N]
            body += f"(let ((R (modular-ring {N})))\n"
            for a, b, op, expected in cases:
                if b is not None:
                    body += f"  (test {expected} ({op} R {a} {b}))\n"
                else:
                    body += f"  (test {expected} ({op} R {a}))\n"
            body += ")\n\n"
        write_snapshot(
            "sage-structures-modular-ring-test.scm",
            "sage-structures-modular-ring",
            ["(wile algebra)"],
            body,
            args.seed,
        )

    return failures


def validate_powerset_lattice(args):
    """Validate Wile's (powerset-lattice) against Python set operations."""
    print("  powerset-lattice...", end=" ", flush=True)
    universe = [1, 2, 3]
    subsets = []
    for r in range(len(universe) + 1):
        for s in combinations(universe, r):
            subsets.append(frozenset(s))
    cases = []
    failures = 0

    for a in subsets:
        for b in subsets:
            cases.append((a, b, "join", a | b))
            cases.append((a, b, "meet", a & b))
            cases.append((a, b, "leq?", a <= b))

    def fmt_set(s):
        if not s:
            return "'()"
        return "'" + "(" + " ".join(str(x) for x in sorted(s)) + ")"

    def parse_set(s):
        s = s.strip()
        if s == "()" or s == "":
            return frozenset()
        if s.startswith("(") and s.endswith(")"):
            s = s[1:-1]
        if not s.strip():
            return frozenset()
        return frozenset(int(x) for x in s.split())

    if not args.snapshot:
        scheme = "(import (wile algebra)) (let ((L (powerset-lattice '(1 2 3)))) "
        tests = []
        for a, b, op, expected in cases:
            if op == "join":
                tests.append(
                    f"(write (lattice-join L {fmt_set(a)} {fmt_set(b)}))"
                    f" (display #\\newline)")
            elif op == "meet":
                tests.append(
                    f"(write (lattice-meet L {fmt_set(a)} {fmt_set(b)}))"
                    f" (display #\\newline)")
            elif op == "leq?":
                tests.append(
                    f"(display (lattice-leq? L {fmt_set(a)} {fmt_set(b)}))"
                    f" (display #\\newline)")
        scheme += " ".join(tests) + ")"
        output = run_wile(scheme)
        results = output.strip().split("\n")
        if len(results) != len(cases):
            print(f"\n    ERROR: expected {len(cases)} output lines, got {len(results)}")
            return len(cases)
        for i, (a, b, op, expected) in enumerate(cases):
            if op == "leq?":
                expected_str = "#t" if expected else "#f"
                if results[i] != expected_str:
                    failures += 1
                    print(f"\n    FAIL: (lattice-leq? L {fmt_set(a)}"
                          f" {fmt_set(b)}) = {results[i]},"
                          f" expected {expected_str}")
            else:
                if parse_set(results[i]) != expected:
                    failures += 1
                    wile_op = ("lattice-join" if op == "join"
                               else "lattice-meet")
                    print(f"\n    FAIL: ({wile_op} L {fmt_set(a)}"
                          f" {fmt_set(b)}) = {results[i]},"
                          f" expected {sorted(expected)}")
        if failures == 0:
            print(f"OK ({len(cases)} cases)")
        else:
            print(f"\n    {failures}/{len(cases)} FAILED")
    else:
        body = "(let ((L (powerset-lattice '(1 2 3))))\n"
        for a, b, op, expected in cases:
            if op == "leq?":
                exp = "#t" if expected else "#f"
                body += (f"  (test {exp}"
                         f" (lattice-leq? L {fmt_set(a)} {fmt_set(b)}))\n")
            elif op == "join":
                body += (f"  (test {len(expected)}"
                         f" (length (lattice-join L"
                         f" {fmt_set(a)} {fmt_set(b)})))\n")
            elif op == "meet":
                body += (f"  (test {len(expected)}"
                         f" (length (lattice-meet L"
                         f" {fmt_set(a)} {fmt_set(b)})))\n")
        body += ")\n"
        write_snapshot(
            "sage-structures-powerset-lattice-test.scm",
            "sage-structures-powerset-lattice",
            ["(wile algebra)"],
            body,
            args.seed,
        )

    return failures


def validate_boolean_semiring(args):
    """Validate Wile's (boolean-semiring) against truth tables."""
    print("  boolean-semiring...", end=" ", flush=True)
    cases = []
    failures = 0

    for a in [False, True]:
        for b in [False, True]:
            cases.append((a, b, "semiring-plus", a or b))
            cases.append((a, b, "semiring-times", a and b))

    def fmt_bool(v):
        return "#t" if v else "#f"

    if not args.snapshot:
        scheme = "(import (wile algebra)) (let ((S (boolean-semiring))) "
        tests = []
        for a, b, op, expected in cases:
            tests.append(
                f"(display ({op} S {fmt_bool(a)} {fmt_bool(b)}))"
                f" (display #\\newline)")
        scheme += " ".join(tests) + ")"
        output = run_wile(scheme)
        results = output.strip().split("\n")
        if len(results) != len(cases):
            print(f"\n    ERROR: expected {len(cases)} output lines, got {len(results)}")
            return len(cases)
        for i, (a, b, op, expected) in enumerate(cases):
            expected_str = fmt_bool(expected)
            if results[i] != expected_str:
                failures += 1
                print(f"\n    FAIL: ({op} S {fmt_bool(a)} {fmt_bool(b)})"
                      f" = {results[i]}, expected {expected_str}")
        if failures == 0:
            print(f"OK ({len(cases)} cases)")
        else:
            print(f"\n    {failures}/{len(cases)} FAILED")
    else:
        body = "(let ((S (boolean-semiring)))\n"
        for a, b, op, expected in cases:
            body += (f"  (test {fmt_bool(expected)}"
                     f" ({op} S {fmt_bool(a)} {fmt_bool(b)}))\n")
        body += ")\n"
        write_snapshot(
            "sage-structures-boolean-semiring-test.scm",
            "sage-structures-boolean-semiring",
            ["(wile algebra)"],
            body,
            args.seed,
        )

    return failures


def validate_tropical_semiring(args):
    """Validate Wile's (tropical-semiring) against Sage's TropicalSemiring."""
    print("  tropical-semiring...", end=" ", flush=True)
    T = TropicalSemiring(ZZ)
    samples = list(range(0, 11))
    cases = []
    failures = 0

    for a in samples:
        for b in samples:
            tp = T(a) + T(b)  # min
            tt = T(a) * T(b)  # +
            cases.append((a, b, "semiring-plus", int(tp.lift())))
            cases.append((a, b, "semiring-times", int(tt.lift())))

    if not args.snapshot:
        scheme = "(import (wile algebra)) (let ((S (tropical-semiring))) "
        tests = []
        for a, b, op, expected in cases:
            tests.append(
                f"(display ({op} S {a} {b})) (display #\\newline)")
        scheme += " ".join(tests) + ")"
        output = run_wile(scheme)
        results = output.strip().split("\n")
        if len(results) != len(cases):
            print(f"\n    ERROR: expected {len(cases)} output lines, got {len(results)}")
            return len(cases)
        for i, (a, b, op, expected) in enumerate(cases):
            try:
                actual = int(results[i])
            except (ValueError, IndexError) as e:
                failures += 1
                print(f"\n    FAIL: cannot parse output line {i}: {results[i]!r} ({e})")
                continue
            if actual != expected:
                failures += 1
                print(f"\n    FAIL: ({op} S {a} {b})"
                      f" = {actual}, expected {expected}")
        if failures == 0:
            print(f"OK ({len(cases)} cases)")
        else:
            print(f"\n    {failures}/{len(cases)} FAILED")
    else:
        body = "(let ((S (tropical-semiring)))\n"
        for a, b, op, expected in cases:
            body += f"  (test {expected} ({op} S {a} {b}))\n"
        body += ")\n"
        write_snapshot(
            "sage-structures-tropical-semiring-test.scm",
            "sage-structures-tropical-semiring",
            ["(wile algebra)"],
            body,
            args.seed,
        )

    return failures


def validate_polynomial(args):
    """Validate (wile algebra) polynomials against Sage PolynomialRing."""
    print("  polynomial...", end=" ", flush=True)
    Rz = PolynomialRing(ZZ, 'x')
    Rq = PolynomialRing(QQ, 'x')
    coeff_samples = [[], [5], [1, 1], [2, -1], [1, 2, 3], [0, 0, 1], [-1, 0, 1]]

    def zlit(cs):
        return "'(" + " ".join(str(int(c)) for c in cs) + ")"

    def zcoeffs(p):
        return [int(c) for c in p.list()]

    def qcoeffs(p):
        return [format_rational_for_wile(QQ(c)) for c in p.list()]

    cases = []
    P = "(make-poly (integer-ring) "
    for ca in coeff_samples:
        pa = Rz(ca)
        cases.append((f"(poly-coeffs (poly-negate {P}{zlit(ca)})))", zcoeffs(-pa)))
        cases.append((f"(poly-coeffs (poly-derivative {P}{zlit(ca)})))",
                      zcoeffs(pa.derivative())))
        cases.append((f"(poly-degree {P}{zlit(ca)}))", int(pa.degree())))
        cases.append((f"(poly-leading-coeff {P}{zlit(ca)}))",
                      int(pa.list()[-1]) if pa != 0 else int(0)))
        for x in [-2, -1, 0, 1, 2, 3]:
            cases.append((f"(poly-eval {P}{zlit(ca)}) {x})", int(pa(x))))
        for cb in coeff_samples:
            pb = Rz(cb)
            cases.append((f"(poly-coeffs (poly-plus {P}{zlit(ca)}) {P}{zlit(cb)})))",
                          zcoeffs(pa + pb)))
            cases.append((f"(poly-coeffs (poly-minus {P}{zlit(ca)}) {P}{zlit(cb)})))",
                          zcoeffs(pa - pb)))
            cases.append((f"(poly-coeffs (poly-times {P}{zlit(ca)}) {P}{zlit(cb)})))",
                          zcoeffs(pa * pb)))

    # gcd over QQ (Wile requires a field; Sage gcd over QQ is monic — matches).
    Q = "(make-poly (field->ring (rational-field)) "
    gcd_pairs = [([-1, 0, 1], [-1, 1]), ([1, 2, 1], [1, 1]), ([1, 0, 0, 1], [1, 1])]
    for ca, cb in gcd_pairs:
        g = (Rq(ca).gcd(Rq(cb))).monic()
        cases.append((f"(poly-coeffs (poly-gcd {Q}{zlit(ca)}) {Q}{zlit(cb)}) (rational-field)))",
                      qcoeffs(g)))

    return check_or_snapshot(
        args, "sage-structures-polynomial-test.scm",
        "sage-structures-polynomial", ["(wile algebra)"], cases, "Sage-builtin")


# ---------------------------------------------------------------------------
# Phase 1 entry point
# ---------------------------------------------------------------------------

def run_phase1(args):
    print("=== Phase 1: Structure Validation ===")
    total_failures = 0
    total_failures += validate_integer_ring(args)
    total_failures += validate_rational_field(args)
    total_failures += validate_modular_ring(args)
    total_failures += validate_powerset_lattice(args)
    total_failures += validate_boolean_semiring(args)
    total_failures += validate_tropical_semiring(args)
    total_failures += validate_polynomial(args)
    if total_failures > 0:
        print(f"\nPhase 1: {total_failures} total failures")
    else:
        print("Phase 1: all passed")
    return total_failures

# ---------------------------------------------------------------------------
# Task 5: Term generator and S-expression parser
# ---------------------------------------------------------------------------

def random_term(operators, leaves, max_depth, depth=0):
    """Generate a random term tree.

    Returns either a leaf value or a tuple (op_symbol, [args...]).
    At max_depth or with 30% probability, returns a random leaf.
    Otherwise picks a random operator and recursively generates args.
    """
    if depth >= max_depth or random.random() < 0.3:
        return random.choice(leaves)
    op_symbol, arity = random.choice(operators)
    args = [random_term(operators, leaves, max_depth, depth + 1)
            for _ in range(arity)]
    return (op_symbol, args)


def term_to_sexp(term):
    """Convert a term tuple to S-expression string.

    Leaf (non-tuple): str(term)
    Tuple (op, args): "(op arg1 arg2 ...)"
    """
    if not isinstance(term, tuple):
        return str(term)
    op, args = term
    return "(" + op + " " + " ".join(term_to_sexp(a) for a in args) + ")"


def compute_term_sage(term, sage_ops):
    """Evaluate a term using a dict of Sage callables.

    sage_ops maps operator symbols to functions, plus '_leaf' for leaf conversion.
    Leaf (non-tuple): apply sage_ops['_leaf'] (or identity if missing).
    Tuple: recursively compute args, then call sage_ops[op](*computed_args).
    """
    if not isinstance(term, tuple):
        leaf_fn = sage_ops.get('_leaf')
        if leaf_fn is not None:
            return leaf_fn(term)
        return term
    op, args = term
    computed_args = [compute_term_sage(a, sage_ops) for a in args]
    return sage_ops[op](*computed_args)


def tokenize_sexp(s):
    """Split an S-expression string into a list of tokens.

    Tokens are: '(', ')', or atom strings. Handles nested parens.
    """
    tokens = []
    i = 0
    while i < len(s):
        c = s[i]
        if c in ' \t\n\r':
            i += 1
        elif c == '(':
            tokens.append('(')
            i += 1
        elif c == ')':
            tokens.append(')')
            i += 1
        else:
            # Atom: read until whitespace or paren
            j = i
            while j < len(s) and s[j] not in ' \t\n\r()':
                j += 1
            tokens.append(s[i:j])
            i = j
    return tokens


def parse_sexp(s):
    """Parse Wile's S-expression output back into term tuples.

    Atoms become int (try first), float, or string.
    Lists become (op, [args]) tuples.
    """
    tokens = tokenize_sexp(s.strip())
    if not tokens:
        raise ValueError(f"empty S-expression: {s!r}")
    result, pos = _parse_tokens(tokens, 0)
    if pos != len(tokens):
        raise ValueError(f"trailing tokens after S-expression: {' '.join(tokens[pos:])!r}")
    return result


def _parse_tokens(tokens, pos):
    """Recursive token parser. Returns (parsed_value, next_pos)."""
    if pos >= len(tokens):
        raise ValueError("unexpected end of S-expression")
    if tokens[pos] == '(':
        pos += 1  # skip '('
        elements = []
        while pos < len(tokens) and tokens[pos] != ')':
            elem, pos = _parse_tokens(tokens, pos)
            elements.append(elem)
        if pos >= len(tokens):
            raise ValueError("unclosed parenthesis in S-expression")
        pos += 1  # skip ')'
        if len(elements) == 0:
            return ((), pos)
        # First element is operator, rest are args
        return ((elements[0], elements[1:]), pos)
    else:
        atom = tokens[pos]
        # Try int first, then float, then string
        try:
            return (int(atom), pos + 1)
        except (ValueError, TypeError):
            pass
        try:
            return (float(atom), pos + 1)
        except (ValueError, TypeError):
            pass
        return (atom, pos + 1)


# ---------------------------------------------------------------------------
# Task 6: Integer ring rewriting soundness
# ---------------------------------------------------------------------------

def validate_rewriting_integer_ring(args, num_terms=1000):
    """Validate that Wile's integer ring rewriting preserves value."""
    print("  integer-ring rewriting...", end=" ", flush=True)
    failures = 0

    operators = [('+', 2), ('*', 2), ('neg', 1)]
    leaves = list(range(-5, 6))  # -5..5

    # Generate random terms
    terms = [random_term(operators, leaves, 4) for _ in range(num_terms)]

    sage_ops = {
        '+': lambda a, b: a + b,
        '*': lambda a, b: a * b,
        'neg': lambda a: -a,
        '_leaf': lambda x: ZZ(x),
    }

    # Build batch Scheme code: normalize all terms in one subprocess call
    scheme_lines = []
    scheme_lines.append("(import (wile algebra)")
    scheme_lines.append("        (wile algebra symbolic)")
    scheme_lines.append("        (wile algebra rewrite))")
    scheme_lines.append("")
    scheme_lines.append("(define proto")
    scheme_lines.append("  (sexp-term-protocol")
    scheme_lines.append("    (lambda (a b)")
    scheme_lines.append("      (cond")
    scheme_lines.append("        ((and (number? a) (number? b)) (< a b))")
    scheme_lines.append("        ((number? a) #t)")
    scheme_lines.append("        ((number? b) #f)")
    scheme_lines.append("        (else #f)))))")
    scheme_lines.append("")
    scheme_lines.append("(define norm")
    scheme_lines.append("  (make-recursive-normalizer")
    scheme_lines.append("    (ring->theory (integer-ring) '+ '* 'neg)")
    scheme_lines.append("    proto))")
    scheme_lines.append("")

    # Emit each normalization as a separate let-values + write + newline
    scheme_lines.append("(begin")
    for term in terms:
        sexp = term_to_sexp(term)
        scheme_lines.append(
            f"  (let-values (((result trace) (norm '{sexp})))"
            f" (write result) (display #\\newline))")
    scheme_lines.append(")")

    scheme_code = "\n".join(scheme_lines)

    # Run Wile
    output = run_wile(scheme_code)
    result_lines = output.strip().split("\n")

    if len(result_lines) != num_terms:
        print(f"\n    ERROR: expected {num_terms} output lines, got {len(result_lines)}")
        return num_terms  # treat all as failures

    # Check each term
    snapshot_cases = []
    for i, term in enumerate(terms):
        original_value = int(compute_term_sage(term, sage_ops))
        normalized_sexp = result_lines[i].strip()

        # Parse Wile's normalized output back to a term
        normalized_term = parse_sexp(normalized_sexp)

        # Evaluate the normalized term in Sage
        normalized_value = int(compute_term_sage(normalized_term, sage_ops))

        if original_value != normalized_value:
            failures += 1
            if args.verbose or failures <= 5:
                print(f"\n    FAIL [{i}]: {term_to_sexp(term)} = {original_value}, "
                      f"normalized to {normalized_sexp} = {normalized_value}")
        else:
            snapshot_cases.append((term, normalized_sexp, original_value))

    if failures == 0:
        print(f"OK ({num_terms} terms)")
    else:
        print(f"\n    {failures}/{num_terms} FAILED")

    # Snapshot mode: write up to 100 passing cases
    if args.snapshot and failures > 0:
        print(f"    WARNING: not writing snapshot due to {failures} failures")
    elif args.snapshot and len(snapshot_cases) > 0:
        body = ""
        # Term evaluator: recursively compute integer value from symbolic term
        body += ";; Evaluate a normalized term to its integer value.\n"
        body += ";; The normalizer produces symbolic terms (not arithmetic results),\n"
        body += ";; so we need this to compare against Sage's computed values.\n"
        body += "(define (term-value t)\n"
        body += "  (cond\n"
        body += "    ((number? t) t)\n"
        body += "    ((not (pair? t)) (error \"term-value: unexpected atom\" t))\n"
        body += "    ((eq? (car t) '+)\n"
        body += "     (+ (term-value (cadr t)) (term-value (caddr t))))\n"
        body += "    ((eq? (car t) '*)\n"
        body += "     (* (term-value (cadr t)) (term-value (caddr t))))\n"
        body += "    ((eq? (car t) 'neg)\n"
        body += "     (- (term-value (cadr t))))\n"
        body += "    (else (error \"term-value: unknown operator\" (car t)))))\n\n"

        body += "(define proto\n"
        body += "  (sexp-term-protocol\n"
        body += "    (lambda (a b)\n"
        body += "      (cond\n"
        body += "        ((and (number? a) (number? b)) (< a b))\n"
        body += "        ((number? a) #t)\n"
        body += "        ((number? b) #f)\n"
        body += "        (else #f)))))\n\n"
        body += "(define norm\n"
        body += "  (make-recursive-normalizer\n"
        body += "    (ring->theory (integer-ring) '+ '* 'neg)\n"
        body += "    proto))\n\n"

        for term, normalized_sexp, expected in snapshot_cases[:100]:
            original_sexp = term_to_sexp(term)
            body += (f";; Original: {original_sexp} = {expected}\n"
                     f"(let-values (((result trace) (norm '{original_sexp})))\n"
                     f"  (test {expected} (term-value result)))\n\n")

        write_snapshot(
            "sage-rewriting-integer-ring-test.scm",
            "sage-rewriting-integer-ring",
            ["(wile algebra)",
             "(wile algebra symbolic)",
             "(wile algebra rewrite)"],
            body,
            args.seed,
        )

    return failures


# ---------------------------------------------------------------------------
# Task 7: Boolean algebra rewriting soundness
# ---------------------------------------------------------------------------

def compute_bool(term, env):
    """Evaluate a boolean term tree under a variable assignment.

    term is either a string (variable name) or (op, [args]).
    env maps variable names to Python booleans.
    """
    if isinstance(term, str):
        return env[term]
    op, args = term
    if op == 'or':
        return compute_bool(args[0], env) or compute_bool(args[1], env)
    if op == 'and':
        return compute_bool(args[0], env) and compute_bool(args[1], env)
    if op == 'not':
        return not compute_bool(args[0], env)
    raise ValueError(f"compute_bool: unknown operator {op}")


def truth_table(term):
    """Compute the 8-row truth table for a boolean term over p, q, r.

    Returns a tuple of 8 booleans, one for each assignment of
    (p, q, r) in lexicographic False/True order.
    """
    table = []
    for p in [False, True]:
        for q in [False, True]:
            for r in [False, True]:
                table.append(compute_bool(term, {'p': p, 'q': q, 'r': r}))
    return tuple(table)


def validate_rewriting_boolean(args, num_terms=500):
    """Validate that Wile's boolean algebra rewriting preserves truth tables."""
    print("  boolean-algebra rewriting...", end=" ", flush=True)
    failures = 0

    operators = [('or', 2), ('and', 2), ('not', 1)]
    leaves = ['p', 'q', 'r']

    # Generate random terms
    terms = [random_term(operators, leaves, 4) for _ in range(num_terms)]

    # Build batch Scheme code
    scheme_lines = []
    scheme_lines.append("(import (wile algebra)")
    scheme_lines.append("        (wile algebra symbolic)")
    scheme_lines.append("        (wile algebra rewrite))")
    scheme_lines.append("")
    scheme_lines.append("(define proto")
    scheme_lines.append("  (sexp-term-protocol")
    scheme_lines.append("    (lambda (a b)")
    scheme_lines.append("      (cond")
    scheme_lines.append("        ((and (symbol? a) (symbol? b))")
    scheme_lines.append("         (string<? (symbol->string a) (symbol->string b)))")
    scheme_lines.append("        ((symbol? a) #t)")
    scheme_lines.append("        ((symbol? b) #f)")
    scheme_lines.append("        (else #f)))))")
    scheme_lines.append("")
    scheme_lines.append("(define norm")
    scheme_lines.append("  (make-recursive-normalizer")
    scheme_lines.append("    (boolean->theory (powerset-boolean '(x y z)) 'or 'and 'not)")
    scheme_lines.append("    proto))")
    scheme_lines.append("")

    scheme_lines.append("(begin")
    for term in terms:
        sexp = term_to_sexp(term)
        scheme_lines.append(
            f"  (let-values (((result trace) (norm '{sexp})))"
            f" (write result) (display #\\newline))")
    scheme_lines.append(")")

    scheme_code = "\n".join(scheme_lines)

    # Run Wile
    output = run_wile(scheme_code)
    result_lines = output.strip().split("\n")

    if len(result_lines) != num_terms:
        print(f"\n    ERROR: expected {num_terms} output lines, got {len(result_lines)}")
        return num_terms

    # Check each term: truth tables must match
    snapshot_cases = []
    for i, term in enumerate(terms):
        original_tt = truth_table(term)
        normalized_sexp = result_lines[i].strip()

        # Parse Wile's normalized output back to a term
        normalized_term = parse_sexp(normalized_sexp)

        # Compute truth table of normalized term
        normalized_tt = truth_table(normalized_term)

        if original_tt != normalized_tt:
            failures += 1
            if args.verbose or failures <= 5:
                print(f"\n    FAIL [{i}]: {term_to_sexp(term)}")
                print(f"      original tt:   {original_tt}")
                print(f"      normalized to: {normalized_sexp}")
                print(f"      normalized tt: {normalized_tt}")
        else:
            snapshot_cases.append((term, normalized_sexp))

    if failures == 0:
        print(f"OK ({num_terms} terms)")
    else:
        print(f"\n    {failures}/{num_terms} FAILED")

    # Snapshot mode: write up to 100 passing cases
    if args.snapshot and failures > 0:
        print(f"    WARNING: not writing snapshot due to {failures} failures")
    elif args.snapshot and len(snapshot_cases) > 0:
        body = ""
        body += "(define proto\n"
        body += "  (sexp-term-protocol\n"
        body += "    (lambda (a b)\n"
        body += "      (cond\n"
        body += "        ((and (symbol? a) (symbol? b))\n"
        body += "         (string<? (symbol->string a) (symbol->string b)))\n"
        body += "        ((symbol? a) #t)\n"
        body += "        ((symbol? b) #f)\n"
        body += "        (else #f)))))\n\n"
        body += "(define norm\n"
        body += "  (make-recursive-normalizer\n"
        body += "    (boolean->theory (powerset-boolean '(x y z)) 'or 'and 'not)\n"
        body += "    proto))\n\n"

        for term, normalized_sexp in snapshot_cases[:100]:
            original_sexp = term_to_sexp(term)
            body += (f";; {original_sexp} normalizes to {normalized_sexp}\n"
                     f"(let-values (((result trace) (norm '{original_sexp})))\n"
                     f"  (test '{normalized_sexp} result))\n\n")

        write_snapshot(
            "sage-rewriting-boolean-algebra-test.scm",
            "sage-rewriting-boolean-algebra",
            ["(wile algebra)",
             "(wile algebra symbolic)",
             "(wile algebra rewrite)"],
            body,
            args.seed,
        )

    return failures


# ---------------------------------------------------------------------------
# Task 8a: Lattice rewriting soundness
# ---------------------------------------------------------------------------

def compute_lattice(term, env):
    """Evaluate a lattice term tree under a variable assignment.

    term is either a string (variable name) or (op, [args]).
    env maps variable names to Python frozensets.
    """
    if isinstance(term, str):
        return env[term]
    op, args = term
    if op == 'join':
        return compute_lattice(args[0], env) | compute_lattice(args[1], env)
    if op == 'meet':
        return compute_lattice(args[0], env) & compute_lattice(args[1], env)
    raise ValueError(f"compute_lattice: unknown operator {op}")


def lattice_table(term):
    """Compute the evaluation of a lattice term over all 64 substitutions.

    Uses 4 representative subsets of {1,2,3}: empty, singleton, two-element, full.
    Variables: a, b, c. Returns a tuple of 64 frozensets.
    """
    representatives = [
        frozenset(),
        frozenset([1]),
        frozenset([2, 3]),
        frozenset([1, 2, 3]),
    ]
    table = []
    for a in representatives:
        for b in representatives:
            for c in representatives:
                table.append(compute_lattice(term, {'a': a, 'b': b, 'c': c}))
    return tuple(table)


def validate_rewriting_lattice(args, num_terms=500):
    """Validate that Wile's lattice rewriting preserves semantic equivalence."""
    print("  lattice rewriting...", end=" ", flush=True)
    failures = 0

    operators = [('join', 2), ('meet', 2)]
    leaves = ['a', 'b', 'c']

    # Generate random terms
    terms = [random_term(operators, leaves, 4) for _ in range(num_terms)]

    # Build batch Scheme code
    scheme_lines = []
    scheme_lines.append("(import (wile algebra)")
    scheme_lines.append("        (wile algebra symbolic)")
    scheme_lines.append("        (wile algebra rewrite))")
    scheme_lines.append("")
    scheme_lines.append("(define proto")
    scheme_lines.append("  (sexp-term-protocol")
    scheme_lines.append("    (lambda (a b)")
    scheme_lines.append("      (cond")
    scheme_lines.append("        ((and (symbol? a) (symbol? b))")
    scheme_lines.append("         (string<? (symbol->string a) (symbol->string b)))")
    scheme_lines.append("        ((symbol? a) #t)")
    scheme_lines.append("        ((symbol? b) #f)")
    scheme_lines.append("        (else #f)))))")
    scheme_lines.append("")
    scheme_lines.append("(define norm")
    scheme_lines.append("  (make-recursive-normalizer")
    scheme_lines.append("    (lattice->theory (powerset-lattice '(1 2 3)) 'join 'meet)")
    scheme_lines.append("    proto))")
    scheme_lines.append("")

    scheme_lines.append("(begin")
    for term in terms:
        sexp = term_to_sexp(term)
        scheme_lines.append(
            f"  (let-values (((result trace) (norm '{sexp})))"
            f" (write result) (display #\\newline))")
    scheme_lines.append(")")

    scheme_code = "\n".join(scheme_lines)

    # Run Wile
    output = run_wile(scheme_code)
    result_lines = output.strip().split("\n")

    if len(result_lines) != num_terms:
        print(f"\n    ERROR: expected {num_terms} output lines, got {len(result_lines)}")
        return num_terms

    # Check each term: lattice tables must match
    snapshot_cases = []
    for i, term in enumerate(terms):
        original_lt = lattice_table(term)
        normalized_sexp = result_lines[i].strip()

        # Parse Wile's normalized output back to a term
        normalized_term = parse_sexp(normalized_sexp)

        # Compute lattice table of normalized term
        normalized_lt = lattice_table(normalized_term)

        if original_lt != normalized_lt:
            failures += 1
            if args.verbose or failures <= 5:
                print(f"\n    FAIL [{i}]: {term_to_sexp(term)}")
                print(f"      normalized to: {normalized_sexp}")
        else:
            snapshot_cases.append((term, normalized_sexp))

    if failures == 0:
        print(f"OK ({num_terms} terms)")
    else:
        print(f"\n    {failures}/{num_terms} FAILED")

    # Snapshot mode: write up to 100 passing cases
    if args.snapshot and failures > 0:
        print(f"    WARNING: not writing snapshot due to {failures} failures")
    elif args.snapshot and len(snapshot_cases) > 0:
        body = ""
        body += "(define proto\n"
        body += "  (sexp-term-protocol\n"
        body += "    (lambda (a b)\n"
        body += "      (cond\n"
        body += "        ((and (symbol? a) (symbol? b))\n"
        body += "         (string<? (symbol->string a) (symbol->string b)))\n"
        body += "        ((symbol? a) #t)\n"
        body += "        ((symbol? b) #f)\n"
        body += "        (else #f)))))\n\n"
        body += "(define norm\n"
        body += "  (make-recursive-normalizer\n"
        body += "    (lattice->theory (powerset-lattice '(1 2 3)) 'join 'meet)\n"
        body += "    proto))\n\n"

        for term, normalized_sexp in snapshot_cases[:100]:
            original_sexp = term_to_sexp(term)
            body += (f";; {original_sexp} normalizes to {normalized_sexp}\n"
                     f"(let-values (((result trace) (norm '{original_sexp})))\n"
                     f"  (test '{normalized_sexp} result))\n\n")

        write_snapshot(
            "sage-rewriting-lattice-test.scm",
            "sage-rewriting-lattice",
            ["(wile algebra)",
             "(wile algebra symbolic)",
             "(wile algebra rewrite)"],
            body,
            args.seed,
        )

    return failures


# ---------------------------------------------------------------------------
# Task 8b: Rational field rewriting soundness
# ---------------------------------------------------------------------------

def parse_rational_leaf(x):
    """Convert a parsed S-expression atom to a Sage rational.

    Handles integers (already int from parse_sexp), strings like '1/2',
    and negative forms like '-1/2'.
    """
    if isinstance(x, int):
        return QQ(x)
    # String form: possibly a rational like "1/2" or "-1/2"
    s = str(x)
    if '/' in s:
        parts = s.split('/')
        if len(parts) != 2:
            raise ValueError(f"parse_rational_leaf: malformed rational {s!r}")
        return QQ(int(parts[0])) / QQ(int(parts[1]))
    return QQ(int(s))


def validate_rewriting_rational_field(args, num_terms=500):
    """Validate that Wile's rational field rewriting preserves value."""
    print("  rational-field rewriting...", end=" ", flush=True)
    failures = 0

    operators = [('+', 2), ('*', 2), ('neg', 1), ('recip', 1)]
    # Small non-zero rationals to minimize division-by-zero in nested recip
    rational_leaves = [1, -1, 2, -2, 3, 1/2, -1/2, 1/3]
    # Convert to Sage QQ for leaf generation
    sage_leaves = [QQ(x) for x in rational_leaves]

    sage_ops = {
        '+': lambda a, b: a + b,
        '*': lambda a, b: a * b,
        'neg': lambda a: -a,
        'recip': lambda a: QQ(1)/a,
        '_leaf': parse_rational_leaf,
    }

    # Generate terms, skipping any that cause division by zero
    terms = []
    attempts = 0
    max_attempts = num_terms * 5
    while len(terms) < num_terms and attempts < max_attempts:
        attempts += 1
        term = random_term(operators, sage_leaves, 4)
        try:
            compute_term_sage(term, sage_ops)
            terms.append(term)
        except ZeroDivisionError:
            continue

    actual_count = len(terms)
    if actual_count < num_terms:
        print(f"\n    WARNING: only generated {actual_count}/{num_terms}"
              f" valid terms ({attempts} attempts)")

    # Format a QQ leaf for Scheme output
    def fmt_leaf(q):
        q = QQ(q)
        if q.denominator() == 1:
            return str(int(q.numerator()))
        return f"{int(q.numerator())}/{int(q.denominator())}"

    # Override term_to_sexp for rational leaves
    def rational_term_to_sexp(term):
        if not isinstance(term, tuple):
            return fmt_leaf(term)
        op, args = term
        return "(" + op + " " + " ".join(rational_term_to_sexp(a) for a in args) + ")"

    # Build batch Scheme code
    scheme_lines = []
    scheme_lines.append("(import (wile algebra)")
    scheme_lines.append("        (wile algebra symbolic)")
    scheme_lines.append("        (wile algebra rewrite))")
    scheme_lines.append("")
    scheme_lines.append("(define proto")
    scheme_lines.append("  (sexp-term-protocol")
    scheme_lines.append("    (lambda (a b)")
    scheme_lines.append("      (cond")
    scheme_lines.append("        ((and (number? a) (number? b)) (< a b))")
    scheme_lines.append("        ((number? a) #t)")
    scheme_lines.append("        ((number? b) #f)")
    scheme_lines.append("        (else #f)))))")
    scheme_lines.append("")
    scheme_lines.append("(define norm")
    scheme_lines.append("  (make-recursive-normalizer")
    scheme_lines.append("    (field->theory (rational-field) '+ '* 'neg 'recip)")
    scheme_lines.append("    proto))")
    scheme_lines.append("")

    scheme_lines.append("(begin")
    for term in terms:
        sexp = rational_term_to_sexp(term)
        scheme_lines.append(
            f"  (let-values (((result trace) (norm '{sexp})))"
            f" (write result) (display #\\newline))")
    scheme_lines.append(")")

    scheme_code = "\n".join(scheme_lines)

    # Run Wile
    output = run_wile(scheme_code)
    result_lines = output.strip().split("\n")

    if len(result_lines) != actual_count:
        print(f"\n    ERROR: expected {actual_count} output lines, got {len(result_lines)}")
        return actual_count

    # Check each term
    snapshot_cases = []
    for i, term in enumerate(terms):
        original_value = compute_term_sage(term, sage_ops)
        normalized_sexp = result_lines[i].strip()

        # Parse Wile's normalized output back to a term
        normalized_term = parse_sexp(normalized_sexp)

        # Evaluate the normalized term in Sage
        try:
            normalized_value = compute_term_sage(normalized_term, sage_ops)
        except ZeroDivisionError:
            failures += 1
            if args.verbose or failures <= 5:
                print(f"\n    FAIL [{i}]: normalized form causes division by zero")
                print(f"      original: {rational_term_to_sexp(term)}")
                print(f"      normalized to: {normalized_sexp}")
            continue

        if original_value != normalized_value:
            failures += 1
            if args.verbose or failures <= 5:
                print(f"\n    FAIL [{i}]: {rational_term_to_sexp(term)} = {original_value}, "
                      f"normalized to {normalized_sexp} = {normalized_value}")
        else:
            snapshot_cases.append((term, normalized_sexp, original_value))

    if failures == 0:
        print(f"OK ({actual_count} terms)")
    else:
        print(f"\n    {failures}/{actual_count} FAILED")

    # Snapshot mode: write up to 100 passing cases
    if args.snapshot and failures > 0:
        print(f"    WARNING: not writing snapshot due to {failures} failures")
    elif args.snapshot and len(snapshot_cases) > 0:
        body = ""
        body += ";; Evaluate a normalized term to its rational value.\n"
        body += "(define (term-value t)\n"
        body += "  (cond\n"
        body += "    ((number? t) t)\n"
        body += "    ((not (pair? t)) (error \"term-value: unexpected atom\" t))\n"
        body += "    ((eq? (car t) '+)\n"
        body += "     (+ (term-value (cadr t)) (term-value (caddr t))))\n"
        body += "    ((eq? (car t) '*)\n"
        body += "     (* (term-value (cadr t)) (term-value (caddr t))))\n"
        body += "    ((eq? (car t) 'neg)\n"
        body += "     (- (term-value (cadr t))))\n"
        body += "    ((eq? (car t) 'recip)\n"
        body += "     (/ 1 (term-value (cadr t))))\n"
        body += "    (else (error \"term-value: unknown operator\" (car t)))))\n\n"

        body += "(define proto\n"
        body += "  (sexp-term-protocol\n"
        body += "    (lambda (a b)\n"
        body += "      (cond\n"
        body += "        ((and (number? a) (number? b)) (< a b))\n"
        body += "        ((number? a) #t)\n"
        body += "        ((number? b) #f)\n"
        body += "        (else #f)))))\n\n"
        body += "(define norm\n"
        body += "  (make-recursive-normalizer\n"
        body += "    (field->theory (rational-field) '+ '* 'neg 'recip)\n"
        body += "    proto))\n\n"

        for term, normalized_sexp, expected in snapshot_cases[:100]:
            original_sexp = rational_term_to_sexp(term)
            expected_str = format_rational_expected(expected)
            body += (f";; Original: {original_sexp} = {expected_str}\n"
                     f"(let-values (((result trace) (norm '{original_sexp})))\n"
                     f"  (test \"{expected_str}\" (number->string (term-value result))))\n\n")

        write_snapshot(
            "sage-rewriting-rational-field-test.scm",
            "sage-rewriting-rational-field",
            ["(wile algebra)",
             "(wile algebra symbolic)",
             "(wile algebra rewrite)"],
            body,
            args.seed,
        )

    return failures


# ---------------------------------------------------------------------------
# Phase 2 entry point
# ---------------------------------------------------------------------------

def run_phase2(args):
    print("=== Phase 2: Rewriting Soundness ===")
    total_failures = 0
    total_failures += validate_rewriting_integer_ring(args)
    total_failures += validate_rewriting_boolean(args)
    total_failures += validate_rewriting_lattice(args)
    total_failures += validate_rewriting_rational_field(args)
    if total_failures > 0:
        print(f"\nPhase 2: {total_failures} total failures")
    else:
        print("Phase 2: all passed")
    return total_failures

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()
    random.seed(int(args.seed))

    if not os.path.isfile(WILE_BIN):
        print(f"ERROR: Wile binary not found at {WILE_BIN}", file=sys.stderr)
        print(f"Build with 'make build' or set WILE=/path/to/wile", file=sys.stderr)
        sys.exit(1)

    total = 0
    if args.phase is None or args.phase == "structures":
        total += run_phase1(args)
    if args.phase is None or args.phase == "rewriting":
        total += run_phase2(args)

    if total > 0:
        print(f"\n{total} total failures")
        sys.exit(1)
    else:
        print("\nAll validations passed.")

if __name__ == "__main__":
    main()
