;; scope-ops manifest — raw slice operations on a hygiene scope set.
;;
;; GENERATED by tools/cmd/scopeopslint; asserted by TestScopeOpsManifest in
;; pkg/values. Regenerate with:
;;
;;   WILE_SCOPE_OPS_UPDATE=1 go test -count=1 -run TestScopeOpsManifest ./pkg/values/
;;
;; Baseline. At the pre-flip commit d2927bea the same walk read 423 operations —
;; 94 non-test, 329 test — over 49 files, out of 91 files holding any
;; scope-slice-typed expression. A scope set was []*syntax.Scope / []*values.Scope
;; then; it is now the opaque values.Scopes persistent chain, which exposes no
;; Slice() and no indexed access because member order is an implementation
;; invariant rather than part of the contract. Run with -noalias to see what the
;; alias trap measures instead: 118 operations over 11 files at that same commit,
;; out of 13 files holding any scope-slice-typed expression rather than 91,
;; because syntax.Scope is a type ALIAS of values.Scope and without types.Unalias
;; the walk sees only pkg/values.
;;
;; What is measured. Every expression go/types types as []*values.Scope, after
;; types.Unalias, classified by what its PARENT node does to it: len, cap, range,
;; index, slice expression, append, copy, clear, make, new, conversion, composite
;; literal (EMPTY ONES INCLUDED), comparison against nil, or use as an argument to
;; a slices.*, sort.* or reflect.* helper. Reading, passing or storing the value is
;; not an operation.
;;
;; How to read a diff. Each row is a CEILING, not an equality: (path count) grants
;; that file at most count operations, and a file with no row is granted zero.
;; Removing operations passes, and the manifest is then ratcheted down by
;; regenerating. A row APPEARING is a defect rather than drift — the representation
;; it operates on no longer exists as a contract, so a new site is code that
;; reintroduced it. NEVER regenerate to silence a diff you have not read.
;;
;; The two non-test rows are the boundary, and they are the only ones permitted:
;; ScopesFromSlice is the declared slice→Scopes constructor, so it necessarily
;; ranges its input, and SourceContext.WithScope hands it a one-element literal on
;; the nil-receiver path. TestScopeOpsManifest names both and rejects any third.
;;
;; Measured at generation: 245 operation(s) — 1 non-test, 244 test — over 23
;; file(s), out of 25 file(s) holding any scope-slice-typed expression.
;;
(("pkg/environment/ambiguous_binding_test.go" 15)
 ("pkg/environment/binding_test.go" 5)
 ("pkg/environment/bulk_source_test.go" 2)
 ("pkg/environment/environment_coverage_test.go" 20)
 ("pkg/environment/environment_frame_test.go" 25)
 ("pkg/environment/global_environment_frame_ranked_test.go" 14)
 ("pkg/environment/global_environment_frame_test.go" 17)
 ("pkg/environment/nil_create_not_wildcard_test.go" 1)
 ("pkg/internal/match/literal_match_test.go" 9)
 ("pkg/internal/match/syntax_adapter_test.go" 1)
 ("pkg/internal/match/syntax_expand_test.go" 22)
 ("pkg/internal/validate/escape_sound_test.go" 2)
 ("pkg/internal/validate/frame_reclaim_build_test.go" 13)
 ("pkg/internal/validate/shadow_scope_test.go" 3)
 ("pkg/internal/validate/sharedtest_test.go" 1)
 ("pkg/internal/validate/validate_test.go" 2)
 ("pkg/machine/compilation/expander_use_site_test.go" 2)
 ("pkg/machine/compilation/literal_probe_ambient_test.go" 18)
 ("pkg/syntax/coverage_extra_test.go" 2)
 ("pkg/syntax/coverage_test.go" 35)
 ("pkg/values/scope_set_test.go" 4)
 ("pkg/values/scopes.go" 1)
 ("pkg/values/scopes_test.go" 31))
